// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multiadminservice.proto

package multiadmin

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	multigatewaymanagerdata "github.com/multigres/multigres/go/pb/multigatewaymanagerdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType indicates the type of async job
type JobType int32

const (
	JobType_JOB_TYPE_UNKNOWN JobType = 0
	JobType_JOB_TYPE_BACKUP  JobType = 1
	JobType_JOB_TYPE_RESTORE JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNKNOWN",
		1: "JOB_TYPE_BACKUP",
		2: "JOB_TYPE_RESTORE",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNKNOWN": 0,
		"JOB_TYPE_BACKUP":  1,
		"JOB_TYPE_RESTORE": 2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{0}
}

// JobStatus indicates the current state of an async job
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNKNOWN   JobStatus = 0
	JobStatus_JOB_STATUS_PENDING   JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING   JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED JobStatus = 3
	JobStatus_JOB_STATUS_FAILED    JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNKNOWN",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNKNOWN":   0,
		"JOB_STATUS_PENDING":   1,
		"JOB_STATUS_RUNNING":   2,
		"JOB_STATUS_COMPLETED": 3,
		"JOB_STATUS_FAILED":    4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{1}
}

// BackupStatus indicates the state of a backup artifact
type BackupStatus int32

const (
	BackupStatus_BACKUP_STATUS_UNKNOWN    BackupStatus = 0
	BackupStatus_BACKUP_STATUS_INCOMPLETE BackupStatus = 1
	BackupStatus_BACKUP_STATUS_COMPLETE   BackupStatus = 2
	BackupStatus_BACKUP_STATUS_FAILED     BackupStatus = 3
)

// Enum value maps for BackupStatus.
var (
	BackupStatus_name = map[int32]string{
		0: "BACKUP_STATUS_UNKNOWN",
		1: "BACKUP_STATUS_INCOMPLETE",
		2: "BACKUP_STATUS_COMPLETE",
		3: "BACKUP_STATUS_FAILED",
	}
	BackupStatus_value = map[string]int32{
		"BACKUP_STATUS_UNKNOWN":    0,
		"BACKUP_STATUS_INCOMPLETE": 1,
		"BACKUP_STATUS_COMPLETE":   2,
		"BACKUP_STATUS_FAILED":     3,
	}
)

func (x BackupStatus) Enum() *BackupStatus {
	p := new(BackupStatus)
	*p = x
	return p
}

func (x BackupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_multiadminservice_proto_enumTypes[2].Descriptor()
}

func (BackupStatus) Type() protoreflect.EnumType {
	return &file_multiadminservice_proto_enumTypes[2]
}

func (x BackupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupStatus.Descriptor instead.
func (BackupStatus) EnumDescriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{2}
}

// GetCellRequest specifies the cell to retrieve
type GetCellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the cell to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellRequest) Reset() {
	*x = GetCellRequest{}
	mi := &file_multiadminservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellRequest) ProtoMessage() {}

func (x *GetCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellRequest.ProtoReflect.Descriptor instead.
func (*GetCellRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetCellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetCellResponse contains the cell information
type GetCellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cell contains the Cell protobuf object
	Cell          *clustermetadata.Cell `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellResponse) Reset() {
	*x = GetCellResponse{}
	mi := &file_multiadminservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellResponse) ProtoMessage() {}

func (x *GetCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellResponse.ProtoReflect.Descriptor instead.
func (*GetCellResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetCellResponse) GetCell() *clustermetadata.Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

// GetDatabaseRequest specifies the database to retrieve
type GetDatabaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the database to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseRequest) Reset() {
	*x = GetDatabaseRequest{}
	mi := &file_multiadminservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseRequest) ProtoMessage() {}

func (x *GetDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetDatabaseResponse contains the database information
type GetDatabaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database contains the Database protobuf object
	Database      *clustermetadata.Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseResponse) Reset() {
	*x = GetDatabaseResponse{}
	mi := &file_multiadminservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseResponse) ProtoMessage() {}

func (x *GetDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetDatabaseResponse) GetDatabase() *clustermetadata.Database {
	if x != nil {
		return x.Database
	}
	return nil
}

// GetCellNamesRequest requests all cell names
type GetCellNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellNamesRequest) Reset() {
	*x = GetCellNamesRequest{}
	mi := &file_multiadminservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesRequest) ProtoMessage() {}

func (x *GetCellNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellNamesRequest.ProtoReflect.Descriptor instead.
func (*GetCellNamesRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{4}
}

// GetCellNamesResponse contains all cell names
type GetCellNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellNamesResponse) Reset() {
	*x = GetCellNamesResponse{}
	mi := &file_multiadminservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellNamesResponse) ProtoMessage() {}

func (x *GetCellNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellNamesResponse.ProtoReflect.Descriptor instead.
func (*GetCellNamesResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetCellNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// GetDatabaseNamesRequest requests all database names
type GetDatabaseNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseNamesRequest) Reset() {
	*x = GetDatabaseNamesRequest{}
	mi := &file_multiadminservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesRequest) ProtoMessage() {}

func (x *GetDatabaseNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseNamesRequest.ProtoReflect.Descriptor instead.
func (*GetDatabaseNamesRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{6}
}

// GetDatabaseNamesResponse contains all database names
type GetDatabaseNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatabaseNamesResponse) Reset() {
	*x = GetDatabaseNamesResponse{}
	mi := &file_multiadminservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatabaseNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatabaseNamesResponse) ProtoMessage() {}

func (x *GetDatabaseNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatabaseNamesResponse.ProtoReflect.Descriptor instead.
func (*GetDatabaseNamesResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatabaseNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// GetGatewaysRequest requests gateways with optional filtering
type GetGatewaysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells         []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewaysRequest) Reset() {
	*x = GetGatewaysRequest{}
	mi := &file_multiadminservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysRequest) ProtoMessage() {}

func (x *GetGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewaysRequest.ProtoReflect.Descriptor instead.
func (*GetGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetGatewaysRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// GetGatewaysResponse contains the filtered gateways
type GetGatewaysResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Gateways      []*clustermetadata.MultiGateway `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewaysResponse) Reset() {
	*x = GetGatewaysResponse{}
	mi := &file_multiadminservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewaysResponse) ProtoMessage() {}

func (x *GetGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewaysResponse.ProtoReflect.Descriptor instead.
func (*GetGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetGatewaysResponse) GetGateways() []*clustermetadata.MultiGateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

// GetPoolersRequest requests poolers with optional filtering
type GetPoolersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	// database name to filter by (optional)
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// shard name to filter by (optional)
	Shard         string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolersRequest) Reset() {
	*x = GetPoolersRequest{}
	mi := &file_multiadminservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersRequest) ProtoMessage() {}

func (x *GetPoolersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolersRequest.ProtoReflect.Descriptor instead.
func (*GetPoolersRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{10}
}

func (x *GetPoolersRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *GetPoolersRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetPoolersRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

// GetPoolersResponse contains the filtered poolers
type GetPoolersResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Poolers       []*clustermetadata.MultiPooler `protobuf:"bytes,1,rep,name=poolers,proto3" json:"poolers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolersResponse) Reset() {
	*x = GetPoolersResponse{}
	mi := &file_multiadminservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolersResponse) ProtoMessage() {}

func (x *GetPoolersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolersResponse.ProtoReflect.Descriptor instead.
func (*GetPoolersResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{11}
}

func (x *GetPoolersResponse) GetPoolers() []*clustermetadata.MultiPooler {
	if x != nil {
		return x.Poolers
	}
	return nil
}

// GetOrchsRequest requests orchestrators with optional filtering
type GetOrchsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cells is a comma-separated list of cell names to filter by (optional)
	Cells         []string `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrchsRequest) Reset() {
	*x = GetOrchsRequest{}
	mi := &file_multiadminservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsRequest) ProtoMessage() {}

func (x *GetOrchsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrchsRequest.ProtoReflect.Descriptor instead.
func (*GetOrchsRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrchsRequest) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// GetOrchsResponse contains the filtered orchestrators
type GetOrchsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
	Orchs         []*clustermetadata.MultiOrch `protobuf:"bytes,1,rep,name=orchs,proto3" json:"orchs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrchsResponse) Reset() {
	*x = GetOrchsResponse{}
	mi := &file_multiadminservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrchsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrchsResponse) ProtoMessage() {}

func (x *GetOrchsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrchsResponse.ProtoReflect.Descriptor instead.
func (*GetOrchsResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrchsResponse) GetOrchs() []*clustermetadata.MultiOrch {
	if x != nil {
		return x.Orchs
	}
	return nil
}

// BackupRequest requests an async backup of a specific shard
type BackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database name (required)
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// table_group name (required)
	TableGroup string `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard name (required)
	Shard string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	// type of backup: "full", "differential", or "incremental" (required)
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// force_primary forces the backup to run on the primary instead of a replica.
	// This should typically be false because backups on replicas reduce load on the primary.
	ForcePrimary  bool `protobuf:"varint,5,opt,name=force_primary,json=forcePrimary,proto3" json:"force_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_multiadminservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{14}
}

func (x *BackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BackupRequest) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *BackupRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *BackupRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BackupRequest) GetForcePrimary() bool {
	if x != nil {
		return x.ForcePrimary
	}
	return false
}

// BackupResponse contains the job ID for tracking the async backup
type BackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for tracking this backup job
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_multiadminservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{15}
}

func (x *BackupResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// RestoreFromBackupRequest requests an async restore of a specific shard
type RestoreFromBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database name (required)
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// table_group name (required)
	TableGroup string `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard name (required)
	Shard string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	// backup_id to restore from (optional, empty means "latest backup")
	BackupId string `protobuf:"bytes,4,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// pooler_id identifies which multipooler to restore to (required).
	// This is needed because a cell can have multiple poolers for the same
	// database/table_group/shard combination. Restores are only allowed to standbys.
	PoolerId      *clustermetadata.ID `protobuf:"bytes,5,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromBackupRequest) Reset() {
	*x = RestoreFromBackupRequest{}
	mi := &file_multiadminservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromBackupRequest) ProtoMessage() {}

func (x *RestoreFromBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreFromBackupRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreFromBackupRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *RestoreFromBackupRequest) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

// RestoreFromBackupResponse contains the job ID for tracking the async restore
type RestoreFromBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for tracking this restore job
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFromBackupResponse) Reset() {
	*x = RestoreFromBackupResponse{}
	mi := &file_multiadminservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFromBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFromBackupResponse) ProtoMessage() {}

func (x *RestoreFromBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFromBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreFromBackupResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{17}
}

func (x *RestoreFromBackupResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetBackupJobStatusRequest requests the status of a backup or restore job
type GetBackupJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id to query (required)
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Shard context for fallback lookup via MultiPooler when job is not in memory.
	// Required when job may have been lost due to process restart.
	Database      string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	TableGroup    string `protobuf:"bytes,3,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	Shard         string `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupJobStatusRequest) Reset() {
	*x = GetBackupJobStatusRequest{}
	mi := &file_multiadminservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupJobStatusRequest) ProtoMessage() {}

func (x *GetBackupJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBackupJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{18}
}

func (x *GetBackupJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetBackupJobStatusRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetBackupJobStatusRequest) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *GetBackupJobStatusRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

// GetBackupJobStatusResponse contains the current status of a backup or restore job
type GetBackupJobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for this job
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// job_type indicates whether this is a backup or restore job
	JobType JobType `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=multiadmin.JobType" json:"job_type,omitempty"`
	// status indicates the current state of the job
	Status JobStatus `protobuf:"varint,3,opt,name=status,proto3,enum=multiadmin.JobStatus" json:"status,omitempty"`
	// error_message contains the error if status is FAILED
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Original request context
	Database   string `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	TableGroup string `protobuf:"bytes,6,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	Shard      string `protobuf:"bytes,7,opt,name=shard,proto3" json:"shard,omitempty"`
	// For backup jobs
	BackupType string `protobuf:"bytes,8,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"` // "full", "differential", "incremental"
	// For restore jobs
	RequestedBackupId string `protobuf:"bytes,10,opt,name=requested_backup_id,json=requestedBackupId,proto3" json:"requested_backup_id,omitempty"` // What was requested (may be empty for "latest")
	// Results (set when status = COMPLETED)
	// For backup: created backup_id
	// For restore: backup_id that was restored
	BackupId      string `protobuf:"bytes,11,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupJobStatusResponse) Reset() {
	*x = GetBackupJobStatusResponse{}
	mi := &file_multiadminservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupJobStatusResponse) ProtoMessage() {}

func (x *GetBackupJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBackupJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{19}
}

func (x *GetBackupJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNKNOWN
}

func (x *GetBackupJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNKNOWN
}

func (x *GetBackupJobStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetBackupType() string {
	if x != nil {
		return x.BackupType
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetRequestedBackupId() string {
	if x != nil {
		return x.RequestedBackupId
	}
	return ""
}

func (x *GetBackupJobStatusResponse) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

// GetBackupsRequest requests a list of backup artifacts with optional filtering
type GetBackupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database name to filter by (optional, empty means all databases)
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// table_group name to filter by (optional, empty means all table groups)
	TableGroup string `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard name to filter by (optional, empty means all shards)
	Shard string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	// limit on number of results (optional, 0 means no limit)
	Limit         uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupsRequest) Reset() {
	*x = GetBackupsRequest{}
	mi := &file_multiadminservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsRequest) ProtoMessage() {}

func (x *GetBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupsRequest.ProtoReflect.Descriptor instead.
func (*GetBackupsRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{20}
}

func (x *GetBackupsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetBackupsRequest) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *GetBackupsRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *GetBackupsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetBackupsResponse contains the list of backup artifacts
type GetBackupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// backups is the list of backup information
	Backups       []*BackupInfo `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupsResponse) Reset() {
	*x = GetBackupsResponse{}
	mi := &file_multiadminservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupsResponse) ProtoMessage() {}

func (x *GetBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupsResponse.ProtoReflect.Descriptor instead.
func (*GetBackupsResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{21}
}

func (x *GetBackupsResponse) GetBackups() []*BackupInfo {
	if x != nil {
		return x.Backups
	}
	return nil
}

// ExpireBackupsRequest requests expiration of old backups
type ExpireBackupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database name (required)
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// table_group name (required)
	TableGroup string `protobuf:"bytes,2,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard name (required)
	Shard string `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	// Optional overrides for pgbackrest expire command-line flags.
	Overrides     map[string]string `protobuf:"bytes,4,rep,name=overrides,proto3" json:"overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireBackupsRequest) Reset() {
	*x = ExpireBackupsRequest{}
	mi := &file_multiadminservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireBackupsRequest) ProtoMessage() {}

func (x *ExpireBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireBackupsRequest.ProtoReflect.Descriptor instead.
func (*ExpireBackupsRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{22}
}

func (x *ExpireBackupsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ExpireBackupsRequest) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *ExpireBackupsRequest) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *ExpireBackupsRequest) GetOverrides() map[string]string {
	if x != nil {
		return x.Overrides
	}
	return nil
}

// ExpireBackupsResponse contains the result of backup expiration
type ExpireBackupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IDs of backups that were removed by the expiration.
	ExpiredBackupIds []string `protobuf:"bytes,1,rep,name=expired_backup_ids,json=expiredBackupIds,proto3" json:"expired_backup_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpireBackupsResponse) Reset() {
	*x = ExpireBackupsResponse{}
	mi := &file_multiadminservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireBackupsResponse) ProtoMessage() {}

func (x *ExpireBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireBackupsResponse.ProtoReflect.Descriptor instead.
func (*ExpireBackupsResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{23}
}

func (x *ExpireBackupsResponse) GetExpiredBackupIds() []string {
	if x != nil {
		return x.ExpiredBackupIds
	}
	return nil
}

// BackupInfo contains information about a single backup artifact
type BackupInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// backup_id uniquely identifies this backup (e.g., "20250117-123456F")
	BackupId string `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	// database name
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// table_group name
	TableGroup string `protobuf:"bytes,3,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard name
	Shard string `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	// type of backup: "full", "differential", or "incremental"
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// status of the backup
	Status BackupStatus `protobuf:"varint,6,opt,name=status,proto3,enum=multiadmin.BackupStatus" json:"status,omitempty"`
	// backup_time is when the backup was created
	BackupTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=backup_time,json=backupTime,proto3" json:"backup_time,omitempty"`
	// backup_size_bytes is the size of the backup in bytes
	BackupSizeBytes uint64 `protobuf:"varint,8,opt,name=backup_size_bytes,json=backupSizeBytes,proto3" json:"backup_size_bytes,omitempty"`
	// multipooler_service_id is the ID of the multipooler that reported the backup
	MultipoolerServiceId string `protobuf:"bytes,9,opt,name=multipooler_service_id,json=multipoolerServiceId,proto3" json:"multipooler_service_id,omitempty"`
	// pooler_type is the type of the multipooler (PRIMARY or REPLICA)
	PoolerType    clustermetadata.PoolerType `protobuf:"varint,10,opt,name=pooler_type,json=poolerType,proto3,enum=clustermetadata.PoolerType" json:"pooler_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_multiadminservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupInfo.ProtoReflect.Descriptor instead.
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{24}
}

func (x *BackupInfo) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

func (x *BackupInfo) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BackupInfo) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *BackupInfo) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *BackupInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BackupInfo) GetStatus() BackupStatus {
	if x != nil {
		return x.Status
	}
	return BackupStatus_BACKUP_STATUS_UNKNOWN
}

func (x *BackupInfo) GetBackupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BackupTime
	}
	return nil
}

func (x *BackupInfo) GetBackupSizeBytes() uint64 {
	if x != nil {
		return x.BackupSizeBytes
	}
	return 0
}

func (x *BackupInfo) GetMultipoolerServiceId() string {
	if x != nil {
		return x.MultipoolerServiceId
	}
	return ""
}

func (x *BackupInfo) GetPoolerType() clustermetadata.PoolerType {
	if x != nil {
		return x.PoolerType
	}
	return clustermetadata.PoolerType(0)
}

// GetPoolerStatusRequest requests the status of a specific pooler
type GetPoolerStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pooler_id identifies which pooler to query (required)
	PoolerId      *clustermetadata.ID `protobuf:"bytes,1,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolerStatusRequest) Reset() {
	*x = GetPoolerStatusRequest{}
	mi := &file_multiadminservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolerStatusRequest) ProtoMessage() {}

func (x *GetPoolerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPoolerStatusRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{25}
}

func (x *GetPoolerStatusRequest) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

// GetPoolerStatusResponse contains the pooler's unified status
type GetPoolerStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status contains the pooler's unified status from MultiPoolerManager.Status
	Status *multipoolermanagerdata.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// consensus_status is the pooler's current consensus state, forwarded from StatusResponse.
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,2,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPoolerStatusResponse) Reset() {
	*x = GetPoolerStatusResponse{}
	mi := &file_multiadminservice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolerStatusResponse) ProtoMessage() {}

func (x *GetPoolerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPoolerStatusResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{26}
}

func (x *GetPoolerStatusResponse) GetStatus() *multipoolermanagerdata.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetPoolerStatusResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// SetPostgresRestartsEnabledRequest requests to enable or disable automatic PostgreSQL restarts on a pooler
type SetPostgresRestartsEnabledRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pooler_id identifies which pooler to update (required)
	PoolerId *clustermetadata.ID `protobuf:"bytes,1,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// enabled controls whether automatic restarts are enabled (true) or suppressed (false)
	Enabled       bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPostgresRestartsEnabledRequest) Reset() {
	*x = SetPostgresRestartsEnabledRequest{}
	mi := &file_multiadminservice_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPostgresRestartsEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPostgresRestartsEnabledRequest) ProtoMessage() {}

func (x *SetPostgresRestartsEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPostgresRestartsEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetPostgresRestartsEnabledRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{27}
}

func (x *SetPostgresRestartsEnabledRequest) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *SetPostgresRestartsEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SetPostgresRestartsEnabledResponse confirms that the flag was updated
// Errors are returned via gRPC status codes, not in the response body
type SetPostgresRestartsEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPostgresRestartsEnabledResponse) Reset() {
	*x = SetPostgresRestartsEnabledResponse{}
	mi := &file_multiadminservice_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPostgresRestartsEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPostgresRestartsEnabledResponse) ProtoMessage() {}

func (x *SetPostgresRestartsEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPostgresRestartsEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetPostgresRestartsEnabledResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{28}
}

// GetGatewayQueriesRequest specifies which gateway to query and how to bound
// the response.
type GetGatewayQueriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway_id identifies which gateway to query (required)
	GatewayId *clustermetadata.ID `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// limit caps the number of fingerprints returned, sorted by call count
	// descending. 0 means no limit.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// min_calls drops fingerprints whose total call count is below this
	// threshold. 0 means no threshold.
	MinCalls      uint64 `protobuf:"varint,3,opt,name=min_calls,json=minCalls,proto3" json:"min_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayQueriesRequest) Reset() {
	*x = GetGatewayQueriesRequest{}
	mi := &file_multiadminservice_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayQueriesRequest) ProtoMessage() {}

func (x *GetGatewayQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayQueriesRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayQueriesRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{29}
}

func (x *GetGatewayQueriesRequest) GetGatewayId() *clustermetadata.ID {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *GetGatewayQueriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetGatewayQueriesRequest) GetMinCalls() uint64 {
	if x != nil {
		return x.MinCalls
	}
	return 0
}

// GetGatewayQueriesResponse contains the gateway's per-fingerprint query registry snapshot.
type GetGatewayQueriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// snapshot contains the registry data from MultiGatewayManager.GetQueryRegistry
	Snapshot      *multigatewaymanagerdata.QueryRegistrySnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayQueriesResponse) Reset() {
	*x = GetGatewayQueriesResponse{}
	mi := &file_multiadminservice_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayQueriesResponse) ProtoMessage() {}

func (x *GetGatewayQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayQueriesResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayQueriesResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{30}
}

func (x *GetGatewayQueriesResponse) GetSnapshot() *multigatewaymanagerdata.QueryRegistrySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// GetGatewayConsolidatorRequest specifies which gateway to query.
type GetGatewayConsolidatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway_id identifies which gateway to query (required)
	GatewayId     *clustermetadata.ID `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayConsolidatorRequest) Reset() {
	*x = GetGatewayConsolidatorRequest{}
	mi := &file_multiadminservice_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConsolidatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConsolidatorRequest) ProtoMessage() {}

func (x *GetGatewayConsolidatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConsolidatorRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayConsolidatorRequest) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{31}
}

func (x *GetGatewayConsolidatorRequest) GetGatewayId() *clustermetadata.ID {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

// GetGatewayConsolidatorResponse contains the gateway's consolidator snapshot.
type GetGatewayConsolidatorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stats contains the consolidator data from MultiGatewayManager.GetConsolidatorStats
	Stats         *multigatewaymanagerdata.ConsolidatorStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayConsolidatorResponse) Reset() {
	*x = GetGatewayConsolidatorResponse{}
	mi := &file_multiadminservice_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayConsolidatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConsolidatorResponse) ProtoMessage() {}

func (x *GetGatewayConsolidatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multiadminservice_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConsolidatorResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayConsolidatorResponse) Descriptor() ([]byte, []int) {
	return file_multiadminservice_proto_rawDescGZIP(), []int{32}
}

func (x *GetGatewayConsolidatorResponse) GetStats() *multigatewaymanagerdata.ConsolidatorStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_multiadminservice_proto protoreflect.FileDescriptor

const file_multiadminservice_proto_rawDesc = "" +
	"\n" +
	"\x17multiadminservice.proto\x12\n" +
	"multiadmin\x1a\x15clustermetadata.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dmultigatewaymanagerdata.proto\x1a\x1cmultipoolermanagerdata.proto\"$\n" +
	"\x0eGetCellRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x0fGetCellResponse\x12)\n" +
	"\x04cell\x18\x01 \x01(\v2\x15.clustermetadata.CellR\x04cell\"(\n" +
	"\x12GetDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x13GetDatabaseResponse\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.clustermetadata.DatabaseR\bdatabase\"\x15\n" +
	"\x13GetCellNamesRequest\",\n" +
	"\x14GetCellNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\x19\n" +
	"\x17GetDatabaseNamesRequest\"0\n" +
	"\x18GetDatabaseNamesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"*\n" +
	"\x12GetGatewaysRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"P\n" +
	"\x13GetGatewaysResponse\x129\n" +
	"\bgateways\x18\x01 \x03(\v2\x1d.clustermetadata.MultiGatewayR\bgateways\"[\n" +
	"\x11GetPoolersRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\"L\n" +
	"\x12GetPoolersResponse\x126\n" +
	"\apoolers\x18\x01 \x03(\v2\x1c.clustermetadata.MultiPoolerR\apoolers\"'\n" +
	"\x0fGetOrchsRequest\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"D\n" +
	"\x10GetOrchsResponse\x120\n" +
	"\x05orchs\x18\x01 \x03(\v2\x1a.clustermetadata.MultiOrchR\x05orchs\"\x9b\x01\n" +
	"\rBackupRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12#\n" +
	"\rforce_primary\x18\x05 \x01(\bR\fforcePrimary\"'\n" +
	"\x0eBackupResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xbc\x01\n" +
	"\x18RestoreFromBackupRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x1b\n" +
	"\tbackup_id\x18\x04 \x01(\tR\bbackupId\x120\n" +
	"\tpooler_id\x18\x05 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\"2\n" +
	"\x19RestoreFromBackupResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x85\x01\n" +
	"\x19GetBackupJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x03 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\tR\x05shard\"\xf8\x02\n" +
	"\x1aGetBackupJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12.\n" +
	"\bjob_type\x18\x02 \x01(\x0e2\x13.multiadmin.JobTypeR\ajobType\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.multiadmin.JobStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x06 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\a \x01(\tR\x05shard\x12\x1f\n" +
	"\vbackup_type\x18\b \x01(\tR\n" +
	"backupType\x12.\n" +
	"\x13requested_backup_id\x18\n" +
	" \x01(\tR\x11requestedBackupId\x12\x1b\n" +
	"\tbackup_id\x18\v \x01(\tR\bbackupId\"|\n" +
	"\x11GetBackupsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"F\n" +
	"\x12GetBackupsResponse\x120\n" +
	"\abackups\x18\x01 \x03(\v2\x16.multiadmin.BackupInfoR\abackups\"\xf6\x01\n" +
	"\x14ExpireBackupsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x02 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x03 \x01(\tR\x05shard\x12M\n" +
	"\toverrides\x18\x04 \x03(\v2/.multiadmin.ExpireBackupsRequest.OverridesEntryR\toverrides\x1a<\n" +
	"\x0eOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x15ExpireBackupsResponse\x12,\n" +
	"\x12expired_backup_ids\x18\x01 \x03(\tR\x10expiredBackupIds\"\x9f\x03\n" +
	"\n" +
	"BackupInfo\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x03 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\tR\x05shard\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.multiadmin.BackupStatusR\x06status\x12;\n" +
	"\vbackup_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"backupTime\x12*\n" +
	"\x11backup_size_bytes\x18\b \x01(\x04R\x0fbackupSizeBytes\x124\n" +
	"\x16multipooler_service_id\x18\t \x01(\tR\x14multipoolerServiceId\x12<\n" +
	"\vpooler_type\x18\n" +
	" \x01(\x0e2\x1b.clustermetadata.PoolerTypeR\n" +
	"poolerType\"J\n" +
	"\x16GetPoolerStatusRequest\x120\n" +
	"\tpooler_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\"\x9e\x01\n" +
	"\x17GetPoolerStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.multipoolermanagerdata.StatusR\x06status\x12K\n" +
	"\x10consensus_status\x18\x02 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\"o\n" +
	"!SetPostgresRestartsEnabledRequest\x120\n" +
	"\tpooler_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"$\n" +
	"\"SetPostgresRestartsEnabledResponse\"\x81\x01\n" +
	"\x18GetGatewayQueriesRequest\x122\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\tgatewayId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1b\n" +
	"\tmin_calls\x18\x03 \x01(\x04R\bminCalls\"g\n" +
	"\x19GetGatewayQueriesResponse\x12J\n" +
	"\bsnapshot\x18\x01 \x01(\v2..multigatewaymanagerdata.QueryRegistrySnapshotR\bsnapshot\"S\n" +
	"\x1dGetGatewayConsolidatorRequest\x122\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\tgatewayId\"b\n" +
	"\x1eGetGatewayConsolidatorResponse\x12@\n" +
	"\x05stats\x18\x01 \x01(\v2*.multigatewaymanagerdata.ConsolidatorStatsR\x05stats*J\n" +
	"\aJobType\x12\x14\n" +
	"\x10JOB_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fJOB_TYPE_BACKUP\x10\x01\x12\x14\n" +
	"\x10JOB_TYPE_RESTORE\x10\x02*\x84\x01\n" +
	"\tJobStatus\x12\x16\n" +
	"\x12JOB_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04*}\n" +
	"\fBackupStatus\x12\x19\n" +
	"\x15BACKUP_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18BACKUP_STATUS_INCOMPLETE\x10\x01\x12\x1a\n" +
	"\x16BACKUP_STATUS_COMPLETE\x10\x02\x12\x18\n" +
	"\x14BACKUP_STATUS_FAILED\x10\x032\x8c\x10\n" +
	"\x11MultiAdminService\x12`\n" +
	"\aGetCell\x12\x1a.multiadmin.GetCellRequest\x1a\x1b.multiadmin.GetCellResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/cells/{name}\x12p\n" +
	"\vGetDatabase\x12\x1e.multiadmin.GetDatabaseRequest\x1a\x1f.multiadmin.GetDatabaseResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/databases/{name}\x12h\n" +
	"\fGetCellNames\x12\x1f.multiadmin.GetCellNamesRequest\x1a .multiadmin.GetCellNamesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/cells\x12x\n" +
	"\x10GetDatabaseNames\x12#.multiadmin.GetDatabaseNamesRequest\x1a$.multiadmin.GetDatabaseNamesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/databases\x12h\n" +
	"\vGetGateways\x12\x1e.multiadmin.GetGatewaysRequest\x1a\x1f.multiadmin.GetGatewaysResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/gateways\x12d\n" +
	"\n" +
	"GetPoolers\x12\x1d.multiadmin.GetPoolersRequest\x1a\x1e.multiadmin.GetPoolersResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/poolers\x12\\\n" +
	"\bGetOrchs\x12\x1b.multiadmin.GetOrchsRequest\x1a\x1c.multiadmin.GetOrchsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/orchs\x12[\n" +
	"\x06Backup\x12\x19.multiadmin.BackupRequest\x1a\x1a.multiadmin.BackupResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/backups\x12}\n" +
	"\x11RestoreFromBackup\x12$.multiadmin.RestoreFromBackupRequest\x1a%.multiadmin.RestoreFromBackupResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/restores\x12\x82\x01\n" +
	"\x12GetBackupJobStatus\x12%.multiadmin.GetBackupJobStatusRequest\x1a&.multiadmin.GetBackupJobStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/jobs/{job_id}\x12d\n" +
	"\n" +
	"GetBackups\x12\x1d.multiadmin.GetBackupsRequest\x1a\x1e.multiadmin.GetBackupsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/backups\x12w\n" +
	"\rExpireBackups\x12 .multiadmin.ExpireBackupsRequest\x1a!.multiadmin.ExpireBackupsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/backups/expire\x12\x9c\x01\n" +
	"\x0fGetPoolerStatus\x12\".multiadmin.GetPoolerStatusRequest\x1a#.multiadmin.GetPoolerStatusResponse\"@\x82\xd3\xe4\x93\x02:\x128/api/v1/poolers/{pooler_id.cell}/{pooler_id.name}/status\x12\xcb\x01\n" +
	"\x1aSetPostgresRestartsEnabled\x12-.multiadmin.SetPostgresRestartsEnabledRequest\x1a..multiadmin.SetPostgresRestartsEnabledResponse\"N\x82\xd3\xe4\x93\x02H:\x01*\"C/api/v1/poolers/{pooler_id.cell}/{pooler_id.name}/postgres-restarts\x12\xa6\x01\n" +
	"\x11GetGatewayQueries\x12$.multiadmin.GetGatewayQueriesRequest\x1a%.multiadmin.GetGatewayQueriesResponse\"D\x82\xd3\xe4\x93\x02>\x12</api/v1/gateways/{gateway_id.cell}/{gateway_id.name}/queries\x12\xba\x01\n" +
	"\x16GetGatewayConsolidator\x12).multiadmin.GetGatewayConsolidatorRequest\x1a*.multiadmin.GetGatewayConsolidatorResponse\"I\x82\xd3\xe4\x93\x02C\x12A/api/v1/gateways/{gateway_id.cell}/{gateway_id.name}/consolidatorB1Z/github.com/multigres/multigres/go/pb/multiadminb\x06proto3"

var (
	file_multiadminservice_proto_rawDescOnce sync.Once
	file_multiadminservice_proto_rawDescData []byte
)

func file_multiadminservice_proto_rawDescGZIP() []byte {
	file_multiadminservice_proto_rawDescOnce.Do(func() {
		file_multiadminservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiadminservice_proto_rawDesc), len(file_multiadminservice_proto_rawDesc)))
	})
	return file_multiadminservice_proto_rawDescData
}

var file_multiadminservice_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_multiadminservice_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_multiadminservice_proto_goTypes = []any{
	(JobType)(0),                                          // 0: multiadmin.JobType
	(JobStatus)(0),                                        // 1: multiadmin.JobStatus
	(BackupStatus)(0),                                     // 2: multiadmin.BackupStatus
	(*GetCellRequest)(nil),                                // 3: multiadmin.GetCellRequest
	(*GetCellResponse)(nil),                               // 4: multiadmin.GetCellResponse
	(*GetDatabaseRequest)(nil),                            // 5: multiadmin.GetDatabaseRequest
	(*GetDatabaseResponse)(nil),                           // 6: multiadmin.GetDatabaseResponse
	(*GetCellNamesRequest)(nil),                           // 7: multiadmin.GetCellNamesRequest
	(*GetCellNamesResponse)(nil),                          // 8: multiadmin.GetCellNamesResponse
	(*GetDatabaseNamesRequest)(nil),                       // 9: multiadmin.GetDatabaseNamesRequest
	(*GetDatabaseNamesResponse)(nil),                      // 10: multiadmin.GetDatabaseNamesResponse
	(*GetGatewaysRequest)(nil),                            // 11: multiadmin.GetGatewaysRequest
	(*GetGatewaysResponse)(nil),                           // 12: multiadmin.GetGatewaysResponse
	(*GetPoolersRequest)(nil),                             // 13: multiadmin.GetPoolersRequest
	(*GetPoolersResponse)(nil),                            // 14: multiadmin.GetPoolersResponse
	(*GetOrchsRequest)(nil),                               // 15: multiadmin.GetOrchsRequest
	(*GetOrchsResponse)(nil),                              // 16: multiadmin.GetOrchsResponse
	(*BackupRequest)(nil),                                 // 17: multiadmin.BackupRequest
	(*BackupResponse)(nil),                                // 18: multiadmin.BackupResponse
	(*RestoreFromBackupRequest)(nil),                      // 19: multiadmin.RestoreFromBackupRequest
	(*RestoreFromBackupResponse)(nil),                     // 20: multiadmin.RestoreFromBackupResponse
	(*GetBackupJobStatusRequest)(nil),                     // 21: multiadmin.GetBackupJobStatusRequest
	(*GetBackupJobStatusResponse)(nil),                    // 22: multiadmin.GetBackupJobStatusResponse
	(*GetBackupsRequest)(nil),                             // 23: multiadmin.GetBackupsRequest
	(*GetBackupsResponse)(nil),                            // 24: multiadmin.GetBackupsResponse
	(*ExpireBackupsRequest)(nil),                          // 25: multiadmin.ExpireBackupsRequest
	(*ExpireBackupsResponse)(nil),                         // 26: multiadmin.ExpireBackupsResponse
	(*BackupInfo)(nil),                                    // 27: multiadmin.BackupInfo
	(*GetPoolerStatusRequest)(nil),                        // 28: multiadmin.GetPoolerStatusRequest
	(*GetPoolerStatusResponse)(nil),                       // 29: multiadmin.GetPoolerStatusResponse
	(*SetPostgresRestartsEnabledRequest)(nil),             // 30: multiadmin.SetPostgresRestartsEnabledRequest
	(*SetPostgresRestartsEnabledResponse)(nil),            // 31: multiadmin.SetPostgresRestartsEnabledResponse
	(*GetGatewayQueriesRequest)(nil),                      // 32: multiadmin.GetGatewayQueriesRequest
	(*GetGatewayQueriesResponse)(nil),                     // 33: multiadmin.GetGatewayQueriesResponse
	(*GetGatewayConsolidatorRequest)(nil),                 // 34: multiadmin.GetGatewayConsolidatorRequest
	(*GetGatewayConsolidatorResponse)(nil),                // 35: multiadmin.GetGatewayConsolidatorResponse
	nil,                                                   // 36: multiadmin.ExpireBackupsRequest.OverridesEntry
	(*clustermetadata.Cell)(nil),                          // 37: clustermetadata.Cell
	(*clustermetadata.Database)(nil),                      // 38: clustermetadata.Database
	(*clustermetadata.MultiGateway)(nil),                  // 39: clustermetadata.MultiGateway
	(*clustermetadata.MultiPooler)(nil),                   // 40: clustermetadata.MultiPooler
	(*clustermetadata.MultiOrch)(nil),                     // 41: clustermetadata.MultiOrch
	(*clustermetadata.ID)(nil),                            // 42: clustermetadata.ID
	(*timestamppb.Timestamp)(nil),                         // 43: google.protobuf.Timestamp
	(clustermetadata.PoolerType)(0),                       // 44: clustermetadata.PoolerType
	(*multipoolermanagerdata.Status)(nil),                 // 45: multipoolermanagerdata.Status
	(*clustermetadata.ConsensusStatus)(nil),               // 46: clustermetadata.ConsensusStatus
	(*multigatewaymanagerdata.QueryRegistrySnapshot)(nil), // 47: multigatewaymanagerdata.QueryRegistrySnapshot
	(*multigatewaymanagerdata.ConsolidatorStats)(nil),     // 48: multigatewaymanagerdata.ConsolidatorStats
}
var file_multiadminservice_proto_depIdxs = []int32{
	37, // 0: multiadmin.GetCellResponse.cell:type_name -> clustermetadata.Cell
	38, // 1: multiadmin.GetDatabaseResponse.database:type_name -> clustermetadata.Database
	39, // 2: multiadmin.GetGatewaysResponse.gateways:type_name -> clustermetadata.MultiGateway
	40, // 3: multiadmin.GetPoolersResponse.poolers:type_name -> clustermetadata.MultiPooler
	41, // 4: multiadmin.GetOrchsResponse.orchs:type_name -> clustermetadata.MultiOrch
	42, // 5: multiadmin.RestoreFromBackupRequest.pooler_id:type_name -> clustermetadata.ID
	0,  // 6: multiadmin.GetBackupJobStatusResponse.job_type:type_name -> multiadmin.JobType
	1,  // 7: multiadmin.GetBackupJobStatusResponse.status:type_name -> multiadmin.JobStatus
	27, // 8: multiadmin.GetBackupsResponse.backups:type_name -> multiadmin.BackupInfo
	36, // 9: multiadmin.ExpireBackupsRequest.overrides:type_name -> multiadmin.ExpireBackupsRequest.OverridesEntry
	2,  // 10: multiadmin.BackupInfo.status:type_name -> multiadmin.BackupStatus
	43, // 11: multiadmin.BackupInfo.backup_time:type_name -> google.protobuf.Timestamp
	44, // 12: multiadmin.BackupInfo.pooler_type:type_name -> clustermetadata.PoolerType
	42, // 13: multiadmin.GetPoolerStatusRequest.pooler_id:type_name -> clustermetadata.ID
	45, // 14: multiadmin.GetPoolerStatusResponse.status:type_name -> multipoolermanagerdata.Status
	46, // 15: multiadmin.GetPoolerStatusResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	42, // 16: multiadmin.SetPostgresRestartsEnabledRequest.pooler_id:type_name -> clustermetadata.ID
	42, // 17: multiadmin.GetGatewayQueriesRequest.gateway_id:type_name -> clustermetadata.ID
	47, // 18: multiadmin.GetGatewayQueriesResponse.snapshot:type_name -> multigatewaymanagerdata.QueryRegistrySnapshot
	42, // 19: multiadmin.GetGatewayConsolidatorRequest.gateway_id:type_name -> clustermetadata.ID
	48, // 20: multiadmin.GetGatewayConsolidatorResponse.stats:type_name -> multigatewaymanagerdata.ConsolidatorStats
	3,  // 21: multiadmin.MultiAdminService.GetCell:input_type -> multiadmin.GetCellRequest
	5,  // 22: multiadmin.MultiAdminService.GetDatabase:input_type -> multiadmin.GetDatabaseRequest
	7,  // 23: multiadmin.MultiAdminService.GetCellNames:input_type -> multiadmin.GetCellNamesRequest
	9,  // 24: multiadmin.MultiAdminService.GetDatabaseNames:input_type -> multiadmin.GetDatabaseNamesRequest
	11, // 25: multiadmin.MultiAdminService.GetGateways:input_type -> multiadmin.GetGatewaysRequest
	13, // 26: multiadmin.MultiAdminService.GetPoolers:input_type -> multiadmin.GetPoolersRequest
	15, // 27: multiadmin.MultiAdminService.GetOrchs:input_type -> multiadmin.GetOrchsRequest
	17, // 28: multiadmin.MultiAdminService.Backup:input_type -> multiadmin.BackupRequest
	19, // 29: multiadmin.MultiAdminService.RestoreFromBackup:input_type -> multiadmin.RestoreFromBackupRequest
	21, // 30: multiadmin.MultiAdminService.GetBackupJobStatus:input_type -> multiadmin.GetBackupJobStatusRequest
	23, // 31: multiadmin.MultiAdminService.GetBackups:input_type -> multiadmin.GetBackupsRequest
	25, // 32: multiadmin.MultiAdminService.ExpireBackups:input_type -> multiadmin.ExpireBackupsRequest
	28, // 33: multiadmin.MultiAdminService.GetPoolerStatus:input_type -> multiadmin.GetPoolerStatusRequest
	30, // 34: multiadmin.MultiAdminService.SetPostgresRestartsEnabled:input_type -> multiadmin.SetPostgresRestartsEnabledRequest
	32, // 35: multiadmin.MultiAdminService.GetGatewayQueries:input_type -> multiadmin.GetGatewayQueriesRequest
	34, // 36: multiadmin.MultiAdminService.GetGatewayConsolidator:input_type -> multiadmin.GetGatewayConsolidatorRequest
	4,  // 37: multiadmin.MultiAdminService.GetCell:output_type -> multiadmin.GetCellResponse
	6,  // 38: multiadmin.MultiAdminService.GetDatabase:output_type -> multiadmin.GetDatabaseResponse
	8,  // 39: multiadmin.MultiAdminService.GetCellNames:output_type -> multiadmin.GetCellNamesResponse
	10, // 40: multiadmin.MultiAdminService.GetDatabaseNames:output_type -> multiadmin.GetDatabaseNamesResponse
	12, // 41: multiadmin.MultiAdminService.GetGateways:output_type -> multiadmin.GetGatewaysResponse
	14, // 42: multiadmin.MultiAdminService.GetPoolers:output_type -> multiadmin.GetPoolersResponse
	16, // 43: multiadmin.MultiAdminService.GetOrchs:output_type -> multiadmin.GetOrchsResponse
	18, // 44: multiadmin.MultiAdminService.Backup:output_type -> multiadmin.BackupResponse
	20, // 45: multiadmin.MultiAdminService.RestoreFromBackup:output_type -> multiadmin.RestoreFromBackupResponse
	22, // 46: multiadmin.MultiAdminService.GetBackupJobStatus:output_type -> multiadmin.GetBackupJobStatusResponse
	24, // 47: multiadmin.MultiAdminService.GetBackups:output_type -> multiadmin.GetBackupsResponse
	26, // 48: multiadmin.MultiAdminService.ExpireBackups:output_type -> multiadmin.ExpireBackupsResponse
	29, // 49: multiadmin.MultiAdminService.GetPoolerStatus:output_type -> multiadmin.GetPoolerStatusResponse
	31, // 50: multiadmin.MultiAdminService.SetPostgresRestartsEnabled:output_type -> multiadmin.SetPostgresRestartsEnabledResponse
	33, // 51: multiadmin.MultiAdminService.GetGatewayQueries:output_type -> multiadmin.GetGatewayQueriesResponse
	35, // 52: multiadmin.MultiAdminService.GetGatewayConsolidator:output_type -> multiadmin.GetGatewayConsolidatorResponse
	37, // [37:53] is the sub-list for method output_type
	21, // [21:37] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_multiadminservice_proto_init() }
func file_multiadminservice_proto_init() {
	if File_multiadminservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiadminservice_proto_rawDesc), len(file_multiadminservice_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiadminservice_proto_goTypes,
		DependencyIndexes: file_multiadminservice_proto_depIdxs,
		EnumInfos:         file_multiadminservice_proto_enumTypes,
		MessageInfos:      file_multiadminservice_proto_msgTypes,
	}.Build()
	File_multiadminservice_proto = out.File
	file_multiadminservice_proto_goTypes = nil
	file_multiadminservice_proto_depIdxs = nil
}
