// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multiadminservice.proto

package multiadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiAdminService_GetCell_FullMethodName                    = "/multiadmin.MultiAdminService/GetCell"
	MultiAdminService_GetDatabase_FullMethodName                = "/multiadmin.MultiAdminService/GetDatabase"
	MultiAdminService_GetCellNames_FullMethodName               = "/multiadmin.MultiAdminService/GetCellNames"
	MultiAdminService_GetDatabaseNames_FullMethodName           = "/multiadmin.MultiAdminService/GetDatabaseNames"
	MultiAdminService_GetGateways_FullMethodName                = "/multiadmin.MultiAdminService/GetGateways"
	MultiAdminService_GetPoolers_FullMethodName                 = "/multiadmin.MultiAdminService/GetPoolers"
	MultiAdminService_GetOrchs_FullMethodName                   = "/multiadmin.MultiAdminService/GetOrchs"
	MultiAdminService_Backup_FullMethodName                     = "/multiadmin.MultiAdminService/Backup"
	MultiAdminService_RestoreFromBackup_FullMethodName          = "/multiadmin.MultiAdminService/RestoreFromBackup"
	MultiAdminService_GetBackupJobStatus_FullMethodName         = "/multiadmin.MultiAdminService/GetBackupJobStatus"
	MultiAdminService_GetBackups_FullMethodName                 = "/multiadmin.MultiAdminService/GetBackups"
	MultiAdminService_ExpireBackups_FullMethodName              = "/multiadmin.MultiAdminService/ExpireBackups"
	MultiAdminService_GetPoolerStatus_FullMethodName            = "/multiadmin.MultiAdminService/GetPoolerStatus"
	MultiAdminService_SetPostgresRestartsEnabled_FullMethodName = "/multiadmin.MultiAdminService/SetPostgresRestartsEnabled"
	MultiAdminService_GetGatewayQueries_FullMethodName          = "/multiadmin.MultiAdminService/GetGatewayQueries"
	MultiAdminService_GetGatewayConsolidator_FullMethodName     = "/multiadmin.MultiAdminService/GetGatewayConsolidator"
)

// MultiAdminServiceClient is the client API for MultiAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceClient interface {
	// GetCell retrieves information about a specific cell
	GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// GetCellNames retrieves all cell names in the cluster
	GetCellNames(ctx context.Context, in *GetCellNamesRequest, opts ...grpc.CallOption) (*GetCellNamesResponse, error)
	// GetDatabaseNames retrieves all database names in the cluster
	GetDatabaseNames(ctx context.Context, in *GetDatabaseNamesRequest, opts ...grpc.CallOption) (*GetDatabaseNamesResponse, error)
	// GetGateways retrieves gateways filtered by cells
	GetGateways(ctx context.Context, in *GetGatewaysRequest, opts ...grpc.CallOption) (*GetGatewaysResponse, error)
	// GetPoolers retrieves poolers filtered by cells and/or database
	GetPoolers(ctx context.Context, in *GetPoolersRequest, opts ...grpc.CallOption) (*GetPoolersResponse, error)
	// GetOrchs retrieves orchestrators filtered by cells
	GetOrchs(ctx context.Context, in *GetOrchsRequest, opts ...grpc.CallOption) (*GetOrchsResponse, error)
	// Backup starts an async backup of a specific shard
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	// RestoreFromBackup starts an async restore of a specific shard from a backup
	RestoreFromBackup(ctx context.Context, in *RestoreFromBackupRequest, opts ...grpc.CallOption) (*RestoreFromBackupResponse, error)
	// GetBackupJobStatus checks the status of a backup or restore job
	GetBackupJobStatus(ctx context.Context, in *GetBackupJobStatusRequest, opts ...grpc.CallOption) (*GetBackupJobStatusResponse, error)
	// GetBackups lists backup artifacts with optional filtering
	GetBackups(ctx context.Context, in *GetBackupsRequest, opts ...grpc.CallOption) (*GetBackupsResponse, error)
	// ExpireBackups removes old backups according to retention policy
	ExpireBackups(ctx context.Context, in *ExpireBackupsRequest, opts ...grpc.CallOption) (*ExpireBackupsResponse, error)
	// GetPoolerStatus retrieves the unified status of a specific pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.Status RPC.
	GetPoolerStatus(ctx context.Context, in *GetPoolerStatusRequest, opts ...grpc.CallOption) (*GetPoolerStatusResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts on a pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.SetPostgresRestartsEnabled RPC.
	SetPostgresRestartsEnabled(ctx context.Context, in *SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*SetPostgresRestartsEnabledResponse, error)
	// GetGatewayQueries retrieves the per-fingerprint query registry of a
	// specific multigateway. This proxies the request to the target gateway's
	// MultiGatewayManager.GetQueryRegistry RPC.
	GetGatewayQueries(ctx context.Context, in *GetGatewayQueriesRequest, opts ...grpc.CallOption) (*GetGatewayQueriesResponse, error)
	// GetGatewayConsolidator retrieves the prepared-statement consolidator
	// snapshot of a specific multigateway. This proxies the request to the
	// target gateway's MultiGatewayManager.GetConsolidatorStats RPC.
	GetGatewayConsolidator(ctx context.Context, in *GetGatewayConsolidatorRequest, opts ...grpc.CallOption) (*GetGatewayConsolidatorResponse, error)
}

type multiAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiAdminServiceClient(cc grpc.ClientConnInterface) MultiAdminServiceClient {
	return &multiAdminServiceClient{cc}
}

func (c *multiAdminServiceClient) GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetCellNames(ctx context.Context, in *GetCellNamesRequest, opts ...grpc.CallOption) (*GetCellNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellNamesResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetCellNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetDatabaseNames(ctx context.Context, in *GetDatabaseNamesRequest, opts ...grpc.CallOption) (*GetDatabaseNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseNamesResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetDatabaseNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetGateways(ctx context.Context, in *GetGatewaysRequest, opts ...grpc.CallOption) (*GetGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewaysResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetPoolers(ctx context.Context, in *GetPoolersRequest, opts ...grpc.CallOption) (*GetPoolersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolersResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetPoolers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetOrchs(ctx context.Context, in *GetOrchsRequest, opts ...grpc.CallOption) (*GetOrchsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrchsResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetOrchs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) RestoreFromBackup(ctx context.Context, in *RestoreFromBackupRequest, opts ...grpc.CallOption) (*RestoreFromBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreFromBackupResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_RestoreFromBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetBackupJobStatus(ctx context.Context, in *GetBackupJobStatusRequest, opts ...grpc.CallOption) (*GetBackupJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackupJobStatusResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetBackupJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetBackups(ctx context.Context, in *GetBackupsRequest, opts ...grpc.CallOption) (*GetBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackupsResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) ExpireBackups(ctx context.Context, in *ExpireBackupsRequest, opts ...grpc.CallOption) (*ExpireBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireBackupsResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_ExpireBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetPoolerStatus(ctx context.Context, in *GetPoolerStatusRequest, opts ...grpc.CallOption) (*GetPoolerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolerStatusResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetPoolerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) SetPostgresRestartsEnabled(ctx context.Context, in *SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*SetPostgresRestartsEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPostgresRestartsEnabledResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_SetPostgresRestartsEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetGatewayQueries(ctx context.Context, in *GetGatewayQueriesRequest, opts ...grpc.CallOption) (*GetGatewayQueriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayQueriesResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetGatewayQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetGatewayConsolidator(ctx context.Context, in *GetGatewayConsolidatorRequest, opts ...grpc.CallOption) (*GetGatewayConsolidatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayConsolidatorResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetGatewayConsolidator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiAdminServiceServer is the server API for MultiAdminService service.
// All implementations must embed UnimplementedMultiAdminServiceServer
// for forward compatibility.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceServer interface {
	// GetCell retrieves information about a specific cell
	GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	// GetCellNames retrieves all cell names in the cluster
	GetCellNames(context.Context, *GetCellNamesRequest) (*GetCellNamesResponse, error)
	// GetDatabaseNames retrieves all database names in the cluster
	GetDatabaseNames(context.Context, *GetDatabaseNamesRequest) (*GetDatabaseNamesResponse, error)
	// GetGateways retrieves gateways filtered by cells
	GetGateways(context.Context, *GetGatewaysRequest) (*GetGatewaysResponse, error)
	// GetPoolers retrieves poolers filtered by cells and/or database
	GetPoolers(context.Context, *GetPoolersRequest) (*GetPoolersResponse, error)
	// GetOrchs retrieves orchestrators filtered by cells
	GetOrchs(context.Context, *GetOrchsRequest) (*GetOrchsResponse, error)
	// Backup starts an async backup of a specific shard
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	// RestoreFromBackup starts an async restore of a specific shard from a backup
	RestoreFromBackup(context.Context, *RestoreFromBackupRequest) (*RestoreFromBackupResponse, error)
	// GetBackupJobStatus checks the status of a backup or restore job
	GetBackupJobStatus(context.Context, *GetBackupJobStatusRequest) (*GetBackupJobStatusResponse, error)
	// GetBackups lists backup artifacts with optional filtering
	GetBackups(context.Context, *GetBackupsRequest) (*GetBackupsResponse, error)
	// ExpireBackups removes old backups according to retention policy
	ExpireBackups(context.Context, *ExpireBackupsRequest) (*ExpireBackupsResponse, error)
	// GetPoolerStatus retrieves the unified status of a specific pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.Status RPC.
	GetPoolerStatus(context.Context, *GetPoolerStatusRequest) (*GetPoolerStatusResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts on a pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.SetPostgresRestartsEnabled RPC.
	SetPostgresRestartsEnabled(context.Context, *SetPostgresRestartsEnabledRequest) (*SetPostgresRestartsEnabledResponse, error)
	// GetGatewayQueries retrieves the per-fingerprint query registry of a
	// specific multigateway. This proxies the request to the target gateway's
	// MultiGatewayManager.GetQueryRegistry RPC.
	GetGatewayQueries(context.Context, *GetGatewayQueriesRequest) (*GetGatewayQueriesResponse, error)
	// GetGatewayConsolidator retrieves the prepared-statement consolidator
	// snapshot of a specific multigateway. This proxies the request to the
	// target gateway's MultiGatewayManager.GetConsolidatorStats RPC.
	GetGatewayConsolidator(context.Context, *GetGatewayConsolidatorRequest) (*GetGatewayConsolidatorResponse, error)
	mustEmbedUnimplementedMultiAdminServiceServer()
}

// UnimplementedMultiAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiAdminServiceServer struct{}

func (UnimplementedMultiAdminServiceServer) GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCell not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabase not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetCellNames(context.Context, *GetCellNamesRequest) (*GetCellNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCellNames not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetDatabaseNames(context.Context, *GetDatabaseNamesRequest) (*GetDatabaseNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabaseNames not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetGateways(context.Context, *GetGatewaysRequest) (*GetGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGateways not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetPoolers(context.Context, *GetPoolersRequest) (*GetPoolersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolers not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetOrchs(context.Context, *GetOrchsRequest) (*GetOrchsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrchs not implemented")
}
func (UnimplementedMultiAdminServiceServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedMultiAdminServiceServer) RestoreFromBackup(context.Context, *RestoreFromBackupRequest) (*RestoreFromBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreFromBackup not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetBackupJobStatus(context.Context, *GetBackupJobStatusRequest) (*GetBackupJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupJobStatus not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetBackups(context.Context, *GetBackupsRequest) (*GetBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackups not implemented")
}
func (UnimplementedMultiAdminServiceServer) ExpireBackups(context.Context, *ExpireBackupsRequest) (*ExpireBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpireBackups not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetPoolerStatus(context.Context, *GetPoolerStatusRequest) (*GetPoolerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolerStatus not implemented")
}
func (UnimplementedMultiAdminServiceServer) SetPostgresRestartsEnabled(context.Context, *SetPostgresRestartsEnabledRequest) (*SetPostgresRestartsEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPostgresRestartsEnabled not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetGatewayQueries(context.Context, *GetGatewayQueriesRequest) (*GetGatewayQueriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayQueries not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetGatewayConsolidator(context.Context, *GetGatewayConsolidatorRequest) (*GetGatewayConsolidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayConsolidator not implemented")
}
func (UnimplementedMultiAdminServiceServer) mustEmbedUnimplementedMultiAdminServiceServer() {}
func (UnimplementedMultiAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeMultiAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiAdminServiceServer will
// result in compilation errors.
type UnsafeMultiAdminServiceServer interface {
	mustEmbedUnimplementedMultiAdminServiceServer()
}

func RegisterMultiAdminServiceServer(s grpc.ServiceRegistrar, srv MultiAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultiAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiAdminService_ServiceDesc, srv)
}

func _MultiAdminService_GetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetCell(ctx, req.(*GetCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetCellNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetCellNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetCellNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetCellNames(ctx, req.(*GetCellNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetDatabaseNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetDatabaseNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetDatabaseNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetDatabaseNames(ctx, req.(*GetDatabaseNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetGateways(ctx, req.(*GetGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetPoolers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetPoolers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetPoolers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetPoolers(ctx, req.(*GetPoolersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetOrchs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrchsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetOrchs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetOrchs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetOrchs(ctx, req.(*GetOrchsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_RestoreFromBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFromBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).RestoreFromBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_RestoreFromBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).RestoreFromBackup(ctx, req.(*RestoreFromBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetBackupJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetBackupJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetBackupJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetBackupJobStatus(ctx, req.(*GetBackupJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetBackups(ctx, req.(*GetBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_ExpireBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).ExpireBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_ExpireBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).ExpireBackups(ctx, req.(*ExpireBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetPoolerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetPoolerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetPoolerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetPoolerStatus(ctx, req.(*GetPoolerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_SetPostgresRestartsEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPostgresRestartsEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).SetPostgresRestartsEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_SetPostgresRestartsEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).SetPostgresRestartsEnabled(ctx, req.(*SetPostgresRestartsEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetGatewayQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayQueriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetGatewayQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetGatewayQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetGatewayQueries(ctx, req.(*GetGatewayQueriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetGatewayConsolidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayConsolidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetGatewayConsolidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetGatewayConsolidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetGatewayConsolidator(ctx, req.(*GetGatewayConsolidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiAdminService_ServiceDesc is the grpc.ServiceDesc for MultiAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiadmin.MultiAdminService",
	HandlerType: (*MultiAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCell",
			Handler:    _MultiAdminService_GetCell_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _MultiAdminService_GetDatabase_Handler,
		},
		{
			MethodName: "GetCellNames",
			Handler:    _MultiAdminService_GetCellNames_Handler,
		},
		{
			MethodName: "GetDatabaseNames",
			Handler:    _MultiAdminService_GetDatabaseNames_Handler,
		},
		{
			MethodName: "GetGateways",
			Handler:    _MultiAdminService_GetGateways_Handler,
		},
		{
			MethodName: "GetPoolers",
			Handler:    _MultiAdminService_GetPoolers_Handler,
		},
		{
			MethodName: "GetOrchs",
			Handler:    _MultiAdminService_GetOrchs_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MultiAdminService_Backup_Handler,
		},
		{
			MethodName: "RestoreFromBackup",
			Handler:    _MultiAdminService_RestoreFromBackup_Handler,
		},
		{
			MethodName: "GetBackupJobStatus",
			Handler:    _MultiAdminService_GetBackupJobStatus_Handler,
		},
		{
			MethodName: "GetBackups",
			Handler:    _MultiAdminService_GetBackups_Handler,
		},
		{
			MethodName: "ExpireBackups",
			Handler:    _MultiAdminService_ExpireBackups_Handler,
		},
		{
			MethodName: "GetPoolerStatus",
			Handler:    _MultiAdminService_GetPoolerStatus_Handler,
		},
		{
			MethodName: "SetPostgresRestartsEnabled",
			Handler:    _MultiAdminService_SetPostgresRestartsEnabled_Handler,
		},
		{
			MethodName: "GetGatewayQueries",
			Handler:    _MultiAdminService_GetGatewayQueries_Handler,
		},
		{
			MethodName: "GetGatewayConsolidator",
			Handler:    _MultiAdminService_GetGatewayConsolidator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiadminservice.proto",
}
