//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: multipoolerservice.proto

package multipoolerservice

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	mtrpc "github.com/multigres/multigres/go/pb/mtrpc"
	query "github.com/multigres/multigres/go/pb/query"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReservationReason indicates why a connection needs to be reserved.
// Values are powers of 2 to allow combining multiple reasons via bitwise OR.
// A connection can be reserved for multiple reasons simultaneously (e.g., transaction + temp table).
// The connection is only released when all reasons are cleared.
type ReservationReason int32

const (
	ReservationReason_RESERVATION_REASON_UNSPECIFIED ReservationReason = 0
	// Connection is reserved for a transaction - execute BEGIN before the query
	ReservationReason_RESERVATION_REASON_TRANSACTION ReservationReason = 1 // 0b001
	// Connection is reserved due to temporary tables - no BEGIN needed
	ReservationReason_RESERVATION_REASON_TEMP_TABLE ReservationReason = 2 // 0b010
	// Connection is reserved for portal/cursor operations
	ReservationReason_RESERVATION_REASON_PORTAL ReservationReason = 4 // 0b0100
	// Connection is reserved for an active COPY operation
	ReservationReason_RESERVATION_REASON_COPY ReservationReason = 8 // 0b1000
	// Connection is reserved for LISTEN/NOTIFY (dedicated PubSubListener connection)
	ReservationReason_RESERVATION_REASON_LISTEN ReservationReason = 16 // 0b10000
)

// Enum value maps for ReservationReason.
var (
	ReservationReason_name = map[int32]string{
		0:  "RESERVATION_REASON_UNSPECIFIED",
		1:  "RESERVATION_REASON_TRANSACTION",
		2:  "RESERVATION_REASON_TEMP_TABLE",
		4:  "RESERVATION_REASON_PORTAL",
		8:  "RESERVATION_REASON_COPY",
		16: "RESERVATION_REASON_LISTEN",
	}
	ReservationReason_value = map[string]int32{
		"RESERVATION_REASON_UNSPECIFIED": 0,
		"RESERVATION_REASON_TRANSACTION": 1,
		"RESERVATION_REASON_TEMP_TABLE":  2,
		"RESERVATION_REASON_PORTAL":      4,
		"RESERVATION_REASON_COPY":        8,
		"RESERVATION_REASON_LISTEN":      16,
	}
)

func (x ReservationReason) Enum() *ReservationReason {
	p := new(ReservationReason)
	*p = x
	return p
}

func (x ReservationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_multipoolerservice_proto_enumTypes[0].Descriptor()
}

func (ReservationReason) Type() protoreflect.EnumType {
	return &file_multipoolerservice_proto_enumTypes[0]
}

func (x ReservationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationReason.Descriptor instead.
func (ReservationReason) EnumDescriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{0}
}

// TransactionConclusion specifies how to conclude a transaction.
type TransactionConclusion int32

const (
	TransactionConclusion_TRANSACTION_CONCLUSION_UNSPECIFIED TransactionConclusion = 0
	// Execute COMMIT to commit the transaction
	TransactionConclusion_TRANSACTION_CONCLUSION_COMMIT TransactionConclusion = 1
	// Execute ROLLBACK to rollback the transaction
	TransactionConclusion_TRANSACTION_CONCLUSION_ROLLBACK TransactionConclusion = 2
)

// Enum value maps for TransactionConclusion.
var (
	TransactionConclusion_name = map[int32]string{
		0: "TRANSACTION_CONCLUSION_UNSPECIFIED",
		1: "TRANSACTION_CONCLUSION_COMMIT",
		2: "TRANSACTION_CONCLUSION_ROLLBACK",
	}
	TransactionConclusion_value = map[string]int32{
		"TRANSACTION_CONCLUSION_UNSPECIFIED": 0,
		"TRANSACTION_CONCLUSION_COMMIT":      1,
		"TRANSACTION_CONCLUSION_ROLLBACK":    2,
	}
)

func (x TransactionConclusion) Enum() *TransactionConclusion {
	p := new(TransactionConclusion)
	*p = x
	return p
}

func (x TransactionConclusion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionConclusion) Descriptor() protoreflect.EnumDescriptor {
	return file_multipoolerservice_proto_enumTypes[1].Descriptor()
}

func (TransactionConclusion) Type() protoreflect.EnumType {
	return &file_multipoolerservice_proto_enumTypes[1]
}

func (x TransactionConclusion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionConclusion.Descriptor instead.
func (TransactionConclusion) EnumDescriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{1}
}

// Phase indicates which phase of the operation this message represents
type CopyBidiExecuteRequest_Phase int32

const (
	CopyBidiExecuteRequest_INITIATE CopyBidiExecuteRequest_Phase = 0 // Initial command
	CopyBidiExecuteRequest_DATA     CopyBidiExecuteRequest_Phase = 1 // Data chunk (for COPY FROM STDIN)
	CopyBidiExecuteRequest_DONE     CopyBidiExecuteRequest_Phase = 2 // Finalize operation (all data sent for COPY FROM, or ready to receive for COPY TO)
	CopyBidiExecuteRequest_FAIL     CopyBidiExecuteRequest_Phase = 3 // Abort operation
)

// Enum value maps for CopyBidiExecuteRequest_Phase.
var (
	CopyBidiExecuteRequest_Phase_name = map[int32]string{
		0: "INITIATE",
		1: "DATA",
		2: "DONE",
		3: "FAIL",
	}
	CopyBidiExecuteRequest_Phase_value = map[string]int32{
		"INITIATE": 0,
		"DATA":     1,
		"DONE":     2,
		"FAIL":     3,
	}
)

func (x CopyBidiExecuteRequest_Phase) Enum() *CopyBidiExecuteRequest_Phase {
	p := new(CopyBidiExecuteRequest_Phase)
	*p = x
	return p
}

func (x CopyBidiExecuteRequest_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyBidiExecuteRequest_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_multipoolerservice_proto_enumTypes[2].Descriptor()
}

func (CopyBidiExecuteRequest_Phase) Type() protoreflect.EnumType {
	return &file_multipoolerservice_proto_enumTypes[2]
}

func (x CopyBidiExecuteRequest_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyBidiExecuteRequest_Phase.Descriptor instead.
func (CopyBidiExecuteRequest_Phase) EnumDescriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{11, 0}
}

// Phase indicates which phase of the response this represents
type CopyBidiExecuteResponse_Phase int32

const (
	CopyBidiExecuteResponse_READY CopyBidiExecuteResponse_Phase = 0 // Command initiated successfully, ready for data streaming
	// For COPY FROM STDIN: PostgreSQL sent CopyInResponse
	// For COPY TO STDOUT: PostgreSQL sent CopyOutResponse
	CopyBidiExecuteResponse_DATA   CopyBidiExecuteResponse_Phase = 1 // Data chunk (for COPY TO STDOUT)
	CopyBidiExecuteResponse_RESULT CopyBidiExecuteResponse_Phase = 2 // Final result (CommandComplete)
	CopyBidiExecuteResponse_ERROR  CopyBidiExecuteResponse_Phase = 3 // Error occurred
)

// Enum value maps for CopyBidiExecuteResponse_Phase.
var (
	CopyBidiExecuteResponse_Phase_name = map[int32]string{
		0: "READY",
		1: "DATA",
		2: "RESULT",
		3: "ERROR",
	}
	CopyBidiExecuteResponse_Phase_value = map[string]int32{
		"READY":  0,
		"DATA":   1,
		"RESULT": 2,
		"ERROR":  3,
	}
)

func (x CopyBidiExecuteResponse_Phase) Enum() *CopyBidiExecuteResponse_Phase {
	p := new(CopyBidiExecuteResponse_Phase)
	*p = x
	return p
}

func (x CopyBidiExecuteResponse_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyBidiExecuteResponse_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_multipoolerservice_proto_enumTypes[3].Descriptor()
}

func (CopyBidiExecuteResponse_Phase) Type() protoreflect.EnumType {
	return &file_multipoolerservice_proto_enumTypes[3]
}

func (x CopyBidiExecuteResponse_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyBidiExecuteResponse_Phase.Descriptor instead.
func (CopyBidiExecuteResponse_Phase) EnumDescriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{12, 0}
}

// ExecuteQueryRequest represents a request to execute a SQL query
type ExecuteQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target  *query.Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MaxRows uint64        `protobuf:"varint,3,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including session state needed for query execution.
	Options       *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ExecuteQueryRequest) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *ExecuteQueryRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *ExecuteQueryRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ExecuteQueryResponse represents the response from executing a SQL query
type ExecuteQueryResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *query.QueryResult     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	ReservedState *query.ReservedState `protobuf:"bytes,5,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteQueryResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

// StreamExecuteRequest represents a request to execute a SQL query with streaming results
type StreamExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query is the SQL query to execute
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller. This is the effective caller ID,
	// set by the application to further identify the caller.
	CallerId *mtrpc.CallerID `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including session state needed for query execution.
	Options *query.ExecuteOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// reservation_options controls connection reservation behavior.
	// When set with non-zero reasons, StreamExecute creates a new reserved connection
	// (or extends the reasons on an existing one if options.reserved_connection_id is set).
	ReservationOptions *query.ReservationOptions `protobuf:"bytes,5,opt,name=reservation_options,json=reservationOptions,proto3" json:"reservation_options,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamExecuteRequest) Reset() {
	*x = StreamExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteRequest) ProtoMessage() {}

func (x *StreamExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecuteRequest.ProtoReflect.Descriptor instead.
func (*StreamExecuteRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{2}
}

func (x *StreamExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *StreamExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *StreamExecuteRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *StreamExecuteRequest) GetReservationOptions() *query.ReservationOptions {
	if x != nil {
		return x.ReservationOptions
	}
	return nil
}

// StreamExecuteResponse represents a single response in the stream of query results
type StreamExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the query result data (rows, fields, etc.) or diagnostics (notices)
	Result *query.QueryResultPayload `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	// Sent in a final message after query execution completes.
	ReservedState *query.ReservedState `protobuf:"bytes,5,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecuteResponse) Reset() {
	*x = StreamExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecuteResponse) ProtoMessage() {}

func (x *StreamExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecuteResponse.ProtoReflect.Descriptor instead.
func (*StreamExecuteResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{3}
}

func (x *StreamExecuteResponse) GetResult() *query.QueryResultPayload {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamExecuteResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

// PortalStreamExecuteRequest represents a request to execute a portal with streaming results
type PortalStreamExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// prepared_statement contains the prepared statement to execute
	PreparedStatement *query.PreparedStatement `protobuf:"bytes,2,opt,name=prepared_statement,json=preparedStatement,proto3" json:"prepared_statement,omitempty"`
	// portal contains the portal with bound parameters
	Portal *query.Portal `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including max rows and reserved connection ID
	Options *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	// portal_options contains portal-specific knobs that don't apply to plain
	// StreamExecute. Kept on PortalStreamExecuteRequest (rather than
	// ExecuteOptions) so the portal-only fields don't leak into every other
	// request type that carries ExecuteOptions.
	PortalOptions *PortalExecuteOptions `protobuf:"bytes,6,opt,name=portal_options,json=portalOptions,proto3" json:"portal_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalStreamExecuteRequest) Reset() {
	*x = PortalStreamExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalStreamExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalStreamExecuteRequest) ProtoMessage() {}

func (x *PortalStreamExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalStreamExecuteRequest.ProtoReflect.Descriptor instead.
func (*PortalStreamExecuteRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{4}
}

func (x *PortalStreamExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetPreparedStatement() *query.PreparedStatement {
	if x != nil {
		return x.PreparedStatement
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetPortal() *query.Portal {
	if x != nil {
		return x.Portal
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PortalStreamExecuteRequest) GetPortalOptions() *PortalExecuteOptions {
	if x != nil {
		return x.PortalOptions
	}
	return nil
}

// PortalExecuteOptions carries knobs that only make sense on the portal
// (extended-protocol) execution path.
type PortalExecuteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// include_describe asks the multipooler to fuse a portal Describe('P')
	// into the same backend round trip as Execute, so the gateway can resolve
	// libpq-style Bind+Describe(P)+Execute+Sync batches without two RPCs.
	// The portal RowDescription rides back on the streaming response Fields
	// of the first chunk; for DML (NoData) the Fields stay nil.
	IncludeDescribe bool `protobuf:"varint,1,opt,name=include_describe,json=includeDescribe,proto3" json:"include_describe,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PortalExecuteOptions) Reset() {
	*x = PortalExecuteOptions{}
	mi := &file_multipoolerservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalExecuteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalExecuteOptions) ProtoMessage() {}

func (x *PortalExecuteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalExecuteOptions.ProtoReflect.Descriptor instead.
func (*PortalExecuteOptions) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{5}
}

func (x *PortalExecuteOptions) GetIncludeDescribe() bool {
	if x != nil {
		return x.IncludeDescribe
	}
	return false
}

// PortalStreamExecuteResponse represents a response in the portal execution stream
type PortalStreamExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the query result data (rows, fields, etc.) or diagnostics
	Result *query.QueryResultPayload `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	// This is returned in the first response and should be used for subsequent queries.
	ReservedState *query.ReservedState `protobuf:"bytes,5,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalStreamExecuteResponse) Reset() {
	*x = PortalStreamExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalStreamExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalStreamExecuteResponse) ProtoMessage() {}

func (x *PortalStreamExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalStreamExecuteResponse.ProtoReflect.Descriptor instead.
func (*PortalStreamExecuteResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{6}
}

func (x *PortalStreamExecuteResponse) GetResult() *query.QueryResultPayload {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PortalStreamExecuteResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

// DescribeRequest represents a request to describe a prepared statement or portal
type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// prepared_statement is the prepared statement to describe (nil if describing a portal)
	PreparedStatement *query.PreparedStatement `protobuf:"bytes,2,opt,name=prepared_statement,json=preparedStatement,proto3" json:"prepared_statement,omitempty"`
	// portal is the portal to describe (nil if describing a prepared statement)
	Portal *query.Portal `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options including reserved connection ID
	Options       *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DescribeRequest) GetPreparedStatement() *query.PreparedStatement {
	if x != nil {
		return x.PreparedStatement
	}
	return nil
}

func (x *DescribeRequest) GetPortal() *query.Portal {
	if x != nil {
		return x.Portal
	}
	return nil
}

func (x *DescribeRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *DescribeRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// DescribeResponse represents the response from describing a statement or portal
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description contains the statement metadata (fields, parameter types, etc.)
	Description   *query.StatementDescription `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeResponse) GetDescription() *query.StatementDescription {
	if x != nil {
		return x.Description
	}
	return nil
}

// GetAuthCredentialsRequest represents a request to get authentication credentials for a user.
type GetAuthCredentialsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database is the database the user is connecting to.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// username is the PostgreSQL username to authenticate.
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCredentialsRequest) Reset() {
	*x = GetAuthCredentialsRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCredentialsRequest) ProtoMessage() {}

func (x *GetAuthCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetAuthCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuthCredentialsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *GetAuthCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// GetAuthCredentialsResponse represents the response containing authentication credentials.
// Returns codes.NotFound if the user does not exist.
type GetAuthCredentialsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scram_hash is the stored SCRAM-SHA-256 password hash from pg_authid.
	// Format: SCRAM-SHA-256$<iterations>:<salt>$<stored_key>:<server_key>
	// Empty if user exists but has no password set.
	ScramHash     string `protobuf:"bytes,1,opt,name=scram_hash,json=scramHash,proto3" json:"scram_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCredentialsResponse) Reset() {
	*x = GetAuthCredentialsResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCredentialsResponse) ProtoMessage() {}

func (x *GetAuthCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{10}
}

func (x *GetAuthCredentialsResponse) GetScramHash() string {
	if x != nil {
		return x.ScramHash
	}
	return ""
}

// CopyBidiExecuteRequest represents a message in the bidirectional execute stream from gateway to pooler.
// Used for commands that require bidirectional streaming (e.g., COPY FROM STDIN, COPY TO STDOUT).
type CopyBidiExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// phase indicates the current phase
	Phase CopyBidiExecuteRequest_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=multipoolerservice.CopyBidiExecuteRequest_Phase" json:"phase,omitempty"`
	// query is the SQL command to execute (only for INITIATE phase)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// target specifies the routing destination (only for INITIATE phase)
	Target *query.Target `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller (only for INITIATE phase)
	CallerId *mtrpc.CallerID `protobuf:"bytes,4,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options contains execution options (only for INITIATE phase)
	Options *query.ExecuteOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	// data contains the data chunk (for DATA and DONE phases in COPY FROM STDIN)
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// error_message contains the error message (for FAIL phase)
	ErrorMessage string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// reservation_options controls connection reservation behavior (only for INITIATE phase).
	// When set with a transaction reason and begin_query, the executor will start a
	// transaction on the new connection before initiating COPY.
	ReservationOptions *query.ReservationOptions `protobuf:"bytes,8,opt,name=reservation_options,json=reservationOptions,proto3" json:"reservation_options,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CopyBidiExecuteRequest) Reset() {
	*x = CopyBidiExecuteRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyBidiExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyBidiExecuteRequest) ProtoMessage() {}

func (x *CopyBidiExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyBidiExecuteRequest.ProtoReflect.Descriptor instead.
func (*CopyBidiExecuteRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{11}
}

func (x *CopyBidiExecuteRequest) GetPhase() CopyBidiExecuteRequest_Phase {
	if x != nil {
		return x.Phase
	}
	return CopyBidiExecuteRequest_INITIATE
}

func (x *CopyBidiExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CopyBidiExecuteRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CopyBidiExecuteRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *CopyBidiExecuteRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CopyBidiExecuteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CopyBidiExecuteRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CopyBidiExecuteRequest) GetReservationOptions() *query.ReservationOptions {
	if x != nil {
		return x.ReservationOptions
	}
	return nil
}

// CopyBidiExecuteResponse represents a message in the bidirectional execute stream from pooler to gateway.
// Used for responses to commands that require bidirectional streaming.
type CopyBidiExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// phase indicates the current phase
	Phase CopyBidiExecuteResponse_Phase `protobuf:"varint,1,opt,name=phase,proto3,enum=multipoolerservice.CopyBidiExecuteResponse_Phase" json:"phase,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	// Used in READY phase (connection info) and RESULT/ERROR phases (remaining reasons).
	ReservedState *query.ReservedState `protobuf:"bytes,10,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	// format indicates the COPY format (for READY phase with COPY commands)
	// 0 = text, 1 = binary
	Format int32 `protobuf:"varint,4,opt,name=format,proto3" json:"format,omitempty"`
	// column_formats contains the format code for each column (for READY phase with COPY commands)
	// Each value is 0 (text) or 1 (binary)
	ColumnFormats []int32 `protobuf:"varint,8,rep,packed,name=column_formats,json=columnFormats,proto3" json:"column_formats,omitempty"`
	// data contains the data chunk (for DATA phase in COPY TO STDOUT)
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// result contains the final query result (for RESULT phase)
	Result *query.QueryResult `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	// error contains the error message (for ERROR phase)
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyBidiExecuteResponse) Reset() {
	*x = CopyBidiExecuteResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyBidiExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyBidiExecuteResponse) ProtoMessage() {}

func (x *CopyBidiExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyBidiExecuteResponse.ProtoReflect.Descriptor instead.
func (*CopyBidiExecuteResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{12}
}

func (x *CopyBidiExecuteResponse) GetPhase() CopyBidiExecuteResponse_Phase {
	if x != nil {
		return x.Phase
	}
	return CopyBidiExecuteResponse_READY
}

func (x *CopyBidiExecuteResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

func (x *CopyBidiExecuteResponse) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *CopyBidiExecuteResponse) GetColumnFormats() []int32 {
	if x != nil {
		return x.ColumnFormats
	}
	return nil
}

func (x *CopyBidiExecuteResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CopyBidiExecuteResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CopyBidiExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ConcludeTransactionRequest represents a request to conclude a transaction on a reserved connection.
// The connection may or may not be released back to the pool depending on whether there are
// other reasons to keep it reserved (e.g., temporary tables).
type ConcludeTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options must include reserved_connection_id to identify the connection
	Options *query.ExecuteOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// conclusion specifies whether to COMMIT or ROLLBACK the transaction
	Conclusion    TransactionConclusion `protobuf:"varint,4,opt,name=conclusion,proto3,enum=multipoolerservice.TransactionConclusion" json:"conclusion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcludeTransactionRequest) Reset() {
	*x = ConcludeTransactionRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcludeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcludeTransactionRequest) ProtoMessage() {}

func (x *ConcludeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcludeTransactionRequest.ProtoReflect.Descriptor instead.
func (*ConcludeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{13}
}

func (x *ConcludeTransactionRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ConcludeTransactionRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *ConcludeTransactionRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConcludeTransactionRequest) GetConclusion() TransactionConclusion {
	if x != nil {
		return x.Conclusion
	}
	return TransactionConclusion_TRANSACTION_CONCLUSION_UNSPECIFIED
}

// ConcludeTransactionResponse represents the response from concluding a transaction.
type ConcludeTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the result of the COMMIT or ROLLBACK command
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	// If reserved_connection_id is zero, the connection was released and ScatterConn should clear its state.
	ReservedState *query.ReservedState `protobuf:"bytes,5,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcludeTransactionResponse) Reset() {
	*x = ConcludeTransactionResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcludeTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcludeTransactionResponse) ProtoMessage() {}

func (x *ConcludeTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcludeTransactionResponse.ProtoReflect.Descriptor instead.
func (*ConcludeTransactionResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{14}
}

func (x *ConcludeTransactionResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConcludeTransactionResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

// DiscardTempTablesRequest represents a request to discard temp tables on a reserved connection.
// The connection may or may not be released back to the pool depending on whether there are
// other reasons to keep it reserved (e.g., active transaction).
type DiscardTempTablesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options must include reserved_connection_id to identify the connection
	Options       *query.ExecuteOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardTempTablesRequest) Reset() {
	*x = DiscardTempTablesRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardTempTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardTempTablesRequest) ProtoMessage() {}

func (x *DiscardTempTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardTempTablesRequest.ProtoReflect.Descriptor instead.
func (*DiscardTempTablesRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{15}
}

func (x *DiscardTempTablesRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DiscardTempTablesRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *DiscardTempTablesRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// DiscardTempTablesResponse represents the response from discarding temp tables.
type DiscardTempTablesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result contains the result of the DISCARD TEMP command
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// reserved_state contains the authoritative reservation state from multipooler.
	// If reserved_connection_id is zero, the connection was released and ScatterConn should clear its state.
	ReservedState *query.ReservedState `protobuf:"bytes,5,opt,name=reserved_state,json=reservedState,proto3" json:"reserved_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardTempTablesResponse) Reset() {
	*x = DiscardTempTablesResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardTempTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardTempTablesResponse) ProtoMessage() {}

func (x *DiscardTempTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardTempTablesResponse.ProtoReflect.Descriptor instead.
func (*DiscardTempTablesResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{16}
}

func (x *DiscardTempTablesResponse) GetResult() *query.QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DiscardTempTablesResponse) GetReservedState() *query.ReservedState {
	if x != nil {
		return x.ReservedState
	}
	return nil
}

// ReleaseReservedConnectionRequest requests forceful release of a reserved connection.
// The multipooler will handle all cleanup internally (rollback, COPY abort, portal release).
// If any cleanup step fails, the connection is tainted and closed so the pool creates a fresh one.
type ReleaseReservedConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target specifies the routing destination (tablegroup, shard, pooler type)
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// caller_id identifies the caller
	CallerId *mtrpc.CallerID `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// options must include reserved_connection_id to identify the connection
	Options       *query.ExecuteOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservedConnectionRequest) Reset() {
	*x = ReleaseReservedConnectionRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservedConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservedConnectionRequest) ProtoMessage() {}

func (x *ReleaseReservedConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservedConnectionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservedConnectionRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{17}
}

func (x *ReleaseReservedConnectionRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReleaseReservedConnectionRequest) GetCallerId() *mtrpc.CallerID {
	if x != nil {
		return x.CallerId
	}
	return nil
}

func (x *ReleaseReservedConnectionRequest) GetOptions() *query.ExecuteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ReleaseReservedConnectionResponse is the response from releasing a reserved connection.
// Intentionally minimal since this is a forceful cleanup operation.
type ReleaseReservedConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservedConnectionResponse) Reset() {
	*x = ReleaseReservedConnectionResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservedConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservedConnectionResponse) ProtoMessage() {}

func (x *ReleaseReservedConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservedConnectionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservedConnectionResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{18}
}

// StreamPoolerHealthRequest initiates a health stream from the multipooler.
// Currently empty; future versions may add fields for client-requested intervals.
type StreamPoolerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPoolerHealthRequest) Reset() {
	*x = StreamPoolerHealthRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPoolerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPoolerHealthRequest) ProtoMessage() {}

func (x *StreamPoolerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPoolerHealthRequest.ProtoReflect.Descriptor instead.
func (*StreamPoolerHealthRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{19}
}

// StreamPoolerHealthResponse contains the current health state of the multipooler.
// Sent immediately on connection, on state changes, and periodically as heartbeats.
type StreamPoolerHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target identifies the tablegroup, shard, and pooler type this pooler serves.
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// pooler_id identifies this multipooler instance.
	PoolerId *clustermetadata.ID `protobuf:"bytes,2,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// serving_status is the current serving state of the pooler.
	ServingStatus clustermetadata.PoolerServingStatus `protobuf:"varint,3,opt,name=serving_status,json=servingStatus,proto3,enum=clustermetadata.PoolerServingStatus" json:"serving_status,omitempty"`
	// leader_observation contains this pooler's view of who the consensus leader is.
	// Used by clients to identify the true leader when multiple poolers exist.
	LeaderObservation *LeaderObservation `protobuf:"bytes,4,opt,name=leader_observation,json=leaderObservation,proto3" json:"leader_observation,omitempty"`
	// recommended_staleness_timeout is the duration clients should use
	// to detect a stale/dead health stream. If no message is received within
	// this duration, clients should mark the pooler as unhealthy.
	RecommendedStalenessTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=recommended_staleness_timeout,json=recommendedStalenessTimeout,proto3" json:"recommended_staleness_timeout,omitempty"`
	// replication_lag_ns is the current replication lag in nanoseconds,
	// measured via heartbeat timestamps. Zero on a leader or when unknown.
	ReplicationLagNs int64 `protobuf:"varint,6,opt,name=replication_lag_ns,json=replicationLagNs,proto3" json:"replication_lag_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamPoolerHealthResponse) Reset() {
	*x = StreamPoolerHealthResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPoolerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPoolerHealthResponse) ProtoMessage() {}

func (x *StreamPoolerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPoolerHealthResponse.ProtoReflect.Descriptor instead.
func (*StreamPoolerHealthResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{20}
}

func (x *StreamPoolerHealthResponse) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetPoolerId() *clustermetadata.ID {
	if x != nil {
		return x.PoolerId
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetServingStatus() clustermetadata.PoolerServingStatus {
	if x != nil {
		return x.ServingStatus
	}
	return clustermetadata.PoolerServingStatus(0)
}

func (x *StreamPoolerHealthResponse) GetLeaderObservation() *LeaderObservation {
	if x != nil {
		return x.LeaderObservation
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetRecommendedStalenessTimeout() *durationpb.Duration {
	if x != nil {
		return x.RecommendedStalenessTimeout
	}
	return nil
}

func (x *StreamPoolerHealthResponse) GetReplicationLagNs() int64 {
	if x != nil {
		return x.ReplicationLagNs
	}
	return 0
}

// LeaderObservation represents a pooler's view of who the consensus leader is.
type LeaderObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leader_id is the ID of the pooler this node believes is the consensus leader.
	// May be this pooler's own ID if it believes itself to be leader.
	LeaderId *clustermetadata.ID `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// leader_term is the consensus term at which this observation was made.
	// The leader never changes within a leader_term. Higher values indicate
	// more recent leader appointments.
	LeaderTerm    int64 `protobuf:"varint,2,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderObservation) Reset() {
	*x = LeaderObservation{}
	mi := &file_multipoolerservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderObservation) ProtoMessage() {}

func (x *LeaderObservation) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderObservation.ProtoReflect.Descriptor instead.
func (*LeaderObservation) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{21}
}

func (x *LeaderObservation) GetLeaderId() *clustermetadata.ID {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *LeaderObservation) GetLeaderTerm() int64 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

// StreamNotificationsRequest subscribes to or unsubscribes from PG notification channels.
type StreamNotificationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target identifies the shard to listen on.
	Target *query.Target `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// channels is the list of channels to subscribe to initially.
	Channels      []string `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsRequest) Reset() {
	*x = StreamNotificationsRequest{}
	mi := &file_multipoolerservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsRequest) ProtoMessage() {}

func (x *StreamNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsRequest.ProtoReflect.Descriptor instead.
func (*StreamNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{22}
}

func (x *StreamNotificationsRequest) GetTarget() *query.Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *StreamNotificationsRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

// StreamNotificationsResponse delivers a notification from the shared listener.
type StreamNotificationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notification contains the PG notification data.
	Notification  *query.PgNotification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsResponse) Reset() {
	*x = StreamNotificationsResponse{}
	mi := &file_multipoolerservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsResponse) ProtoMessage() {}

func (x *StreamNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_multipoolerservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsResponse.ProtoReflect.Descriptor instead.
func (*StreamNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_multipoolerservice_proto_rawDescGZIP(), []int{23}
}

func (x *StreamNotificationsResponse) GetNotification() *query.PgNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_multipoolerservice_proto protoreflect.FileDescriptor

const file_multipoolerservice_proto_rawDesc = "" +
	"\n" +
	"\x18multipoolerservice.proto\x12\x12multipoolerservice\x1a\x15clustermetadata.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\vmtrpc.proto\x1a\vquery.proto\"\xcc\x01\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12\x19\n" +
	"\bmax_rows\x18\x03 \x01(\x04R\amaxRows\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"\x7f\n" +
	"\x14ExecuteQueryResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\x12;\n" +
	"\x0ereserved_state\x18\x05 \x01(\v2\x14.query.ReservedStateR\rreservedState\"\xfe\x01\n" +
	"\x14StreamExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x02 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x03 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x04 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\x12J\n" +
	"\x13reservation_options\x18\x05 \x01(\v2\x19.query.ReservationOptionsR\x12reservationOptions\"\x87\x01\n" +
	"\x15StreamExecuteResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.query.QueryResultPayloadR\x06result\x12;\n" +
	"\x0ereserved_state\x18\x05 \x01(\v2\x14.query.ReservedStateR\rreservedState\"\xe3\x02\n" +
	"\x1aPortalStreamExecuteRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12G\n" +
	"\x12prepared_statement\x18\x02 \x01(\v2\x18.query.PreparedStatementR\x11preparedStatement\x12%\n" +
	"\x06portal\x18\x03 \x01(\v2\r.query.PortalR\x06portal\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\x12O\n" +
	"\x0eportal_options\x18\x06 \x01(\v2(.multipoolerservice.PortalExecuteOptionsR\rportalOptions\"A\n" +
	"\x14PortalExecuteOptions\x12)\n" +
	"\x10include_describe\x18\x01 \x01(\bR\x0fincludeDescribe\"\x8d\x01\n" +
	"\x1bPortalStreamExecuteResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.query.QueryResultPayloadR\x06result\x12;\n" +
	"\x0ereserved_state\x18\x05 \x01(\v2\x14.query.ReservedStateR\rreservedState\"\x87\x02\n" +
	"\x0fDescribeRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12G\n" +
	"\x12prepared_statement\x18\x02 \x01(\v2\x18.query.PreparedStatementR\x11preparedStatement\x12%\n" +
	"\x06portal\x18\x03 \x01(\v2\r.query.PortalR\x06portal\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"Q\n" +
	"\x10DescribeResponse\x12=\n" +
	"\vdescription\x18\x01 \x01(\v2\x1b.query.StatementDescriptionR\vdescription\"S\n" +
	"\x19GetAuthCredentialsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\";\n" +
	"\x1aGetAuthCredentialsResponse\x12\x1d\n" +
	"\n" +
	"scram_hash\x18\x01 \x01(\tR\tscramHash\"\xb6\x03\n" +
	"\x16CopyBidiExecuteRequest\x12F\n" +
	"\x05phase\x18\x01 \x01(\x0e20.multipoolerservice.CopyBidiExecuteRequest.PhaseR\x05phase\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12%\n" +
	"\x06target\x18\x03 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x04 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x05 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12J\n" +
	"\x13reservation_options\x18\b \x01(\v2\x19.query.ReservationOptionsR\x12reservationOptions\"3\n" +
	"\x05Phase\x12\f\n" +
	"\bINITIATE\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\b\n" +
	"\x04FAIL\x10\x03\"\xe9\x02\n" +
	"\x17CopyBidiExecuteResponse\x12G\n" +
	"\x05phase\x18\x01 \x01(\x0e21.multipoolerservice.CopyBidiExecuteResponse.PhaseR\x05phase\x12;\n" +
	"\x0ereserved_state\x18\n" +
	" \x01(\v2\x14.query.ReservedStateR\rreservedState\x12\x16\n" +
	"\x06format\x18\x04 \x01(\x05R\x06format\x12%\n" +
	"\x0ecolumn_formats\x18\b \x03(\x05R\rcolumnFormats\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12*\n" +
	"\x06result\x18\x06 \x01(\v2\x12.query.QueryResultR\x06result\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"3\n" +
	"\x05Phase\x12\t\n" +
	"\x05READY\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\n" +
	"\n" +
	"\x06RESULT\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"\xed\x01\n" +
	"\x1aConcludeTransactionRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x02 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x03 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\x12I\n" +
	"\n" +
	"conclusion\x18\x04 \x01(\x0e2).multipoolerservice.TransactionConclusionR\n" +
	"conclusion\"\x86\x01\n" +
	"\x1bConcludeTransactionResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\x12;\n" +
	"\x0ereserved_state\x18\x05 \x01(\v2\x14.query.ReservedStateR\rreservedState\"\xa0\x01\n" +
	"\x18DiscardTempTablesRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x02 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x03 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"\x84\x01\n" +
	"\x19DiscardTempTablesResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.query.QueryResultR\x06result\x12;\n" +
	"\x0ereserved_state\x18\x05 \x01(\v2\x14.query.ReservedStateR\rreservedState\"\xa8\x01\n" +
	" ReleaseReservedConnectionRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12,\n" +
	"\tcaller_id\x18\x02 \x01(\v2\x0f.mtrpc.CallerIDR\bcallerId\x12/\n" +
	"\aoptions\x18\x03 \x01(\v2\x15.query.ExecuteOptionsR\aoptions\"#\n" +
	"!ReleaseReservedConnectionResponse\"\x1b\n" +
	"\x19StreamPoolerHealthRequest\"\xa5\x03\n" +
	"\x1aStreamPoolerHealthResponse\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x120\n" +
	"\tpooler_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\bpoolerId\x12K\n" +
	"\x0eserving_status\x18\x03 \x01(\x0e2$.clustermetadata.PoolerServingStatusR\rservingStatus\x12T\n" +
	"\x12leader_observation\x18\x04 \x01(\v2%.multipoolerservice.LeaderObservationR\x11leaderObservation\x12]\n" +
	"\x1drecommended_staleness_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x1brecommendedStalenessTimeout\x12,\n" +
	"\x12replication_lag_ns\x18\x06 \x01(\x03R\x10replicationLagNs\"f\n" +
	"\x11LeaderObservation\x120\n" +
	"\tleader_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\bleaderId\x12\x1f\n" +
	"\vleader_term\x18\x02 \x01(\x03R\n" +
	"leaderTerm\"_\n" +
	"\x1aStreamNotificationsRequest\x12%\n" +
	"\x06target\x18\x01 \x01(\v2\r.query.TargetR\x06target\x12\x1a\n" +
	"\bchannels\x18\x02 \x03(\tR\bchannels\"X\n" +
	"\x1bStreamNotificationsResponse\x129\n" +
	"\fnotification\x18\x01 \x01(\v2\x15.query.PgNotificationR\fnotification*\xd9\x01\n" +
	"\x11ReservationReason\x12\"\n" +
	"\x1eRESERVATION_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRESERVATION_REASON_TRANSACTION\x10\x01\x12!\n" +
	"\x1dRESERVATION_REASON_TEMP_TABLE\x10\x02\x12\x1d\n" +
	"\x19RESERVATION_REASON_PORTAL\x10\x04\x12\x1b\n" +
	"\x17RESERVATION_REASON_COPY\x10\b\x12\x1d\n" +
	"\x19RESERVATION_REASON_LISTEN\x10\x10*\x87\x01\n" +
	"\x15TransactionConclusion\x12&\n" +
	"\"TRANSACTION_CONCLUSION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTRANSACTION_CONCLUSION_COMMIT\x10\x01\x12#\n" +
	"\x1fTRANSACTION_CONCLUSION_ROLLBACK\x10\x022\xfb\t\n" +
	"\x12MultiPoolerService\x12a\n" +
	"\fExecuteQuery\x12'.multipoolerservice.ExecuteQueryRequest\x1a(.multipoolerservice.ExecuteQueryResponse\x12f\n" +
	"\rStreamExecute\x12(.multipoolerservice.StreamExecuteRequest\x1a).multipoolerservice.StreamExecuteResponse0\x01\x12x\n" +
	"\x13PortalStreamExecute\x12..multipoolerservice.PortalStreamExecuteRequest\x1a/.multipoolerservice.PortalStreamExecuteResponse0\x01\x12U\n" +
	"\bDescribe\x12#.multipoolerservice.DescribeRequest\x1a$.multipoolerservice.DescribeResponse\x12s\n" +
	"\x12GetAuthCredentials\x12-.multipoolerservice.GetAuthCredentialsRequest\x1a..multipoolerservice.GetAuthCredentialsResponse\x12n\n" +
	"\x0fCopyBidiExecute\x12*.multipoolerservice.CopyBidiExecuteRequest\x1a+.multipoolerservice.CopyBidiExecuteResponse(\x010\x01\x12v\n" +
	"\x13ConcludeTransaction\x12..multipoolerservice.ConcludeTransactionRequest\x1a/.multipoolerservice.ConcludeTransactionResponse\x12p\n" +
	"\x11DiscardTempTables\x12,.multipoolerservice.DiscardTempTablesRequest\x1a-.multipoolerservice.DiscardTempTablesResponse\x12\x88\x01\n" +
	"\x19ReleaseReservedConnection\x124.multipoolerservice.ReleaseReservedConnectionRequest\x1a5.multipoolerservice.ReleaseReservedConnectionResponse\x12u\n" +
	"\x12StreamPoolerHealth\x12-.multipoolerservice.StreamPoolerHealthRequest\x1a..multipoolerservice.StreamPoolerHealthResponse0\x01\x12x\n" +
	"\x13StreamNotifications\x12..multipoolerservice.StreamNotificationsRequest\x1a/.multipoolerservice.StreamNotificationsResponse0\x01B9Z7github.com/multigres/multigres/go/pb/multipoolerserviceb\x06proto3"

var (
	file_multipoolerservice_proto_rawDescOnce sync.Once
	file_multipoolerservice_proto_rawDescData []byte
)

func file_multipoolerservice_proto_rawDescGZIP() []byte {
	file_multipoolerservice_proto_rawDescOnce.Do(func() {
		file_multipoolerservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipoolerservice_proto_rawDesc), len(file_multipoolerservice_proto_rawDesc)))
	})
	return file_multipoolerservice_proto_rawDescData
}

var file_multipoolerservice_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_multipoolerservice_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_multipoolerservice_proto_goTypes = []any{
	(ReservationReason)(0),                    // 0: multipoolerservice.ReservationReason
	(TransactionConclusion)(0),                // 1: multipoolerservice.TransactionConclusion
	(CopyBidiExecuteRequest_Phase)(0),         // 2: multipoolerservice.CopyBidiExecuteRequest.Phase
	(CopyBidiExecuteResponse_Phase)(0),        // 3: multipoolerservice.CopyBidiExecuteResponse.Phase
	(*ExecuteQueryRequest)(nil),               // 4: multipoolerservice.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),              // 5: multipoolerservice.ExecuteQueryResponse
	(*StreamExecuteRequest)(nil),              // 6: multipoolerservice.StreamExecuteRequest
	(*StreamExecuteResponse)(nil),             // 7: multipoolerservice.StreamExecuteResponse
	(*PortalStreamExecuteRequest)(nil),        // 8: multipoolerservice.PortalStreamExecuteRequest
	(*PortalExecuteOptions)(nil),              // 9: multipoolerservice.PortalExecuteOptions
	(*PortalStreamExecuteResponse)(nil),       // 10: multipoolerservice.PortalStreamExecuteResponse
	(*DescribeRequest)(nil),                   // 11: multipoolerservice.DescribeRequest
	(*DescribeResponse)(nil),                  // 12: multipoolerservice.DescribeResponse
	(*GetAuthCredentialsRequest)(nil),         // 13: multipoolerservice.GetAuthCredentialsRequest
	(*GetAuthCredentialsResponse)(nil),        // 14: multipoolerservice.GetAuthCredentialsResponse
	(*CopyBidiExecuteRequest)(nil),            // 15: multipoolerservice.CopyBidiExecuteRequest
	(*CopyBidiExecuteResponse)(nil),           // 16: multipoolerservice.CopyBidiExecuteResponse
	(*ConcludeTransactionRequest)(nil),        // 17: multipoolerservice.ConcludeTransactionRequest
	(*ConcludeTransactionResponse)(nil),       // 18: multipoolerservice.ConcludeTransactionResponse
	(*DiscardTempTablesRequest)(nil),          // 19: multipoolerservice.DiscardTempTablesRequest
	(*DiscardTempTablesResponse)(nil),         // 20: multipoolerservice.DiscardTempTablesResponse
	(*ReleaseReservedConnectionRequest)(nil),  // 21: multipoolerservice.ReleaseReservedConnectionRequest
	(*ReleaseReservedConnectionResponse)(nil), // 22: multipoolerservice.ReleaseReservedConnectionResponse
	(*StreamPoolerHealthRequest)(nil),         // 23: multipoolerservice.StreamPoolerHealthRequest
	(*StreamPoolerHealthResponse)(nil),        // 24: multipoolerservice.StreamPoolerHealthResponse
	(*LeaderObservation)(nil),                 // 25: multipoolerservice.LeaderObservation
	(*StreamNotificationsRequest)(nil),        // 26: multipoolerservice.StreamNotificationsRequest
	(*StreamNotificationsResponse)(nil),       // 27: multipoolerservice.StreamNotificationsResponse
	(*query.Target)(nil),                      // 28: query.Target
	(*mtrpc.CallerID)(nil),                    // 29: mtrpc.CallerID
	(*query.ExecuteOptions)(nil),              // 30: query.ExecuteOptions
	(*query.QueryResult)(nil),                 // 31: query.QueryResult
	(*query.ReservedState)(nil),               // 32: query.ReservedState
	(*query.ReservationOptions)(nil),          // 33: query.ReservationOptions
	(*query.QueryResultPayload)(nil),          // 34: query.QueryResultPayload
	(*query.PreparedStatement)(nil),           // 35: query.PreparedStatement
	(*query.Portal)(nil),                      // 36: query.Portal
	(*query.StatementDescription)(nil),        // 37: query.StatementDescription
	(*clustermetadata.ID)(nil),                // 38: clustermetadata.ID
	(clustermetadata.PoolerServingStatus)(0),  // 39: clustermetadata.PoolerServingStatus
	(*durationpb.Duration)(nil),               // 40: google.protobuf.Duration
	(*query.PgNotification)(nil),              // 41: query.PgNotification
}
var file_multipoolerservice_proto_depIdxs = []int32{
	28, // 0: multipoolerservice.ExecuteQueryRequest.target:type_name -> query.Target
	29, // 1: multipoolerservice.ExecuteQueryRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 2: multipoolerservice.ExecuteQueryRequest.options:type_name -> query.ExecuteOptions
	31, // 3: multipoolerservice.ExecuteQueryResponse.result:type_name -> query.QueryResult
	32, // 4: multipoolerservice.ExecuteQueryResponse.reserved_state:type_name -> query.ReservedState
	28, // 5: multipoolerservice.StreamExecuteRequest.target:type_name -> query.Target
	29, // 6: multipoolerservice.StreamExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 7: multipoolerservice.StreamExecuteRequest.options:type_name -> query.ExecuteOptions
	33, // 8: multipoolerservice.StreamExecuteRequest.reservation_options:type_name -> query.ReservationOptions
	34, // 9: multipoolerservice.StreamExecuteResponse.result:type_name -> query.QueryResultPayload
	32, // 10: multipoolerservice.StreamExecuteResponse.reserved_state:type_name -> query.ReservedState
	28, // 11: multipoolerservice.PortalStreamExecuteRequest.target:type_name -> query.Target
	35, // 12: multipoolerservice.PortalStreamExecuteRequest.prepared_statement:type_name -> query.PreparedStatement
	36, // 13: multipoolerservice.PortalStreamExecuteRequest.portal:type_name -> query.Portal
	29, // 14: multipoolerservice.PortalStreamExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 15: multipoolerservice.PortalStreamExecuteRequest.options:type_name -> query.ExecuteOptions
	9,  // 16: multipoolerservice.PortalStreamExecuteRequest.portal_options:type_name -> multipoolerservice.PortalExecuteOptions
	34, // 17: multipoolerservice.PortalStreamExecuteResponse.result:type_name -> query.QueryResultPayload
	32, // 18: multipoolerservice.PortalStreamExecuteResponse.reserved_state:type_name -> query.ReservedState
	28, // 19: multipoolerservice.DescribeRequest.target:type_name -> query.Target
	35, // 20: multipoolerservice.DescribeRequest.prepared_statement:type_name -> query.PreparedStatement
	36, // 21: multipoolerservice.DescribeRequest.portal:type_name -> query.Portal
	29, // 22: multipoolerservice.DescribeRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 23: multipoolerservice.DescribeRequest.options:type_name -> query.ExecuteOptions
	37, // 24: multipoolerservice.DescribeResponse.description:type_name -> query.StatementDescription
	2,  // 25: multipoolerservice.CopyBidiExecuteRequest.phase:type_name -> multipoolerservice.CopyBidiExecuteRequest.Phase
	28, // 26: multipoolerservice.CopyBidiExecuteRequest.target:type_name -> query.Target
	29, // 27: multipoolerservice.CopyBidiExecuteRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 28: multipoolerservice.CopyBidiExecuteRequest.options:type_name -> query.ExecuteOptions
	33, // 29: multipoolerservice.CopyBidiExecuteRequest.reservation_options:type_name -> query.ReservationOptions
	3,  // 30: multipoolerservice.CopyBidiExecuteResponse.phase:type_name -> multipoolerservice.CopyBidiExecuteResponse.Phase
	32, // 31: multipoolerservice.CopyBidiExecuteResponse.reserved_state:type_name -> query.ReservedState
	31, // 32: multipoolerservice.CopyBidiExecuteResponse.result:type_name -> query.QueryResult
	28, // 33: multipoolerservice.ConcludeTransactionRequest.target:type_name -> query.Target
	29, // 34: multipoolerservice.ConcludeTransactionRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 35: multipoolerservice.ConcludeTransactionRequest.options:type_name -> query.ExecuteOptions
	1,  // 36: multipoolerservice.ConcludeTransactionRequest.conclusion:type_name -> multipoolerservice.TransactionConclusion
	31, // 37: multipoolerservice.ConcludeTransactionResponse.result:type_name -> query.QueryResult
	32, // 38: multipoolerservice.ConcludeTransactionResponse.reserved_state:type_name -> query.ReservedState
	28, // 39: multipoolerservice.DiscardTempTablesRequest.target:type_name -> query.Target
	29, // 40: multipoolerservice.DiscardTempTablesRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 41: multipoolerservice.DiscardTempTablesRequest.options:type_name -> query.ExecuteOptions
	31, // 42: multipoolerservice.DiscardTempTablesResponse.result:type_name -> query.QueryResult
	32, // 43: multipoolerservice.DiscardTempTablesResponse.reserved_state:type_name -> query.ReservedState
	28, // 44: multipoolerservice.ReleaseReservedConnectionRequest.target:type_name -> query.Target
	29, // 45: multipoolerservice.ReleaseReservedConnectionRequest.caller_id:type_name -> mtrpc.CallerID
	30, // 46: multipoolerservice.ReleaseReservedConnectionRequest.options:type_name -> query.ExecuteOptions
	28, // 47: multipoolerservice.StreamPoolerHealthResponse.target:type_name -> query.Target
	38, // 48: multipoolerservice.StreamPoolerHealthResponse.pooler_id:type_name -> clustermetadata.ID
	39, // 49: multipoolerservice.StreamPoolerHealthResponse.serving_status:type_name -> clustermetadata.PoolerServingStatus
	25, // 50: multipoolerservice.StreamPoolerHealthResponse.leader_observation:type_name -> multipoolerservice.LeaderObservation
	40, // 51: multipoolerservice.StreamPoolerHealthResponse.recommended_staleness_timeout:type_name -> google.protobuf.Duration
	38, // 52: multipoolerservice.LeaderObservation.leader_id:type_name -> clustermetadata.ID
	28, // 53: multipoolerservice.StreamNotificationsRequest.target:type_name -> query.Target
	41, // 54: multipoolerservice.StreamNotificationsResponse.notification:type_name -> query.PgNotification
	4,  // 55: multipoolerservice.MultiPoolerService.ExecuteQuery:input_type -> multipoolerservice.ExecuteQueryRequest
	6,  // 56: multipoolerservice.MultiPoolerService.StreamExecute:input_type -> multipoolerservice.StreamExecuteRequest
	8,  // 57: multipoolerservice.MultiPoolerService.PortalStreamExecute:input_type -> multipoolerservice.PortalStreamExecuteRequest
	11, // 58: multipoolerservice.MultiPoolerService.Describe:input_type -> multipoolerservice.DescribeRequest
	13, // 59: multipoolerservice.MultiPoolerService.GetAuthCredentials:input_type -> multipoolerservice.GetAuthCredentialsRequest
	15, // 60: multipoolerservice.MultiPoolerService.CopyBidiExecute:input_type -> multipoolerservice.CopyBidiExecuteRequest
	17, // 61: multipoolerservice.MultiPoolerService.ConcludeTransaction:input_type -> multipoolerservice.ConcludeTransactionRequest
	19, // 62: multipoolerservice.MultiPoolerService.DiscardTempTables:input_type -> multipoolerservice.DiscardTempTablesRequest
	21, // 63: multipoolerservice.MultiPoolerService.ReleaseReservedConnection:input_type -> multipoolerservice.ReleaseReservedConnectionRequest
	23, // 64: multipoolerservice.MultiPoolerService.StreamPoolerHealth:input_type -> multipoolerservice.StreamPoolerHealthRequest
	26, // 65: multipoolerservice.MultiPoolerService.StreamNotifications:input_type -> multipoolerservice.StreamNotificationsRequest
	5,  // 66: multipoolerservice.MultiPoolerService.ExecuteQuery:output_type -> multipoolerservice.ExecuteQueryResponse
	7,  // 67: multipoolerservice.MultiPoolerService.StreamExecute:output_type -> multipoolerservice.StreamExecuteResponse
	10, // 68: multipoolerservice.MultiPoolerService.PortalStreamExecute:output_type -> multipoolerservice.PortalStreamExecuteResponse
	12, // 69: multipoolerservice.MultiPoolerService.Describe:output_type -> multipoolerservice.DescribeResponse
	14, // 70: multipoolerservice.MultiPoolerService.GetAuthCredentials:output_type -> multipoolerservice.GetAuthCredentialsResponse
	16, // 71: multipoolerservice.MultiPoolerService.CopyBidiExecute:output_type -> multipoolerservice.CopyBidiExecuteResponse
	18, // 72: multipoolerservice.MultiPoolerService.ConcludeTransaction:output_type -> multipoolerservice.ConcludeTransactionResponse
	20, // 73: multipoolerservice.MultiPoolerService.DiscardTempTables:output_type -> multipoolerservice.DiscardTempTablesResponse
	22, // 74: multipoolerservice.MultiPoolerService.ReleaseReservedConnection:output_type -> multipoolerservice.ReleaseReservedConnectionResponse
	24, // 75: multipoolerservice.MultiPoolerService.StreamPoolerHealth:output_type -> multipoolerservice.StreamPoolerHealthResponse
	27, // 76: multipoolerservice.MultiPoolerService.StreamNotifications:output_type -> multipoolerservice.StreamNotificationsResponse
	66, // [66:77] is the sub-list for method output_type
	55, // [55:66] is the sub-list for method input_type
	55, // [55:55] is the sub-list for extension type_name
	55, // [55:55] is the sub-list for extension extendee
	0,  // [0:55] is the sub-list for field type_name
}

func init() { file_multipoolerservice_proto_init() }
func file_multipoolerservice_proto_init() {
	if File_multipoolerservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipoolerservice_proto_rawDesc), len(file_multipoolerservice_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipoolerservice_proto_goTypes,
		DependencyIndexes: file_multipoolerservice_proto_depIdxs,
		EnumInfos:         file_multipoolerservice_proto_enumTypes,
		MessageInfos:      file_multipoolerservice_proto_msgTypes,
	}.Build()
	File_multipoolerservice_proto = out.File
	file_multipoolerservice_proto_goTypes = nil
	file_multipoolerservice_proto_depIdxs = nil
}
