// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: clustermetadata.proto

package clustermetadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoolerType represents the type of a given MultiPooler.
type PoolerType int32

const (
	// UNKNOWN is not a valid type.
	// It is useful during upgrades to detect when a value is not initialized
	PoolerType_UNKNOWN PoolerType = 0
	// PRIMARY is the primary server for the shard. Only PRIMARY allows DMLs.
	PoolerType_PRIMARY PoolerType = 1
	// REPLICA replicates from leader. It is used to read only traffic
	PoolerType_REPLICA PoolerType = 2
	// DRAINED is used for poolers that are temporarily removed from serving traffic
	PoolerType_DRAINED PoolerType = 3
)

// Enum value maps for PoolerType.
var (
	PoolerType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PRIMARY",
		2: "REPLICA",
		3: "DRAINED",
	}
	PoolerType_value = map[string]int32{
		"UNKNOWN": 0,
		"PRIMARY": 1,
		"REPLICA": 2,
		"DRAINED": 3,
	}
)

func (x PoolerType) Enum() *PoolerType {
	p := new(PoolerType)
	*p = x
	return p
}

func (x PoolerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolerType) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermetadata_proto_enumTypes[0].Descriptor()
}

func (PoolerType) Type() protoreflect.EnumType {
	return &file_clustermetadata_proto_enumTypes[0]
}

func (x PoolerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolerType.Descriptor instead.
func (PoolerType) EnumDescriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{0}
}

// PoolerServingStatus represents the serving status of the given MultiPooler.
type PoolerServingStatus int32

const (
	// SERVING is the status a server during normal operations when it is serving traffic.
	PoolerServingStatus_SERVING PoolerServingStatus = 0
	// NOT_SERVING is the status of a server when it is not serving traffic.
	// This typically occurs during startup, shutdown, or when the server is
	// in an error state and cannot accept connections.
	PoolerServingStatus_NOT_SERVING PoolerServingStatus = 1
	// BACKUP is the status of a server when it is taking a backup. No queries
	// can be served in BACKUP mode.
	PoolerServingStatus_BACKUP PoolerServingStatus = 2
	// RESTORE is the status a server uses when restoring a backup, at
	// startup time.  No queries can be served in RESTORE mode.
	PoolerServingStatus_RESTORE PoolerServingStatus = 3
)

// Enum value maps for PoolerServingStatus.
var (
	PoolerServingStatus_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
		2: "BACKUP",
		3: "RESTORE",
	}
	PoolerServingStatus_value = map[string]int32{
		"SERVING":     0,
		"NOT_SERVING": 1,
		"BACKUP":      2,
		"RESTORE":     3,
	}
)

func (x PoolerServingStatus) Enum() *PoolerServingStatus {
	p := new(PoolerServingStatus)
	*p = x
	return p
}

func (x PoolerServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolerServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermetadata_proto_enumTypes[1].Descriptor()
}

func (PoolerServingStatus) Type() protoreflect.EnumType {
	return &file_clustermetadata_proto_enumTypes[1]
}

func (x PoolerServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolerServingStatus.Descriptor instead.
func (PoolerServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{1}
}

// QuorumType enumerates supported quorum algorithms
type QuorumType int32

const (
	// QUORUM_TYPE_UNKNOWN represents an unknown or uninitialized quorum type
	QuorumType_QUORUM_TYPE_UNKNOWN QuorumType = 0
	// QUORUM_TYPE_AT_LEAST_N requires at least N nodes from the discovered cohort to acknowledge
	QuorumType_QUORUM_TYPE_AT_LEAST_N QuorumType = 3
	// QUORUM_TYPE_MULTI_CELL_AT_LEAST_N requires nodes from multiple cells (availability zones)
	// with at least one node from each of the required cells
	QuorumType_QUORUM_TYPE_MULTI_CELL_AT_LEAST_N QuorumType = 4
)

// Enum value maps for QuorumType.
var (
	QuorumType_name = map[int32]string{
		0: "QUORUM_TYPE_UNKNOWN",
		3: "QUORUM_TYPE_AT_LEAST_N",
		4: "QUORUM_TYPE_MULTI_CELL_AT_LEAST_N",
	}
	QuorumType_value = map[string]int32{
		"QUORUM_TYPE_UNKNOWN":               0,
		"QUORUM_TYPE_AT_LEAST_N":            3,
		"QUORUM_TYPE_MULTI_CELL_AT_LEAST_N": 4,
	}
)

func (x QuorumType) Enum() *QuorumType {
	p := new(QuorumType)
	*p = x
	return p
}

func (x QuorumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuorumType) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermetadata_proto_enumTypes[2].Descriptor()
}

func (QuorumType) Type() protoreflect.EnumType {
	return &file_clustermetadata_proto_enumTypes[2]
}

func (x QuorumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuorumType.Descriptor instead.
func (QuorumType) EnumDescriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{2}
}

// LeadershipSignal describes a leader's self-reported status for its current term.
// Only published by nodes that are or were the consensus leader (leader_term != 0).
// 0 (UNKNOWN) means the field was not intentionally set.
type LeadershipSignal int32

const (
	LeadershipSignal_LEADERSHIP_SIGNAL_UNKNOWN LeadershipSignal = 0
	// Node is actively and healthily serving as leader for leader_term.
	// Published each poll cycle so the coordinator can distinguish a confirmed
	// healthy leader from one that restarted and hasn't re-published yet.
	LeadershipSignal_LEADERSHIP_SIGNAL_ACTIVE LeadershipSignal = 1
	// Node is requesting demotion from leadership for leader_term. Coordinator
	// should trigger an immediate failover rather than waiting for a heartbeat
	// timeout. The node may continue as a follower after demotion.
	//
	// Staleness check: coordinator verifies leadership_status.leader_term matches
	// the node's known leader_term before acting, to ignore signals left over from
	// a previous failover cycle.
	LeadershipSignal_LEADERSHIP_SIGNAL_REQUESTING_DEMOTION LeadershipSignal = 2
)

// Enum value maps for LeadershipSignal.
var (
	LeadershipSignal_name = map[int32]string{
		0: "LEADERSHIP_SIGNAL_UNKNOWN",
		1: "LEADERSHIP_SIGNAL_ACTIVE",
		2: "LEADERSHIP_SIGNAL_REQUESTING_DEMOTION",
	}
	LeadershipSignal_value = map[string]int32{
		"LEADERSHIP_SIGNAL_UNKNOWN":             0,
		"LEADERSHIP_SIGNAL_ACTIVE":              1,
		"LEADERSHIP_SIGNAL_REQUESTING_DEMOTION": 2,
	}
)

func (x LeadershipSignal) Enum() *LeadershipSignal {
	p := new(LeadershipSignal)
	*p = x
	return p
}

func (x LeadershipSignal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadershipSignal) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermetadata_proto_enumTypes[3].Descriptor()
}

func (LeadershipSignal) Type() protoreflect.EnumType {
	return &file_clustermetadata_proto_enumTypes[3]
}

func (x LeadershipSignal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadershipSignal.Descriptor instead.
func (LeadershipSignal) EnumDescriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{3}
}

// ComponentType represents the type of Multigres component
type ID_ComponentType int32

const (
	// UNKNOWN represents an unknown or uninitialized component type
	ID_UNKNOWN ID_ComponentType = 0
	// MULTIPOOLER represents a multipooler component
	ID_MULTIPOOLER ID_ComponentType = 1
	// MULTIGATEWAY represents a multigateway component
	ID_MULTIGATEWAY ID_ComponentType = 2
	// MULTIORCH represents a multiorch component
	ID_MULTIORCH ID_ComponentType = 3
)

// Enum value maps for ID_ComponentType.
var (
	ID_ComponentType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MULTIPOOLER",
		2: "MULTIGATEWAY",
		3: "MULTIORCH",
	}
	ID_ComponentType_value = map[string]int32{
		"UNKNOWN":      0,
		"MULTIPOOLER":  1,
		"MULTIGATEWAY": 2,
		"MULTIORCH":    3,
	}
)

func (x ID_ComponentType) Enum() *ID_ComponentType {
	p := new(ID_ComponentType)
	*p = x
	return p
}

func (x ID_ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID_ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_clustermetadata_proto_enumTypes[4].Descriptor()
}

func (ID_ComponentType) Type() protoreflect.EnumType {
	return &file_clustermetadata_proto_enumTypes[4]
}

func (x ID_ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID_ComponentType.Descriptor instead.
func (ID_ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{10, 0}
}

// TopoConfig defines the connection parameters for a topology service.
// It specifies the type of topology backend, where it's hosted, and the
// logical root path within that backend.
// This is not stored in the topo itself, but it's the entry point to
// configure the global topo.
type GlobalTopoConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// implementation indicates the type of topology service in use
	// (for example: "etcd",  "memory").
	Implementation string `protobuf:"bytes,1,opt,name=implementation,proto3" json:"implementation,omitempty"`
	// server is the network address (host:port) of the topology service.
	// Can be a list list for HA setups.
	ServerAddresses []string `protobuf:"bytes,2,rep,name=server_addresses,json=serverAddresses,proto3" json:"server_addresses,omitempty"`
	// root is the logical root directory or namespace inside the topology backend
	// under which all cluster metadata will be stored.
	Root          string `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalTopoConfig) Reset() {
	*x = GlobalTopoConfig{}
	mi := &file_clustermetadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalTopoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalTopoConfig) ProtoMessage() {}

func (x *GlobalTopoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalTopoConfig.ProtoReflect.Descriptor instead.
func (*GlobalTopoConfig) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalTopoConfig) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *GlobalTopoConfig) GetServerAddresses() []string {
	if x != nil {
		return x.ServerAddresses
	}
	return nil
}

func (x *GlobalTopoConfig) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

// Cell describes how to connect to a cell topology.
// These records are stored in the global topology server.
type Cell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name for this cell
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// server_address is the network address of the cell topology service.
	ServerAddresses []string `protobuf:"bytes,2,rep,name=server_addresses,json=serverAddresses,proto3" json:"server_addresses,omitempty"`
	// root is the namespace or directory path within the topology service
	// where this cell's metadata is stored. Used only when connecting to server_addresses.
	Root          string `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_clustermetadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cell) GetServerAddresses() []string {
	if x != nil {
		return x.ServerAddresses
	}
	return nil
}

func (x *Cell) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type Database struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the database
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Backup location configuration
	BackupLocation *BackupLocation `protobuf:"bytes,2,opt,name=backup_location,json=backupLocation,proto3" json:"backup_location,omitempty"`
	// List of cell identifiers where this database should be deployed
	Cells []string `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	// bootstrap_durability_policy is the durability policy applied when
	// initializing this database for the first time. Set at database creation.
	BootstrapDurabilityPolicy *DurabilityPolicy `protobuf:"bytes,4,opt,name=bootstrap_durability_policy,json=bootstrapDurabilityPolicy,proto3" json:"bootstrap_durability_policy,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_clustermetadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{2}
}

func (x *Database) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Database) GetBackupLocation() *BackupLocation {
	if x != nil {
		return x.BackupLocation
	}
	return nil
}

func (x *Database) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *Database) GetBootstrapDurabilityPolicy() *DurabilityPolicy {
	if x != nil {
		return x.BootstrapDurabilityPolicy
	}
	return nil
}

// ShardInitClaim records which coordinator claimed the right to initialize a shard
// and the cohort it intends to use. Stored as a create-if-not-exists node in the
// global topology so that only one coordinator can initialize a given shard.
type ShardInitClaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coordinator that claimed this shard initialization.
	ClaimerId *ID `protobuf:"bytes,1,opt,name=claimer_id,json=claimerId,proto3" json:"claimer_id,omitempty"`
	// The cohort of poolers the claimer will use for initial leader appointment.
	// Persisted so that a crash-retry uses the same cohort for idempotency.
	CohortMembers []*ID `protobuf:"bytes,2,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInitClaim) Reset() {
	*x = ShardInitClaim{}
	mi := &file_clustermetadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInitClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInitClaim) ProtoMessage() {}

func (x *ShardInitClaim) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInitClaim.ProtoReflect.Descriptor instead.
func (*ShardInitClaim) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{3}
}

func (x *ShardInitClaim) GetClaimerId() *ID {
	if x != nil {
		return x.ClaimerId
	}
	return nil
}

func (x *ShardInitClaim) GetCohortMembers() []*ID {
	if x != nil {
		return x.CohortMembers
	}
	return nil
}

// BackupLocation specifies where backups are stored
type BackupLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Location:
	//
	//	*BackupLocation_Filesystem
	//	*BackupLocation_S3
	Location      isBackupLocation_Location `protobuf_oneof:"location"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupLocation) Reset() {
	*x = BackupLocation{}
	mi := &file_clustermetadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupLocation) ProtoMessage() {}

func (x *BackupLocation) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupLocation.ProtoReflect.Descriptor instead.
func (*BackupLocation) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{4}
}

func (x *BackupLocation) GetLocation() isBackupLocation_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *BackupLocation) GetFilesystem() *FilesystemBackup {
	if x != nil {
		if x, ok := x.Location.(*BackupLocation_Filesystem); ok {
			return x.Filesystem
		}
	}
	return nil
}

func (x *BackupLocation) GetS3() *S3Backup {
	if x != nil {
		if x, ok := x.Location.(*BackupLocation_S3); ok {
			return x.S3
		}
	}
	return nil
}

type isBackupLocation_Location interface {
	isBackupLocation_Location()
}

type BackupLocation_Filesystem struct {
	Filesystem *FilesystemBackup `protobuf:"bytes,1,opt,name=filesystem,proto3,oneof"`
}

type BackupLocation_S3 struct {
	S3 *S3Backup `protobuf:"bytes,2,opt,name=s3,proto3,oneof"`
}

func (*BackupLocation_Filesystem) isBackupLocation_Location() {}

func (*BackupLocation_S3) isBackupLocation_Location() {}

// FilesystemBackup stores backups on local filesystem
type FilesystemBackup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to backup directory
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemBackup) Reset() {
	*x = FilesystemBackup{}
	mi := &file_clustermetadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemBackup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemBackup) ProtoMessage() {}

func (x *FilesystemBackup) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemBackup.ProtoReflect.Descriptor instead.
func (*FilesystemBackup) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{5}
}

func (x *FilesystemBackup) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// S3Backup stores backups in AWS S3 or S3-compatible storage
type S3Backup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// S3 bucket name (required)
	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// AWS region (required, e.g., "us-east-1")
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// Optional: S3-compatible endpoint URL (e.g., for s3mock testing)
	// If empty, uses standard AWS S3 endpoint
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Optional: Key prefix within bucket (e.g., "multigres-prod/")
	// Used to organize backups in shared buckets
	KeyPrefix string `protobuf:"bytes,4,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// If true, read AWS credentials from environment variables at runtime
	// (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
	// pgbackrest config will use repo1-s3-key-type=shared with explicit credentials
	//
	// If false, use automatic credential detection via repo1-s3-key-type=auto
	// (IRSA, EC2 metadata, etc.). This will only work when running on AWS.
	UseEnvCredentials bool `protobuf:"varint,5,opt,name=use_env_credentials,json=useEnvCredentials,proto3" json:"use_env_credentials,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *S3Backup) Reset() {
	*x = S3Backup{}
	mi := &file_clustermetadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Backup) ProtoMessage() {}

func (x *S3Backup) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Backup.ProtoReflect.Descriptor instead.
func (*S3Backup) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{6}
}

func (x *S3Backup) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Backup) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3Backup) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Backup) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *S3Backup) GetUseEnvCredentials() bool {
	if x != nil {
		return x.UseEnvCredentials
	}
	return false
}

// MultiPooler represents metadata about a running multipooler component instance in the cluster.
type MultiPooler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the multipooler in the cluster.
	Id *ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Database name.
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// TableGroup name.
	TableGroup string `protobuf:"bytes,3,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// Shard name. If range based sharding is used, it should match
	// key_range.
	Shard string `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	// If range based sharding is used, range for the pooler's shard.
	KeyRange *KeyRange `protobuf:"bytes,5,opt,name=key_range,json=keyRange,proto3" json:"key_range,omitempty"`
	// PoolerType is the kind of pooler: PRIMARY or REPLICA
	Type PoolerType `protobuf:"varint,6,opt,name=type,proto3,enum=clustermetadata.PoolerType" json:"type,omitempty"`
	// PoolerServingStatus is the current type of the pooler.
	ServingStatus PoolerServingStatus `protobuf:"varint,7,opt,name=serving_status,json=servingStatus,proto3,enum=clustermetadata.PoolerServingStatus" json:"serving_status,omitempty"`
	// Fully qualified domain name of the host.
	Hostname string `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Map of named ports. These are ports that the pooler exposes. Initially, this will only be gRPC
	PortMap map[string]int32 `protobuf:"bytes,9,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// PoolerDir is used by pgBackRest to compute the primary's data directory.
	PoolerDir string `protobuf:"bytes,10,opt,name=pooler_dir,json=poolerDir,proto3" json:"pooler_dir,omitempty"`
	// PgDataDir is the PostgreSQL data directory path (from the PGDATA environment variable).
	// Used by multiadmin to compute the primary's data directory for pgBackRest.
	PgDataDir     string `protobuf:"bytes,11,opt,name=pg_data_dir,json=pgDataDir,proto3" json:"pg_data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPooler) Reset() {
	*x = MultiPooler{}
	mi := &file_clustermetadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPooler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPooler) ProtoMessage() {}

func (x *MultiPooler) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPooler.ProtoReflect.Descriptor instead.
func (*MultiPooler) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{7}
}

func (x *MultiPooler) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MultiPooler) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *MultiPooler) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *MultiPooler) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *MultiPooler) GetKeyRange() *KeyRange {
	if x != nil {
		return x.KeyRange
	}
	return nil
}

func (x *MultiPooler) GetType() PoolerType {
	if x != nil {
		return x.Type
	}
	return PoolerType_UNKNOWN
}

func (x *MultiPooler) GetServingStatus() PoolerServingStatus {
	if x != nil {
		return x.ServingStatus
	}
	return PoolerServingStatus_SERVING
}

func (x *MultiPooler) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MultiPooler) GetPortMap() map[string]int32 {
	if x != nil {
		return x.PortMap
	}
	return nil
}

func (x *MultiPooler) GetPoolerDir() string {
	if x != nil {
		return x.PoolerDir
	}
	return ""
}

func (x *MultiPooler) GetPgDataDir() string {
	if x != nil {
		return x.PgDataDir
	}
	return ""
}

// MultiGateway represents metadata about a running multigateway component instance in the cluster.
type MultiGateway struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique name of the multi gateway in the cluster.
	Id *ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Fully qualified domain name of the host.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Map of named ports. Normally this should include postgres and grpc.
	PortMap map[string]int32 `protobuf:"bytes,3,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// pid_prefix is the 12-bit prefix encoded into PIDs sent to clients.
	// Used for cross-gateway cancel request routing. Assigned at registration time.
	PidPrefix     uint32 `protobuf:"varint,4,opt,name=pid_prefix,json=pidPrefix,proto3" json:"pid_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiGateway) Reset() {
	*x = MultiGateway{}
	mi := &file_clustermetadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiGateway) ProtoMessage() {}

func (x *MultiGateway) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiGateway.ProtoReflect.Descriptor instead.
func (*MultiGateway) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{8}
}

func (x *MultiGateway) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MultiGateway) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MultiGateway) GetPortMap() map[string]int32 {
	if x != nil {
		return x.PortMap
	}
	return nil
}

func (x *MultiGateway) GetPidPrefix() uint32 {
	if x != nil {
		return x.PidPrefix
	}
	return 0
}

// MultiOrch represents information about a running instance of multiorch.
type MultiOrch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique name of the MultiOrch in the cluster.
	Id *ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Fully qualified domain name of the host.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Map of named ports. These are ports that MultiOrc exposes.
	PortMap       map[string]int32 `protobuf:"bytes,3,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiOrch) Reset() {
	*x = MultiOrch{}
	mi := &file_clustermetadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiOrch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiOrch) ProtoMessage() {}

func (x *MultiOrch) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiOrch.ProtoReflect.Descriptor instead.
func (*MultiOrch) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{9}
}

func (x *MultiOrch) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MultiOrch) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MultiOrch) GetPortMap() map[string]int32 {
	if x != nil {
		return x.PortMap
	}
	return nil
}

// ID is a globally unique pooler identifier.
type ID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// component identifies the type of Multigres component (multipooler, multigateway, or multiorch)
	Component ID_ComponentType `protobuf:"varint,1,opt,name=component,proto3,enum=clustermetadata.ID_ComponentType" json:"component,omitempty"`
	// cell is the Multigres cell where the component is located
	Cell string `protobuf:"bytes,2,opt,name=cell,proto3" json:"cell,omitempty"`
	// name is a unique identifier for the component within the multigres
	// cluster.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_clustermetadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{10}
}

func (x *ID) GetComponent() ID_ComponentType {
	if x != nil {
		return x.Component
	}
	return ID_UNKNOWN
}

func (x *ID) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *ID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// KeyRange represents a range of keys for sharding
type KeyRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start is the start key of the range (inclusive)
	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// end is the end key of the range (exclusive)
	End           []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRange) Reset() {
	*x = KeyRange{}
	mi := &file_clustermetadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRange) ProtoMessage() {}

func (x *KeyRange) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRange.ProtoReflect.Descriptor instead.
func (*KeyRange) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{11}
}

func (x *KeyRange) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *KeyRange) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

// DurabilityPolicy defines consensus quorum rules for a shard.
// These policies are stored locally in each shard's postgres database
// and replicated via postgres streaming replication.
type DurabilityPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// policy_name is a human-readable identifier (e.g., "AT_LEAST_2")
	PolicyName string `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	// policy_version allows policy evolution over time
	PolicyVersion int64 `protobuf:"varint,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// quorum_type determines which quorum algorithm to use
	QuorumType QuorumType `protobuf:"varint,3,opt,name=quorum_type,json=quorumType,proto3,enum=clustermetadata.QuorumType" json:"quorum_type,omitempty"`
	// required_count is the number of nodes/cells required for quorum
	//   - For QUORUM_TYPE_AT_LEAST_N: number of nodes required from discovered cohort
	//   - For QUORUM_TYPE_MULTI_CELL_AT_LEAST_N: number of distinct cells required,
	//     with at least one node from each cell
	RequiredCount int32 `protobuf:"varint,4,opt,name=required_count,json=requiredCount,proto3" json:"required_count,omitempty"`
	// description is a human-readable summary of this policy
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurabilityPolicy) Reset() {
	*x = DurabilityPolicy{}
	mi := &file_clustermetadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurabilityPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurabilityPolicy) ProtoMessage() {}

func (x *DurabilityPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurabilityPolicy.ProtoReflect.Descriptor instead.
func (*DurabilityPolicy) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{12}
}

func (x *DurabilityPolicy) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *DurabilityPolicy) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *DurabilityPolicy) GetQuorumType() QuorumType {
	if x != nil {
		return x.QuorumType
	}
	return QuorumType_QUORUM_TYPE_UNKNOWN
}

func (x *DurabilityPolicy) GetRequiredCount() int32 {
	if x != nil {
		return x.RequiredCount
	}
	return 0
}

func (x *DurabilityPolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// RuleNumber uniquely identifies a shard rule — the outcome of a coordinator
// writing a cluster state change to rule_history. Every change (promotion,
// cohort membership, durability policy) produces a new RuleNumber.
//
// Compared lexicographically: higher coordinator_term takes precedence; within
// the same coordinator_term, higher leader_subterm takes precedence. leader_subterm
// resets to 0 when coordinator_term increases, so subterms alone are not
// globally unique.
type RuleNumber struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorTerm int64                  `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	LeaderSubterm   int64                  `protobuf:"varint,2,opt,name=leader_subterm,json=leaderSubterm,proto3" json:"leader_subterm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleNumber) Reset() {
	*x = RuleNumber{}
	mi := &file_clustermetadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleNumber) ProtoMessage() {}

func (x *RuleNumber) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleNumber.ProtoReflect.Descriptor instead.
func (*RuleNumber) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{13}
}

func (x *RuleNumber) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *RuleNumber) GetLeaderSubterm() int64 {
	if x != nil {
		return x.LeaderSubterm
	}
	return 0
}

// ShardRule is the complete, authoritative description of shard state at a
// specific rule number. Leader identity, cohort membership, and durability
// policy are only meaningful together and relative to the rule that established
// them.
type ShardRule struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RuleNumber *RuleNumber            `protobuf:"bytes,1,opt,name=rule_number,json=ruleNumber,proto3" json:"rule_number,omitempty"`
	// The consensus leader for this rule, through which all transactions (including rules) are
	// written to the WAL.
	LeaderId      *ID   `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CohortMembers []*ID `protobuf:"bytes,3,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	// What nodes need to acknowledge a write before it's considered durable.
	DurabilityPolicy *DurabilityPolicy `protobuf:"bytes,4,opt,name=durability_policy,json=durabilityPolicy,proto3" json:"durability_policy,omitempty"`
	// Which coordinator or pooler facilitated applying the rule.
	CoordinatorId *ID `protobuf:"bytes,5,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	// At what time the coordinator or pooler began trying to apply the rule,
	// from the coordinator's perspective.
	CreationTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardRule) Reset() {
	*x = ShardRule{}
	mi := &file_clustermetadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRule) ProtoMessage() {}

func (x *ShardRule) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRule.ProtoReflect.Descriptor instead.
func (*ShardRule) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{14}
}

func (x *ShardRule) GetRuleNumber() *RuleNumber {
	if x != nil {
		return x.RuleNumber
	}
	return nil
}

func (x *ShardRule) GetLeaderId() *ID {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ShardRule) GetCohortMembers() []*ID {
	if x != nil {
		return x.CohortMembers
	}
	return nil
}

func (x *ShardRule) GetDurabilityPolicy() *DurabilityPolicy {
	if x != nil {
		return x.DurabilityPolicy
	}
	return nil
}

func (x *ShardRule) GetCoordinatorId() *ID {
	if x != nil {
		return x.CoordinatorId
	}
	return nil
}

func (x *ShardRule) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

// PoolerPosition describes a pooler's committed position in logical and physical
// time. It captures the highest ShardRule this pooler has replicated (or written,
// for a leader) and the latest WAL position.
//
// Used in Status, BeginTerm, EmergencyDemote, and Promote responses so the
// coordinator can determine which pooler is most advanced when selecting a
// promotion candidate.
//
// Comparison: prefer the pooler with the higher rule (coordinator_term first,
// then leader_subterm). Break ties by LSN.
type PoolerPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The highest shard rule this pooler has committed to local WAL.
	Rule *ShardRule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	// The current real-time WAL head at the time of reading. Note that this is likely
	// beyond the LSN at which the rule was committed. For a primary: pg_current_wal_lsn().
	// For a standby: pg_last_wal_receive_lsn() (or pg_last_wal_replay_lsn() if receive is null).
	Lsn           string `protobuf:"bytes,2,opt,name=lsn,proto3" json:"lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolerPosition) Reset() {
	*x = PoolerPosition{}
	mi := &file_clustermetadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolerPosition) ProtoMessage() {}

func (x *PoolerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolerPosition.ProtoReflect.Descriptor instead.
func (*PoolerPosition) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{15}
}

func (x *PoolerPosition) GetRule() *ShardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PoolerPosition) GetLsn() string {
	if x != nil {
		return x.Lsn
	}
	return ""
}

// HighestKnownRule is the most recent ShardRule this pooler is aware of,
// which could be beyond the end of this pooler's WAL / PoolerPosition.
//
// If a pooler is disconnected from replication due to network partitions
// or stale coordinators, the HighestKnownRule helps them fix GUC and reconnect
// to learn the latest shard state.
//
// If a coordinator is still establishing a new term's first rule, the HighestKnownRule
// may represent a rule that the coordinator is _about_ to write that doesn't exist in
// any WAL entries yet.
//
// HighestKnownRule does not need to be persisted. It's a best-effort attempt to fix GUC
// settings so that nodes can participate in replication. Nodes with out-of-date information
// will be re-informed of the latest HighestKnownRule by any coordinator that notices the
// pooler has incorrect replication settings.
type HighestKnownRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *ShardRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HighestKnownRule) Reset() {
	*x = HighestKnownRule{}
	mi := &file_clustermetadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighestKnownRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighestKnownRule) ProtoMessage() {}

func (x *HighestKnownRule) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighestKnownRule.ProtoReflect.Descriptor instead.
func (*HighestKnownRule) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{16}
}

func (x *HighestKnownRule) GetRule() *ShardRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// TermRevocation records that this pooler has revoked participation in all terms
// strictly below revoked_below_term. Two things are revoked:
//
//  1. Consensus participation: the pooler will refuse BeginTerm or other coordinator
//     requests for any term < revoked_below_term, and for revoked_below_term itself
//     from a different coordinator than accepted_coordinator_id.
//
//  2. Replication participation: a revoked primary must stop accepting writes; a
//     revoked replica must clear primary_conninfo. Replication participation resumes
//     once the pooler's highest known rule reaches or exceeds revoked_below_term
//     (i.e. the rule for that term has replicated through).
//     TODO: It's currently technically possible to begin a term without revoking
//     replication, but we plan to remove that capability and this message is named
//     for what we intend to do rather than what we currently do.
//
// Re-sending an identical recruitment is idempotent. A higher-term recruitment
// supersedes lower ones automatically.
//
// Persisted to local disk before responding; survives process restarts.
type TermRevocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All terms strictly below this value are revoked. The pooler has accepted
	// the coordinator's exclusive right to act at this term.
	RevokedBelowTerm int64 `protobuf:"varint,1,opt,name=revoked_below_term,json=revokedBelowTerm,proto3" json:"revoked_below_term,omitempty"`
	// The coordinator (multiorch instance) that recruited this revocation.
	// Retained for idempotency: the same coordinator at the same term is re-accepted;
	// a different coordinator at the same term is refused.
	AcceptedCoordinatorId *ID `protobuf:"bytes,2,opt,name=accepted_coordinator_id,json=acceptedCoordinatorId,proto3" json:"accepted_coordinator_id,omitempty"`
	// When the coordinator created this term, set by the coordinator before
	// recruiting. All poolers that accept the same recruitment store the same value.
	// TODO: populate once BeginTermRequest carries this timestamp.
	CoordinatorInitiatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=coordinator_initiated_at,json=coordinatorInitiatedAt,proto3" json:"coordinator_initiated_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TermRevocation) Reset() {
	*x = TermRevocation{}
	mi := &file_clustermetadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermRevocation) ProtoMessage() {}

func (x *TermRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermRevocation.ProtoReflect.Descriptor instead.
func (*TermRevocation) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{17}
}

func (x *TermRevocation) GetRevokedBelowTerm() int64 {
	if x != nil {
		return x.RevokedBelowTerm
	}
	return 0
}

func (x *TermRevocation) GetAcceptedCoordinatorId() *ID {
	if x != nil {
		return x.AcceptedCoordinatorId
	}
	return nil
}

func (x *TermRevocation) GetCoordinatorInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CoordinatorInitiatedAt
	}
	return nil
}

// ConsensusStatus is a pooler's complete view of its position in the distributed
// system. It combines three layers with different durability and precision guarantees:
//
//  1. term_revocation (disk-backed, authoritative)
//     Written to local disk before responding; survives process restarts.
//     Records the highest coordinator term accepted and the coordinator's identity.
//
//  2. current_position (postgres-WAL-backed, authoritative)
//     The highest ShardRule committed to local WAL (from rule_history) and the
//     current LSN. Authoritative because postgres WAL is durable and ordered.
//
//  3. highest_known_rule (best-effort, coordinator-provided)
//     The most recent rule the coordinator is about to establish or has recently
//     established. May be ahead of current_position; not persisted and may be
//     stale after restarts.
type ConsensusStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// term_revocation records the highest coordinator term this pooler has revoked for.
	TermRevocation *TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	// current_position is the highest rule this pooler has committed to local WAL
	// and the latest WAL position.
	CurrentPosition *PoolerPosition `protobuf:"bytes,2,opt,name=current_position,json=currentPosition,proto3" json:"current_position,omitempty"`
	// highest_known_rule is the most recent rule this pooler is aware of. May be
	// ahead of current_position when the pooler has forward knowledge of an
	// upcoming rule that has not yet been replicated or written.
	HighestKnownRule *HighestKnownRule `protobuf:"bytes,3,opt,name=highest_known_rule,json=highestKnownRule,proto3" json:"highest_known_rule,omitempty"`
	// id identifies the pooler that produced this status. Makes ConsensusStatus
	// self-describing when passed around without a surrounding envelope.
	Id            *ID `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusStatus) Reset() {
	*x = ConsensusStatus{}
	mi := &file_clustermetadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusStatus) ProtoMessage() {}

func (x *ConsensusStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusStatus.ProtoReflect.Descriptor instead.
func (*ConsensusStatus) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{18}
}

func (x *ConsensusStatus) GetTermRevocation() *TermRevocation {
	if x != nil {
		return x.TermRevocation
	}
	return nil
}

func (x *ConsensusStatus) GetCurrentPosition() *PoolerPosition {
	if x != nil {
		return x.CurrentPosition
	}
	return nil
}

func (x *ConsensusStatus) GetHighestKnownRule() *HighestKnownRule {
	if x != nil {
		return x.HighestKnownRule
	}
	return nil
}

func (x *ConsensusStatus) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

// LeadershipStatus is published only by nodes that are or have been the consensus leader.
// It lets the coordinator distinguish an actively healthy leader, a leader
// requesting demotion, and a node that has never held leadership.
type LeadershipStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The leader_term at which this node was most recently appointed.
	// Non-zero only on nodes that have been appointed as leader.
	LeaderTerm    int64            `protobuf:"varint,1,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	Signal        LeadershipSignal `protobuf:"varint,2,opt,name=signal,proto3,enum=clustermetadata.LeadershipSignal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipStatus) Reset() {
	*x = LeadershipStatus{}
	mi := &file_clustermetadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipStatus) ProtoMessage() {}

func (x *LeadershipStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipStatus.ProtoReflect.Descriptor instead.
func (*LeadershipStatus) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{19}
}

func (x *LeadershipStatus) GetLeaderTerm() int64 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *LeadershipStatus) GetSignal() LeadershipSignal {
	if x != nil {
		return x.Signal
	}
	return LeadershipSignal_LEADERSHIP_SIGNAL_UNKNOWN
}

// AvailabilityStatus carries best-effort operational fitness signals for a pooler.
// Unlike ConsensusStatus (which is authoritative and backed by postgres WAL and
// on-disk state), AvailabilityStatus is in-memory and may be absent after a
// process restart. Coordinators must treat absence as "unknown," not "unfit."
//
// Signals are re-derivable from continuous health polling, so process restarts
// do not create permanent unavailability. See LeadershipSignal for re-derivation
// rules.
//
// Sources: self-reported by the pooler (fast path) or synthesized by the
// coordinator from observed health state.
// TODO: coordinator should synthesize AvailabilityStatus into
// PoolerHealthState.AvailabilityStatus so the analyzer reads from one place
// regardless of source.
type AvailabilityStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leadership_status is only set by poolers that are or have been the consensus leader.
	LeadershipStatus *LeadershipStatus `protobuf:"bytes,1,opt,name=leadership_status,json=leadershipStatus,proto3" json:"leadership_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AvailabilityStatus) Reset() {
	*x = AvailabilityStatus{}
	mi := &file_clustermetadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityStatus) ProtoMessage() {}

func (x *AvailabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clustermetadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityStatus.ProtoReflect.Descriptor instead.
func (*AvailabilityStatus) Descriptor() ([]byte, []int) {
	return file_clustermetadata_proto_rawDescGZIP(), []int{20}
}

func (x *AvailabilityStatus) GetLeadershipStatus() *LeadershipStatus {
	if x != nil {
		return x.LeadershipStatus
	}
	return nil
}

var File_clustermetadata_proto protoreflect.FileDescriptor

const file_clustermetadata_proto_rawDesc = "" +
	"\n" +
	"\x15clustermetadata.proto\x12\x0fclustermetadata\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x10GlobalTopoConfig\x12&\n" +
	"\x0eimplementation\x18\x01 \x01(\tR\x0eimplementation\x12)\n" +
	"\x10server_addresses\x18\x02 \x03(\tR\x0fserverAddresses\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\"Y\n" +
	"\x04Cell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10server_addresses\x18\x02 \x03(\tR\x0fserverAddresses\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\"\xe1\x01\n" +
	"\bDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\x0fbackup_location\x18\x02 \x01(\v2\x1f.clustermetadata.BackupLocationR\x0ebackupLocation\x12\x14\n" +
	"\x05cells\x18\x03 \x03(\tR\x05cells\x12a\n" +
	"\x1bbootstrap_durability_policy\x18\x04 \x01(\v2!.clustermetadata.DurabilityPolicyR\x19bootstrapDurabilityPolicy\"\x80\x01\n" +
	"\x0eShardInitClaim\x122\n" +
	"\n" +
	"claimer_id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\tclaimerId\x12:\n" +
	"\x0ecohort_members\x18\x02 \x03(\v2\x13.clustermetadata.IDR\rcohortMembers\"\x8e\x01\n" +
	"\x0eBackupLocation\x12C\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\v2!.clustermetadata.FilesystemBackupH\x00R\n" +
	"filesystem\x12+\n" +
	"\x02s3\x18\x02 \x01(\v2\x19.clustermetadata.S3BackupH\x00R\x02s3B\n" +
	"\n" +
	"\blocation\"&\n" +
	"\x10FilesystemBackup\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xa5\x01\n" +
	"\bS3Backup\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x04 \x01(\tR\tkeyPrefix\x12.\n" +
	"\x13use_env_credentials\x18\x05 \x01(\bR\x11useEnvCredentials\"\x98\x04\n" +
	"\vMultiPooler\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\x02id\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1f\n" +
	"\vtable_group\x18\x03 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x04 \x01(\tR\x05shard\x126\n" +
	"\tkey_range\x18\x05 \x01(\v2\x19.clustermetadata.KeyRangeR\bkeyRange\x12/\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1b.clustermetadata.PoolerTypeR\x04type\x12K\n" +
	"\x0eserving_status\x18\a \x01(\x0e2$.clustermetadata.PoolerServingStatusR\rservingStatus\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12D\n" +
	"\bport_map\x18\t \x03(\v2).clustermetadata.MultiPooler.PortMapEntryR\aportMap\x12\x1d\n" +
	"\n" +
	"pooler_dir\x18\n" +
	" \x01(\tR\tpoolerDir\x12\x1e\n" +
	"\vpg_data_dir\x18\v \x01(\tR\tpgDataDir\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf1\x01\n" +
	"\fMultiGateway\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12E\n" +
	"\bport_map\x18\x03 \x03(\v2*.clustermetadata.MultiGateway.PortMapEntryR\aportMap\x12\x1d\n" +
	"\n" +
	"pid_prefix\x18\x04 \x01(\rR\tpidPrefix\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xcc\x01\n" +
	"\tMultiOrch\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.clustermetadata.IDR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12B\n" +
	"\bport_map\x18\x03 \x03(\v2'.clustermetadata.MultiOrch.PortMapEntryR\aportMap\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xbd\x01\n" +
	"\x02ID\x12?\n" +
	"\tcomponent\x18\x01 \x01(\x0e2!.clustermetadata.ID.ComponentTypeR\tcomponent\x12\x12\n" +
	"\x04cell\x18\x02 \x01(\tR\x04cell\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"N\n" +
	"\rComponentType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vMULTIPOOLER\x10\x01\x12\x10\n" +
	"\fMULTIGATEWAY\x10\x02\x12\r\n" +
	"\tMULTIORCH\x10\x03\"2\n" +
	"\bKeyRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\"\xe1\x01\n" +
	"\x10DurabilityPolicy\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\x03R\rpolicyVersion\x12<\n" +
	"\vquorum_type\x18\x03 \x01(\x0e2\x1b.clustermetadata.QuorumTypeR\n" +
	"quorumType\x12%\n" +
	"\x0erequired_count\x18\x04 \x01(\x05R\rrequiredCount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"^\n" +
	"\n" +
	"RuleNumber\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12%\n" +
	"\x0eleader_subterm\x18\x02 \x01(\x03R\rleaderSubterm\"\x84\x03\n" +
	"\tShardRule\x12<\n" +
	"\vrule_number\x18\x01 \x01(\v2\x1b.clustermetadata.RuleNumberR\n" +
	"ruleNumber\x120\n" +
	"\tleader_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\bleaderId\x12:\n" +
	"\x0ecohort_members\x18\x03 \x03(\v2\x13.clustermetadata.IDR\rcohortMembers\x12N\n" +
	"\x11durability_policy\x18\x04 \x01(\v2!.clustermetadata.DurabilityPolicyR\x10durabilityPolicy\x12:\n" +
	"\x0ecoordinator_id\x18\x05 \x01(\v2\x13.clustermetadata.IDR\rcoordinatorId\x12?\n" +
	"\rcreation_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\"R\n" +
	"\x0ePoolerPosition\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.clustermetadata.ShardRuleR\x04rule\x12\x10\n" +
	"\x03lsn\x18\x02 \x01(\tR\x03lsn\"B\n" +
	"\x10HighestKnownRule\x12.\n" +
	"\x04rule\x18\x01 \x01(\v2\x1a.clustermetadata.ShardRuleR\x04rule\"\xe1\x01\n" +
	"\x0eTermRevocation\x12,\n" +
	"\x12revoked_below_term\x18\x01 \x01(\x03R\x10revokedBelowTerm\x12K\n" +
	"\x17accepted_coordinator_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\x15acceptedCoordinatorId\x12T\n" +
	"\x18coordinator_initiated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x16coordinatorInitiatedAt\"\x9d\x02\n" +
	"\x0fConsensusStatus\x12H\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1f.clustermetadata.TermRevocationR\x0etermRevocation\x12J\n" +
	"\x10current_position\x18\x02 \x01(\v2\x1f.clustermetadata.PoolerPositionR\x0fcurrentPosition\x12O\n" +
	"\x12highest_known_rule\x18\x03 \x01(\v2!.clustermetadata.HighestKnownRuleR\x10highestKnownRule\x12#\n" +
	"\x02id\x18\x04 \x01(\v2\x13.clustermetadata.IDR\x02id\"n\n" +
	"\x10LeadershipStatus\x12\x1f\n" +
	"\vleader_term\x18\x01 \x01(\x03R\n" +
	"leaderTerm\x129\n" +
	"\x06signal\x18\x02 \x01(\x0e2!.clustermetadata.LeadershipSignalR\x06signal\"d\n" +
	"\x12AvailabilityStatus\x12N\n" +
	"\x11leadership_status\x18\x01 \x01(\v2!.clustermetadata.LeadershipStatusR\x10leadershipStatus*@\n" +
	"\n" +
	"PoolerType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPRIMARY\x10\x01\x12\v\n" +
	"\aREPLICA\x10\x02\x12\v\n" +
	"\aDRAINED\x10\x03*L\n" +
	"\x13PoolerServingStatus\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x01\x12\n" +
	"\n" +
	"\x06BACKUP\x10\x02\x12\v\n" +
	"\aRESTORE\x10\x03*h\n" +
	"\n" +
	"QuorumType\x12\x17\n" +
	"\x13QUORUM_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16QUORUM_TYPE_AT_LEAST_N\x10\x03\x12%\n" +
	"!QUORUM_TYPE_MULTI_CELL_AT_LEAST_N\x10\x04*z\n" +
	"\x10LeadershipSignal\x12\x1d\n" +
	"\x19LEADERSHIP_SIGNAL_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18LEADERSHIP_SIGNAL_ACTIVE\x10\x01\x12)\n" +
	"%LEADERSHIP_SIGNAL_REQUESTING_DEMOTION\x10\x02B6Z4github.com/multigres/multigres/go/pb/clustermetadatab\x06proto3"

var (
	file_clustermetadata_proto_rawDescOnce sync.Once
	file_clustermetadata_proto_rawDescData []byte
)

func file_clustermetadata_proto_rawDescGZIP() []byte {
	file_clustermetadata_proto_rawDescOnce.Do(func() {
		file_clustermetadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clustermetadata_proto_rawDesc), len(file_clustermetadata_proto_rawDesc)))
	})
	return file_clustermetadata_proto_rawDescData
}

var file_clustermetadata_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_clustermetadata_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_clustermetadata_proto_goTypes = []any{
	(PoolerType)(0),               // 0: clustermetadata.PoolerType
	(PoolerServingStatus)(0),      // 1: clustermetadata.PoolerServingStatus
	(QuorumType)(0),               // 2: clustermetadata.QuorumType
	(LeadershipSignal)(0),         // 3: clustermetadata.LeadershipSignal
	(ID_ComponentType)(0),         // 4: clustermetadata.ID.ComponentType
	(*GlobalTopoConfig)(nil),      // 5: clustermetadata.GlobalTopoConfig
	(*Cell)(nil),                  // 6: clustermetadata.Cell
	(*Database)(nil),              // 7: clustermetadata.Database
	(*ShardInitClaim)(nil),        // 8: clustermetadata.ShardInitClaim
	(*BackupLocation)(nil),        // 9: clustermetadata.BackupLocation
	(*FilesystemBackup)(nil),      // 10: clustermetadata.FilesystemBackup
	(*S3Backup)(nil),              // 11: clustermetadata.S3Backup
	(*MultiPooler)(nil),           // 12: clustermetadata.MultiPooler
	(*MultiGateway)(nil),          // 13: clustermetadata.MultiGateway
	(*MultiOrch)(nil),             // 14: clustermetadata.MultiOrch
	(*ID)(nil),                    // 15: clustermetadata.ID
	(*KeyRange)(nil),              // 16: clustermetadata.KeyRange
	(*DurabilityPolicy)(nil),      // 17: clustermetadata.DurabilityPolicy
	(*RuleNumber)(nil),            // 18: clustermetadata.RuleNumber
	(*ShardRule)(nil),             // 19: clustermetadata.ShardRule
	(*PoolerPosition)(nil),        // 20: clustermetadata.PoolerPosition
	(*HighestKnownRule)(nil),      // 21: clustermetadata.HighestKnownRule
	(*TermRevocation)(nil),        // 22: clustermetadata.TermRevocation
	(*ConsensusStatus)(nil),       // 23: clustermetadata.ConsensusStatus
	(*LeadershipStatus)(nil),      // 24: clustermetadata.LeadershipStatus
	(*AvailabilityStatus)(nil),    // 25: clustermetadata.AvailabilityStatus
	nil,                           // 26: clustermetadata.MultiPooler.PortMapEntry
	nil,                           // 27: clustermetadata.MultiGateway.PortMapEntry
	nil,                           // 28: clustermetadata.MultiOrch.PortMapEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_clustermetadata_proto_depIdxs = []int32{
	9,  // 0: clustermetadata.Database.backup_location:type_name -> clustermetadata.BackupLocation
	17, // 1: clustermetadata.Database.bootstrap_durability_policy:type_name -> clustermetadata.DurabilityPolicy
	15, // 2: clustermetadata.ShardInitClaim.claimer_id:type_name -> clustermetadata.ID
	15, // 3: clustermetadata.ShardInitClaim.cohort_members:type_name -> clustermetadata.ID
	10, // 4: clustermetadata.BackupLocation.filesystem:type_name -> clustermetadata.FilesystemBackup
	11, // 5: clustermetadata.BackupLocation.s3:type_name -> clustermetadata.S3Backup
	15, // 6: clustermetadata.MultiPooler.id:type_name -> clustermetadata.ID
	16, // 7: clustermetadata.MultiPooler.key_range:type_name -> clustermetadata.KeyRange
	0,  // 8: clustermetadata.MultiPooler.type:type_name -> clustermetadata.PoolerType
	1,  // 9: clustermetadata.MultiPooler.serving_status:type_name -> clustermetadata.PoolerServingStatus
	26, // 10: clustermetadata.MultiPooler.port_map:type_name -> clustermetadata.MultiPooler.PortMapEntry
	15, // 11: clustermetadata.MultiGateway.id:type_name -> clustermetadata.ID
	27, // 12: clustermetadata.MultiGateway.port_map:type_name -> clustermetadata.MultiGateway.PortMapEntry
	15, // 13: clustermetadata.MultiOrch.id:type_name -> clustermetadata.ID
	28, // 14: clustermetadata.MultiOrch.port_map:type_name -> clustermetadata.MultiOrch.PortMapEntry
	4,  // 15: clustermetadata.ID.component:type_name -> clustermetadata.ID.ComponentType
	2,  // 16: clustermetadata.DurabilityPolicy.quorum_type:type_name -> clustermetadata.QuorumType
	18, // 17: clustermetadata.ShardRule.rule_number:type_name -> clustermetadata.RuleNumber
	15, // 18: clustermetadata.ShardRule.leader_id:type_name -> clustermetadata.ID
	15, // 19: clustermetadata.ShardRule.cohort_members:type_name -> clustermetadata.ID
	17, // 20: clustermetadata.ShardRule.durability_policy:type_name -> clustermetadata.DurabilityPolicy
	15, // 21: clustermetadata.ShardRule.coordinator_id:type_name -> clustermetadata.ID
	29, // 22: clustermetadata.ShardRule.creation_time:type_name -> google.protobuf.Timestamp
	19, // 23: clustermetadata.PoolerPosition.rule:type_name -> clustermetadata.ShardRule
	19, // 24: clustermetadata.HighestKnownRule.rule:type_name -> clustermetadata.ShardRule
	15, // 25: clustermetadata.TermRevocation.accepted_coordinator_id:type_name -> clustermetadata.ID
	29, // 26: clustermetadata.TermRevocation.coordinator_initiated_at:type_name -> google.protobuf.Timestamp
	22, // 27: clustermetadata.ConsensusStatus.term_revocation:type_name -> clustermetadata.TermRevocation
	20, // 28: clustermetadata.ConsensusStatus.current_position:type_name -> clustermetadata.PoolerPosition
	21, // 29: clustermetadata.ConsensusStatus.highest_known_rule:type_name -> clustermetadata.HighestKnownRule
	15, // 30: clustermetadata.ConsensusStatus.id:type_name -> clustermetadata.ID
	3,  // 31: clustermetadata.LeadershipStatus.signal:type_name -> clustermetadata.LeadershipSignal
	24, // 32: clustermetadata.AvailabilityStatus.leadership_status:type_name -> clustermetadata.LeadershipStatus
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_clustermetadata_proto_init() }
func file_clustermetadata_proto_init() {
	if File_clustermetadata_proto != nil {
		return
	}
	file_clustermetadata_proto_msgTypes[4].OneofWrappers = []any{
		(*BackupLocation_Filesystem)(nil),
		(*BackupLocation_S3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clustermetadata_proto_rawDesc), len(file_clustermetadata_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clustermetadata_proto_goTypes,
		DependencyIndexes: file_clustermetadata_proto_depIdxs,
		EnumInfos:         file_clustermetadata_proto_enumTypes,
		MessageInfos:      file_clustermetadata_proto_msgTypes,
	}.Build()
	File_clustermetadata_proto = out.File
	file_clustermetadata_proto_goTypes = nil
	file_clustermetadata_proto_depIdxs = nil
}
