// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Management / introspection RPCs on the multigateway. These are intended for
// multiadmin to drive per-gateway debug pages — the gateway-to-gateway query
// cancellation API lives separately on MultiGatewayService.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multigatewaymanagerservice.proto

package multigatewaymanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiGatewayManager_GetQueryRegistry_FullMethodName     = "/multigatewaymanager.MultiGatewayManager/GetQueryRegistry"
	MultiGatewayManager_GetConsolidatorStats_FullMethodName = "/multigatewaymanager.MultiGatewayManager/GetConsolidatorStats"
)

// MultiGatewayManagerClient is the client API for MultiGatewayManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiGatewayManager exposes diagnostic snapshots of in-process state on a
// single multigateway instance.
type MultiGatewayManagerClient interface {
	// GetQueryRegistry returns the per-fingerprint query registry snapshot,
	// including rolling trend samples for sparkline rendering.
	GetQueryRegistry(ctx context.Context, in *GetQueryRegistryRequest, opts ...grpc.CallOption) (*GetQueryRegistryResponse, error)
	// GetConsolidatorStats returns a snapshot of the prepared-statement
	// consolidator.
	GetConsolidatorStats(ctx context.Context, in *GetConsolidatorStatsRequest, opts ...grpc.CallOption) (*GetConsolidatorStatsResponse, error)
}

type multiGatewayManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiGatewayManagerClient(cc grpc.ClientConnInterface) MultiGatewayManagerClient {
	return &multiGatewayManagerClient{cc}
}

func (c *multiGatewayManagerClient) GetQueryRegistry(ctx context.Context, in *GetQueryRegistryRequest, opts ...grpc.CallOption) (*GetQueryRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueryRegistryResponse)
	err := c.cc.Invoke(ctx, MultiGatewayManager_GetQueryRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiGatewayManagerClient) GetConsolidatorStats(ctx context.Context, in *GetConsolidatorStatsRequest, opts ...grpc.CallOption) (*GetConsolidatorStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsolidatorStatsResponse)
	err := c.cc.Invoke(ctx, MultiGatewayManager_GetConsolidatorStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiGatewayManagerServer is the server API for MultiGatewayManager service.
// All implementations must embed UnimplementedMultiGatewayManagerServer
// for forward compatibility.
//
// MultiGatewayManager exposes diagnostic snapshots of in-process state on a
// single multigateway instance.
type MultiGatewayManagerServer interface {
	// GetQueryRegistry returns the per-fingerprint query registry snapshot,
	// including rolling trend samples for sparkline rendering.
	GetQueryRegistry(context.Context, *GetQueryRegistryRequest) (*GetQueryRegistryResponse, error)
	// GetConsolidatorStats returns a snapshot of the prepared-statement
	// consolidator.
	GetConsolidatorStats(context.Context, *GetConsolidatorStatsRequest) (*GetConsolidatorStatsResponse, error)
	mustEmbedUnimplementedMultiGatewayManagerServer()
}

// UnimplementedMultiGatewayManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiGatewayManagerServer struct{}

func (UnimplementedMultiGatewayManagerServer) GetQueryRegistry(context.Context, *GetQueryRegistryRequest) (*GetQueryRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueryRegistry not implemented")
}
func (UnimplementedMultiGatewayManagerServer) GetConsolidatorStats(context.Context, *GetConsolidatorStatsRequest) (*GetConsolidatorStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsolidatorStats not implemented")
}
func (UnimplementedMultiGatewayManagerServer) mustEmbedUnimplementedMultiGatewayManagerServer() {}
func (UnimplementedMultiGatewayManagerServer) testEmbeddedByValue()                             {}

// UnsafeMultiGatewayManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiGatewayManagerServer will
// result in compilation errors.
type UnsafeMultiGatewayManagerServer interface {
	mustEmbedUnimplementedMultiGatewayManagerServer()
}

func RegisterMultiGatewayManagerServer(s grpc.ServiceRegistrar, srv MultiGatewayManagerServer) {
	// If the following call pancis, it indicates UnimplementedMultiGatewayManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiGatewayManager_ServiceDesc, srv)
}

func _MultiGatewayManager_GetQueryRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiGatewayManagerServer).GetQueryRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiGatewayManager_GetQueryRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiGatewayManagerServer).GetQueryRegistry(ctx, req.(*GetQueryRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiGatewayManager_GetConsolidatorStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsolidatorStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiGatewayManagerServer).GetConsolidatorStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiGatewayManager_GetConsolidatorStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiGatewayManagerServer).GetConsolidatorStats(ctx, req.(*GetConsolidatorStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiGatewayManager_ServiceDesc is the grpc.ServiceDesc for MultiGatewayManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiGatewayManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multigatewaymanager.MultiGatewayManager",
	HandlerType: (*MultiGatewayManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQueryRegistry",
			Handler:    _MultiGatewayManager_GetQueryRegistry_Handler,
		},
		{
			MethodName: "GetConsolidatorStats",
			Handler:    _MultiGatewayManager_GetConsolidatorStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multigatewaymanagerservice.proto",
}
