// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package manager

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"path/filepath"
	"sync"
	"sync/atomic"
	"time"

	"github.com/multigres/multigres/go/common/backup"
	commonconsensus "github.com/multigres/multigres/go/common/consensus"
	"github.com/multigres/multigres/go/common/constants"
	"github.com/multigres/multigres/go/common/mterrors"
	"github.com/multigres/multigres/go/common/servenv"
	"github.com/multigres/multigres/go/common/sqltypes"
	"github.com/multigres/multigres/go/common/timeouts"
	"github.com/multigres/multigres/go/common/topoclient"
	commontypes "github.com/multigres/multigres/go/common/types"
	"github.com/multigres/multigres/go/services/multipooler/connpoolmanager"
	"github.com/multigres/multigres/go/services/multipooler/executor"
	"github.com/multigres/multigres/go/services/multipooler/heartbeat"
	"github.com/multigres/multigres/go/services/multipooler/poolerserver"
	"github.com/multigres/multigres/go/services/multipooler/pubsub"
	"github.com/multigres/multigres/go/tools/grpccommon"
	"github.com/multigres/multigres/go/tools/retry"
	"github.com/multigres/multigres/go/tools/telemetry"
	"github.com/multigres/multigres/go/tools/timer"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	clustermetadatapb "github.com/multigres/multigres/go/pb/clustermetadata"
	mtrpcpb "github.com/multigres/multigres/go/pb/mtrpc"
	multipoolermanagerdatapb "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	pgctldpb "github.com/multigres/multigres/go/pb/pgctldservice"
)

// ManagerState represents the state of the MultiPoolerManager
type ManagerState string

const (
	// ManagerStateStarting indicates the manager is starting and loading the multipooler record
	ManagerStateStarting ManagerState = "starting"
	// ManagerStateReady indicates the manager has successfully loaded the multipooler record
	ManagerStateReady ManagerState = "ready"
	// ManagerStateError indicates the manager failed to load the multipooler record
	ManagerStateError ManagerState = "error"
)

// MultiPoolerManager manages the pooler lifecycle and PostgreSQL operations
type MultiPoolerManager struct {
	logger     *slog.Logger
	config     *Config
	topoClient topoclient.Store
	// Deprecated: use servicePoolerID instead.
	serviceID       *clustermetadatapb.ID
	servicePoolerID poolerID
	replTracker     *heartbeat.ReplTracker
	pubsubListener  *pubsub.Listener
	pgctldClient    pgctldpb.PgCtldClient

	// connPoolMgr manages all connection pools (admin, regular, reserved)
	connPoolMgr connpoolmanager.PoolManager

	// qsc is the query service controller
	// This controller handles query serving while the manager orchestrates lifecycle,
	// topology, consensus, and replication operations.
	qsc poolerserver.PoolerController

	// actionLock is there to run only one action at a time.
	// This lock can be held for long periods of time (hours),
	// like in the case of a restore. This lock must be obtained
	// first before other mutexes.
	actionLock *ActionLock

	// Multipooler record from topology and startup state

	// mu is the mutex for the manager's state. It must be held for the
	// following:
	// - Reading state
	// - Changing state. This can cause the lock to be held for long periods
	//   of time, particularly when updating external systems (e.g. the topo)
	//   to match the manager's state.
	mu sync.Mutex

	isOpen bool
	// all fields other than Type and ServingStatus never change after initialization.
	// They can be accessed without holding the lock.
	// Type and ServingStatus are exclusively written by the StateManager.
	multipooler    *clustermetadatapb.MultiPooler
	state          ManagerState
	stateError     error
	consensusState *ConsensusState
	topoLoaded     bool
	rules          ruleStorer
	ctx            context.Context
	cancel         context.CancelFunc
	loadTimeout    time.Duration

	// readyChan is closed when state becomes Ready or Error, to broadcast to all waiters.
	// Unbuffered is safe here because we only close() the channel (which never blocks
	// and broadcasts to all receivers) rather than sending to it.
	readyChan chan struct{}

	// Cached backup config from the database topology record.
	// This is loaded once during startup and cached for fast access.
	backupConfig *backup.Config

	// pgBackRestConfigPath is the path to the pgbackrest.conf client config file
	// generated by multipooler during startup. Set once in loadMultiPoolerFromTopo.
	pgBackRestConfigPath string

	// pgMonitorRetryInterval is the interval between auto-restore retry attempts.
	// Defaults to 1 second. Can be set to a shorter duration for testing.
	pgMonitorRetryInterval time.Duration

	// initialized tracks whether this pooler has been fully initialized.
	// Once true, stays true for the lifetime of the manager.
	initialized bool

	// resignedLeaderAtTerm is set when this node voluntarily resigns as primary
	// (via EmergencyDemote). The value is the consensus term at which the primary
	// resigned. A non-zero value signals the coordinator to trigger an immediate
	// election. Protected by mu. Cleared when this node is elected primary again.
	resignedLeaderAtTerm int64

	// pgMonitor manages the PostgreSQL monitoring loop.
	pgMonitor *timer.PeriodicRunner

	// rewindPending suppresses the postgres monitor after emergency demotion until a
	// rewind completes successfully. Set by emergencyDemoteLocked, cleared by RewindToSource.
	rewindPending atomic.Bool

	// promotionInProgress is set while pg_promote() has been called but postgres has not yet
	// transitioned to primary mode. Cleared when promotion completes (success or failure).
	// Reported in the health status so multiorch can suppress spurious PrimaryIsDead detection.
	promotionInProgress atomic.Bool

	// postgresRestartsDisabled suppresses auto-restart of a stopped PostgreSQL instance.
	// When set, the monitor continues to run and detect problems but skips the start action.
	// False by default (restarts enabled); tests and demos set it during controlled failovers.
	postgresRestartsDisabled atomic.Bool

	// pgMonitorLastLoggedReason tracks the last logged reason in the monitor to avoid duplicate logs.
	pgMonitorLastLoggedReason string

	// servingState coordinates serving state transitions across components
	// (query service, heartbeat tracker) and updates the multipooler record.
	servingState *StateManager

	// The following three variables are for pgbackrest.
	primaryPoolerID *clustermetadatapb.ID
	primaryHost     string
	primaryPort     int32

	// metrics holds OTel gauges for pgBackRest server health.
	metrics *Metrics

	// healthStreamer streams health state to subscribers.
	// Owns all health-related state and provides typed update methods.
	healthStreamer *healthStreamer

	// topoPublisher asynchronously reflects in-memory state to etcd.
	topoPublisher *topoPublisher
}

// promotionState tracks which parts of the promotion are complete
type promotionState struct {
	isPrimaryInPostgres    bool
	isPrimaryInTopology    bool
	syncReplicationMatches bool
	currentLSN             string
}

// demotionState tracks which parts of the demotion are complete
type demotionState struct {
	isNotServing        bool   // PoolerServingStatus == NOT_SERVING (includes heartbeat stopped)
	isReplicaInTopology bool   // PoolerType == REPLICA
	isReadOnly          bool   // default_transaction_read_only = on
	finalLSN            string // Captured LSN before demotion
}

// NewMultiPoolerManager creates a new MultiPoolerManager instance
func NewMultiPoolerManager(logger *slog.Logger, multiPooler *clustermetadatapb.MultiPooler, config *Config) (*MultiPoolerManager, error) {
	return NewMultiPoolerManagerWithTimeout(logger, multiPooler, config, 5*time.Minute)
}

// NewMultiPoolerManagerWithTimeout creates a new MultiPoolerManager instance with a custom load timeout
func NewMultiPoolerManagerWithTimeout(logger *slog.Logger, multiPooler *clustermetadatapb.MultiPooler, config *Config, loadTimeout time.Duration) (*MultiPoolerManager, error) {
	// Validate required multiPooler fields
	if multiPooler == nil {
		return nil, mterrors.New(mtrpcpb.Code_INVALID_ARGUMENT, "multiPooler is required")
	}
	if multiPooler.TableGroup == "" {
		return nil, mterrors.New(mtrpcpb.Code_INVALID_ARGUMENT, "TableGroup is required")
	}
	if multiPooler.Shard == "" {
		return nil, mterrors.New(mtrpcpb.Code_INVALID_ARGUMENT, "Shard is required")
	}
	if multiPooler.Id == nil {
		return nil, mterrors.New(mtrpcpb.Code_INVALID_ARGUMENT, "MultiPooler.Id is required")
	}
	svcPoolerID, err := newPoolerID(multiPooler.Id)
	if err != nil {
		return nil, mterrors.Wrap(err, "invalid MultiPooler.Id")
	}

	// MVP validation: fail fast if tablegroup/shard are not the MVP defaults
	if err := constants.ValidateMVPTableGroupAndShard(multiPooler.TableGroup, multiPooler.Shard); err != nil {
		return nil, mterrors.Wrap(err, "MVP validation failed")
	}

	ctx, cancel := context.WithCancel(context.TODO())

	// Create pgctld gRPC client
	var pgctldClient pgctldpb.PgCtldClient
	if config.PgctldAddr != "" {
		conn, err := grpccommon.NewClient(config.PgctldAddr, grpccommon.WithDialOptions(grpc.WithTransportCredentials(insecure.NewCredentials())))
		if err != nil {
			logger.ErrorContext(ctx, "Failed to create pgctld gRPC client", "error", err, "addr", config.PgctldAddr)
			// Continue without client - operations that need it will fail gracefully
		} else {
			rawClient := pgctldpb.NewPgCtldClient(conn)
			pgctldClient = NewProtectedPgctldClient(rawClient)
			logger.InfoContext(ctx, "Created pgctld gRPC client", "addr", config.PgctldAddr)
		}
	}

	// Create connection pool manager from config
	var connPoolMgr connpoolmanager.PoolManager
	if config.ConnPoolConfig != nil {
		connPoolMgr = config.ConnPoolConfig.NewManager(logger)
	}

	monitorRetryInterval := 5 * time.Second
	monitorRunner := timer.NewPeriodicRunner(ctx, monitorRetryInterval)

	pm := &MultiPoolerManager{
		logger:                 logger.With("pooler_name", multiPooler.Id.GetName()),
		config:                 config,
		topoClient:             config.TopoClient,
		serviceID:              multiPooler.Id,
		servicePoolerID:        svcPoolerID,
		multipooler:            multiPooler,
		actionLock:             NewActionLock(),
		state:                  ManagerStateStarting,
		loadTimeout:            loadTimeout,
		pgMonitorRetryInterval: monitorRetryInterval,
		pgctldClient:           pgctldClient,
		connPoolMgr:            connPoolMgr,
		readyChan:              make(chan struct{}),
		pgMonitor:              monitorRunner,
		healthStreamer:         newHealthStreamer(logger, multiPooler.Id, multiPooler.TableGroup, multiPooler.Shard),
		// We create a dummy context because some unit tests need them.
		// These will be overwritten when Open gets called.
		ctx:    ctx,
		cancel: cancel,
	}

	// Load consensus state from disk. Missing file means term=0 (new node), which is fine.
	// Only actual read/parse errors fail the constructor.
	pm.consensusState = NewConsensusState(pm.multipooler.PoolerDir, pm.serviceID)
	if config.ConsensusEnabled {
		if _, err := pm.consensusState.Load(); err != nil {
			cancel()
			return nil, fmt.Errorf("failed to load consensus state from disk: %w", err)
		}
	}

	// Create the query service controller with the pool manager.
	// Get the drain grace period from connpool config (0 means use default).
	var drainGracePeriod time.Duration
	if config.ConnPoolConfig != nil {
		drainGracePeriod = config.ConnPoolConfig.DrainGracePeriod()
	}
	pm.qsc = poolerserver.NewQueryPoolerServer(logger, connPoolMgr, multiPooler.Id, multiPooler.TableGroup, multiPooler.Shard, pm, drainGracePeriod)
	pm.rules = newRuleStore(pm.logger, pm.qsc.InternalQueryService())

	// The health streamer must wait for the query server to update its type before
	// broadcasting SERVING transitions, so the gateway doesn't discover the new
	// primary before the pooler is ready to accept requests for that type.
	pm.healthStreamer.SetQueryServer(pm.qsc)

	// Create the serving state manager with the query service and health streamer as initial components.
	// The ReplTracker is registered later when heartbeat is started.
	pm.servingState = NewStateManager(logger, pm.multipooler, pm.qsc, pm.healthStreamer)

	// Register pgBackRest health metrics.
	var metricsErr error
	pm.metrics, metricsErr = NewMetrics()
	if metricsErr != nil {
		logger.Warn("failed to register pgBackRest metrics", "error", metricsErr)
	}

	pm.topoPublisher = newTopoPublisher(logger, config.TopoClient)

	return pm, nil
}

// internalQueryService returns the InternalQueryService for executing queries via the connection pool.
func (pm *MultiPoolerManager) internalQueryService() executor.InternalQueryService {
	if pm.qsc == nil {
		return nil
	}
	return pm.qsc.InternalQueryService()
}

// query executes a query using the internal query service and returns the result.
// This is a convenience method for internal manager operations.
func (pm *MultiPoolerManager) query(ctx context.Context, sql string) (*sqltypes.Result, error) {
	queryService := pm.internalQueryService()
	if queryService == nil {
		return nil, errors.New("internal query service not available")
	}
	return queryService.Query(ctx, sql)
}

// exec executes a command that doesn't return rows.
// This is a convenience method for internal manager operations.
func (pm *MultiPoolerManager) exec(ctx context.Context, sql string) error {
	_, err := pm.query(ctx, sql)
	return err
}

// queryArgs executes a parameterized query using the internal query service and returns the result.
// This is a convenience method for internal manager operations that helps prevent SQL injection.
func (pm *MultiPoolerManager) queryArgs(ctx context.Context, sql string, args ...any) (*sqltypes.Result, error) {
	queryService := pm.internalQueryService()
	if queryService == nil {
		return nil, errors.New("internal query service not available")
	}
	return queryService.QueryArgs(ctx, sql, args...)
}

// execArgs executes a parameterized command that doesn't return rows.
// This is a convenience method for internal manager operations that helps prevent SQL injection.
func (pm *MultiPoolerManager) execArgs(ctx context.Context, sql string, args ...any) error {
	_, err := pm.queryArgs(ctx, sql, args...)
	return err
}

// Open opens the database connections and starts background operations.
// This operation is infallible - if connection pools fail to open, queries will fail
// gracefully at query time rather than preventing the manager from opening.
// Open is idempotent and safe to call multiple times.
func (pm *MultiPoolerManager) Open() {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	if pm.isOpen {
		return
	}

	pm.ctx, pm.cancel = context.WithCancel(context.TODO())

	pm.openConnectionsLocked()
	pm.logger.InfoContext(pm.ctx, "MultiPoolerManager opened database connection")

	// Start background PostgreSQL monitoring and auto-recovery. prevState
	// persists between ticks so that broadcastHealth fires only on transitions
	// in postgres running state, not every tick.
	prevState := postgresState{}
	pm.pgMonitor.Start(func(ctx context.Context) {
		if newState, err := pm.monitorPostgresIteration(ctx); err == nil {
			// Broadcast postgres health transitions so orchestrators learn
			// about changes immediately without waiting for the next 30-second
			// heartbeat. This is especially important for:
			//   - postgres going down: allows PrimaryIsDeadAnalyzer to detect failure promptly
			//   - postgres coming back up: allows FixReplication to see IsInitialized=true quickly
			if !postgresStateEqual(newState, prevState) {
				pm.logger.InfoContext(ctx, "MonitorPostgres: postgres state changed, broadcasting health",
					"postgres_running", newState.postgresRunning)
				pm.broadcastHealth()
			}
			prevState = newState
		}
	}, nil)
	pm.logger.InfoContext(pm.ctx, "MonitorPostgres enabled successfully")

	pm.isOpen = true

	// Start topology publisher goroutine to eventually-consistently sync state to etcd.
	go pm.topoPublisher.Run(pm.ctx)

	// Start health heartbeat goroutine and transition to SERVING.
	// SetState notifies all components (query service, heartbeat, health streamer).
	go pm.runHealthHeartbeat(pm.ctx, timeouts.DefaultHealthHeartbeatInterval)
	if err := pm.servingState.SetState(pm.ctx, pm.multipooler.Type, clustermetadatapb.PoolerServingStatus_SERVING); err != nil {
		pm.logger.ErrorContext(pm.ctx, "Failed to transition to SERVING on open", "error", err)
	}
}

// Pause temporarily closes the manager for maintenance operations that require
// exclusive database access (e.g., pg_rewind). Returns a resume function that
// MUST be called to reopen the manager.
//
// The resume function is safe to call multiple times (idempotent). This allows
// using both defer and explicit calls:
//
//	resume := pm.Pause()
//	defer resume()  // Guarantees cleanup
//	// ... perform maintenance ...
//	resume()  // Explicit resume at the right time
//	// defer will call resume() again safely
//
// Note: Pause() cancels the manager's context, but Open() creates a fresh one.
func (pm *MultiPoolerManager) Pause() (resume func()) {
	if !pm.closeLocked("paused") {
		pm.logger.Error("MultiPoolerManager: Pause() called on already-closed manager")
	}

	return func() {
		pm.Open()
	}
}

// Shutdown permanently closes the database connection and stops background operations.
// Use this for final cleanup when the manager will no longer be used.
// Unlike Pause(), Shutdown does not return a resume function, signaling permanent closure.
// Safe to call multiple times and safe to call even if never opened.
func (pm *MultiPoolerManager) Shutdown() {
	pm.closeLocked("shutdown")
}

// closeLocked performs the actual close operation.
// Returns true if the manager was open and is now closed, false if it was already closed.
// Caller should NOT hold pm.mu - this function acquires it.
// Always cancels the context - Open() will create a fresh one if reopened.
func (pm *MultiPoolerManager) closeLocked(logMessage string) bool {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	if !pm.isOpen {
		return false
	}

	// Transition to NOT_SERVING before closing resources. This notifies all
	// components: query service rejects queries, heartbeat stops, health
	// streamer broadcasts NOT_SERVING to subscribers.
	if err := pm.servingState.SetState(pm.ctx, pm.multipooler.Type, clustermetadatapb.PoolerServingStatus_NOT_SERVING); err != nil {
		pm.logger.Warn("Failed to transition to NOT_SERVING during close", "error", err)
	}

	pm.pgMonitor.Stop()
	pm.closeConnectionsLocked()
	pm.cancel()
	pm.isOpen = false
	pm.logger.Info("MultiPoolerManager: " + logMessage)
	return true
}

// startHeartbeat starts the replication tracker and syncs it to the current serving state.
// The heartbeat writer/reader mode is determined by the multipooler record (the source of truth),
// not by querying the database directly. If the type later changes (e.g., via promotion or
// topology load), StateManager.SetState will notify the replTracker.
func (pm *MultiPoolerManager) startHeartbeat(ctx context.Context, shardID []byte, poolerID string) error {
	// Create the replication tracker using the executor's InternalQueryService
	pm.replTracker = heartbeat.NewReplTracker(pm.qsc.InternalQueryService(), pm.logger, shardID, poolerID, pm.config.HeartbeatIntervalMs)

	// Register with StateManager and sync to current state. This ensures the
	// heartbeat writer starts for PRIMARY or the reader starts for REPLICA,
	// based on whatever state the StateManager currently holds.
	return pm.servingState.RegisterAndSync(ctx, pm.replTracker)
}

// startPubSubListener creates the shared LISTEN/NOTIFY listener and registers
// it with the state manager. The listener runs only when PRIMARY+SERVING.
func (pm *MultiPoolerManager) startPubSubListener(ctx context.Context) error {
	if pm.connPoolMgr == nil {
		return nil
	}
	pubsubMetrics, err := pubsub.NewPubSubMetrics()
	if err != nil {
		pm.logger.WarnContext(ctx, "failed to initialise some pubsub metrics", "error", err)
	}
	pm.pubsubListener = pubsub.NewListener(pm.connPoolMgr, pm.logger, pubsubMetrics)
	pm.qsc.SetPubSubListener(pm.pubsubListener)
	return pm.servingState.RegisterAndSync(ctx, pm.pubsubListener)
}

// QueryServiceControl returns the query service controller.
// This follows the TabletManager pattern of exposing the controller.
func (pm *MultiPoolerManager) QueryServiceControl() poolerserver.PoolerController {
	return pm.qsc
}

// openConnectionsLocked opens database connections and initializes connection-related components.
// This operation is infallible - connection pool failures are handled gracefully at query time.
// Caller must hold pm.mu.
// This is symmetric to closeConnectionsLocked and used by both Open() and reopenConnections().
func (pm *MultiPoolerManager) openConnectionsLocked() {
	// Open connection pool manager

	// Open connection pool manager
	if pm.connPoolMgr != nil {
		pgPort := int(pm.multipooler.PortMap["postgres"])
		connConfig := &connpoolmanager.ConnectionConfig{
			SocketFile: pm.config.SocketFilePath,
			Port:       pgPort,
			Database:   pm.multipooler.Database,
		}
		pm.connPoolMgr.Open(pm.ctx, connConfig)
		pm.logger.Info("Connection pool manager opened")
	}

	// Create sidecar schema and start heartbeat before opening query service controller
	// This ensures the schema exists before queries can be served
	if pm.replTracker == nil {
		pm.logger.Info("MultiPoolerManager: Starting database heartbeat")
		ctx := context.TODO()
		// TODO: populate shard ID
		shardID := []byte("0") // default shard ID

		// Use the multipooler name from serviceID as the pooler ID
		poolerID := pm.serviceID.Name

		// Schema creation is now handled by multiorch during bootstrap initialization
		// Do not auto-create schema when connecting to postgres

		if err := pm.startHeartbeat(ctx, shardID, poolerID); err != nil {
			pm.logger.ErrorContext(ctx, "Failed to start heartbeat", "error", err)
			// Don't fail the connection if heartbeat fails
		}
	}

	// Start PubSub listener for LISTEN/NOTIFY support.
	if pm.pubsubListener == nil {
		if err := pm.startPubSubListener(context.TODO()); err != nil {
			pm.logger.Error("Failed to start PubSub listener", "error", err)
		}
	}
}

// closeConnectionsLocked closes the connection pool manager and query service controller
// without canceling the main context. Caller must hold pm.mu.
// This is used by reopenConnections() during auto-restore to avoid canceling
// the startup context that WaitUntilReady is waiting on.
func (pm *MultiPoolerManager) closeConnectionsLocked() {
	// Close resources (safe to call even if nil/never opened)
	if pm.replTracker != nil {
		pm.replTracker.Close()
		pm.replTracker = nil
	}

	if pm.pubsubListener != nil {
		pm.pubsubListener.Stop()
		pm.pubsubListener = nil
	}

	// Close connection pool manager
	if pm.connPoolMgr != nil {
		pm.connPoolMgr.Close()
	}
}

// reopenConnections closes and reopens database connections without canceling
// the manager's context. This is used to refresh stale connection pool file
// descriptors after PostgreSQL has been restarted, without disrupting contexts
// derived from pm.ctx (e.g., during auto-restore at startup).
func (pm *MultiPoolerManager) reopenConnections(_ context.Context) {
	pm.mu.Lock()
	defer pm.mu.Unlock()

	pm.closeConnectionsLocked()
	pm.openConnectionsLocked()
}

// GetState returns the current state of the manager
func (pm *MultiPoolerManager) GetState() ManagerState {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	return pm.state
}

// GetStateAndError returns the current manager state and error (used for testing)
func (pm *MultiPoolerManager) GetStateAndError() (ManagerState, error) {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	return pm.state, pm.stateError
}

// stanzaName returns the pgbackrest stanza name
func (pm *MultiPoolerManager) stanzaName() string {
	return "multigres"
}

// getPgCtldClient returns the pgctld gRPC client
func (pm *MultiPoolerManager) getPgCtldClient() pgctldpb.PgCtldClient {
	return pm.pgctldClient
}

// getPoolerType returns the pooler type from the multipooler record
func (pm *MultiPoolerManager) getPoolerType() clustermetadatapb.PoolerType {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	return pm.multipooler.Type
}

// shardKey returns a ShardKey identifying this pooler's shard.
func (pm *MultiPoolerManager) shardKey() commontypes.ShardKey {
	return commontypes.ShardKey{
		Database:   pm.multipooler.Database,
		TableGroup: pm.multipooler.TableGroup,
		Shard:      pm.multipooler.Shard,
	}
}

// checkReady returns an error if the manager is not in Ready state
func (pm *MultiPoolerManager) checkReady() error {
	pm.mu.Lock()
	defer pm.mu.Unlock()

	switch pm.state {
	case ManagerStateReady:
		return nil
	case ManagerStateStarting:
		return mterrors.New(mtrpcpb.Code_UNAVAILABLE, "manager is still starting up")
	case ManagerStateError:
		return mterrors.Wrap(pm.stateError, "manager is in error state")
	default:
		return mterrors.New(mtrpcpb.Code_INTERNAL, fmt.Sprintf("manager is in unknown state: %s", pm.state))
	}
}

// checkPoolerType verifies that the pooler matches the expected type
func (pm *MultiPoolerManager) checkPoolerType(expectedType clustermetadatapb.PoolerType, operationName string) error {
	pm.mu.Lock()
	poolerType := pm.multipooler.Type
	pm.mu.Unlock()

	if poolerType != expectedType {
		pm.logger.Error(operationName+" called on incorrect pooler type",
			"service_id", pm.serviceID.String(),
			"pooler_type", poolerType.String(),
			"expected_type", expectedType.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("operation not allowed: pooler type is %s, must be %s (service_id: %s)",
				poolerType.String(), expectedType.String(), pm.serviceID.String()))
	}
	return nil
}

// getCurrentTermNumber returns the current consensus term number.
func (pm *MultiPoolerManager) getCurrentTermNumber(ctx context.Context) (int64, error) {
	return pm.consensusState.GetCurrentTermNumber(ctx)
}

// checkReplicaGuardrails verifies that the pooler is a REPLICA and PostgreSQL is in recovery mode
// This is a common guardrail for replication-related operations on standby servers
func (pm *MultiPoolerManager) checkReplicaGuardrails(ctx context.Context) error {
	// Guardrail: Check pooler type - only REPLICA poolers can perform replication operations
	if err := pm.checkPoolerType(clustermetadatapb.PoolerType_REPLICA, "Replication operation"); err != nil {
		return err
	}

	// Guardrail: Check if the PostgreSQL instance is in recovery (standby mode)
	isInRecovery, err := pm.isInRecovery(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to check if instance is in recovery", "error", err)
		return mterrors.Wrap(err, "failed to check recovery status")
	}

	if !isInRecovery {
		pm.logger.ErrorContext(ctx, "Replication operation called on non-standby instance", "service_id", pm.serviceID.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("operation not allowed: the PostgreSQL instance is not in standby mode (service_id: %s)", pm.serviceID.String()))
	}

	return nil
}

// checkPrimaryGuardrails verifies that PostgreSQL is not in recovery mode.
// This is the canonical guardrail for primary-only operations.
func (pm *MultiPoolerManager) checkPrimaryGuardrails(ctx context.Context) error {
	isInRecovery, err := pm.isInRecovery(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to check if instance is in recovery", "error", err)
		return mterrors.Wrap(err, "failed to check recovery status")
	}

	if isInRecovery {
		pm.logger.ErrorContext(ctx, "Primary operation called on standby instance", "service_id", pm.serviceID.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("operation not allowed: the PostgreSQL instance is in standby mode (service_id: %s)", pm.serviceID.String()))
	}

	return nil
}

// setStateError sets the manager state to error with the given error message
// Must be called without holding the mutex
func (pm *MultiPoolerManager) setStateError(err error) {
	pm.mu.Lock()
	defer pm.mu.Unlock()
	pm.state = ManagerStateError
	pm.stateError = err
	pm.logger.Error("Manager state changed", "state", ManagerStateError, "error", err.Error())

	// Signal that we've reached a terminal state
	select {
	case <-pm.readyChan:
		// Already closed
	default:
		close(pm.readyChan)
	}
}

// checkAndSetReady checks if all required resources are loaded and sets state to ready if so
// Must be called without holding the mutex
func (pm *MultiPoolerManager) checkAndSetReady() {
	pm.mu.Lock()
	defer pm.mu.Unlock()

	if pm.topoLoaded {
		pm.state = ManagerStateReady
		pm.logger.Info("Manager state changed", "state", ManagerStateReady, "service_id", pm.serviceID.String())

		// Signal that we've reached ready state
		select {
		case <-pm.readyChan:
			// Already closed
		default:
			close(pm.readyChan)
		}

		// Set initial leader observation from the highest known rule.
		// commonconsensus.LeaderTerm returns 0 unless the rule names us as the
		// leader, so publishing serviceID here is safe.
		if cs, err := pm.getInconsistentConsensusStatus(pm.ctx); err == nil {
			if primaryTerm := commonconsensus.LeaderTerm(cs); primaryTerm > 0 {
				pm.healthStreamer.UpdateLeaderObservation(&poolerserver.LeaderObservation{
					LeaderID:   pm.serviceID,
					LeaderTerm: primaryTerm,
				})
			}
		}
	}
}

// loadMultiPoolerFromTopo loads the multipooler record from topology asynchronously
// TODO(sougou): Simplify: We actually just have to verify that we were able to write the record
// to the topo.
func (pm *MultiPoolerManager) loadMultiPoolerFromTopo() {
	// Validate ServiceID is not nil
	if pm.serviceID == nil {
		pm.setStateError(errors.New("ServiceID cannot be nil"))
		return
	}

	// Set timeout for the entire loading process
	timeoutCtx, timeoutCancel := context.WithTimeout(pm.ctx, pm.loadTimeout)
	defer timeoutCancel()

	r := retry.New(100*time.Millisecond, 30*time.Second)
	for _, err := range r.Attempts(timeoutCtx) {
		if err != nil {
			if errors.Is(err, context.DeadlineExceeded) {
				pm.setStateError(fmt.Errorf("timeout waiting for multipooler record to be available in topology after %v", pm.loadTimeout))
			} else {
				pm.setStateError(errors.New("manager context cancelled while loading multipooler record"))
			}
			return
		}

		ctx, cancel := context.WithTimeout(pm.ctx, 5*time.Second)
		_, err := pm.topoClient.GetMultiPooler(ctx, pm.serviceID)
		cancel()

		if err != nil {
			continue // Will retry with backoff
		}
		// Successfully loaded multipooler record
		// Now load the backup location from the database topology
		database := pm.multipooler.Database
		if database == "" {
			pm.setStateError(errors.New("database name not set in multipooler"))
			return
		}

		ctx, cancel = context.WithTimeout(pm.ctx, 5*time.Second)
		db, err := pm.topoClient.GetDatabase(ctx, database)
		cancel()
		if err != nil {
			pm.setStateError(fmt.Errorf("failed to get database %s from topology: %w", database, err))
			return
		}

		// Validate and parse backup configuration
		backupConfig, err := backup.NewConfig(db.BackupLocation)
		if err != nil {
			pm.setStateError(fmt.Errorf("invalid backup_location: %w", err))
			return
		}

		// Verify we can compute the full backup path
		_, err = backupConfig.FullPath(database, pm.multipooler.TableGroup, pm.multipooler.Shard)
		if err != nil {
			pm.setStateError(fmt.Errorf("failed to compute backup path: %w", err))
			return
		}

		// Generate pgbackrest client config now that we have backup location
		pgPort := int(pm.multipooler.PortMap["postgres"])
		socketDir := filepath.Join(pm.multipooler.PoolerDir, "pg_sockets")
		pg1User := constants.DefaultPostgresUser
		if pm.connPoolMgr != nil {
			pg1User = pm.connPoolMgr.PgUser()
		}
		configPath, err := backup.WriteClientConfig(backup.ClientConfigOpts{
			PoolerDir:     pm.multipooler.PoolerDir,
			Pg1Port:       pgPort,
			Pg1SocketPath: socketDir,
			Pg1Path:       postgresDataDir(),
			Pg1User:       pg1User,
		}, backupConfig)
		if err != nil {
			pm.setStateError(fmt.Errorf("failed to generate pgbackrest client config: %w", err))
			return
		}
		pm.logger.Info("Generated pgbackrest client config", "path", configPath)

		pm.mu.Lock()
		pm.backupConfig = backupConfig
		pm.pgBackRestConfigPath = configPath
		pm.topoLoaded = true
		pm.mu.Unlock()

		// Notify all components of the pooler type loaded from topology.
		if err := pm.servingState.SetState(pm.ctx, pm.multipooler.Type, pm.multipooler.ServingStatus); err != nil {
			pm.logger.Error("Failed to set state after topo load", "error", err)
		}

		// Note: restoring from backup (for replicas) happens in a separate goroutine

		pm.checkAndSetReady()
		return
	}
}

// validateAndUpdateTerm validates the request term against the current term following Consensus rules.
// Returns an error if the request term is stale (less than current term).
// If the request term is higher, it updates the term in pgctld and the cache.
// If force is true, validation is skipped.
func (pm *MultiPoolerManager) validateAndUpdateTerm(ctx context.Context, requestTerm int64, force bool) error {
	if force {
		return nil // Skip validation if force is set
	}

	currentTerm, err := pm.getCurrentTermNumber(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current term: %w", err)
	}

	// If request term == current term: ACCEPT (same term, execute)
	// If request term < current term: REJECT (stale request)
	// If request term > current term: UPDATE term and ACCEPT (new term discovered)
	if requestTerm < currentTerm {
		// Request has stale term, reject
		pm.logger.ErrorContext(ctx, "Consensus term too old, rejecting request",
			"request_term", requestTerm,
			"current_term", currentTerm,
			"service_id", pm.serviceID.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("consensus term too old: request term %d is less than current term %d (use force=true to bypass)",
				requestTerm, currentTerm))
	} else if requestTerm > currentTerm {
		// Request has newer term, update our term
		pm.logger.InfoContext(ctx, "Discovered newer term, updating",
			"request_term", requestTerm,
			"old_term", currentTerm,
			"service_id", pm.serviceID.String())

		// Update term atomically (resets accepted leader)
		if err := pm.consensusState.UpdateTermAndSave(ctx, requestTerm); err != nil {
			pm.logger.ErrorContext(ctx, "Failed to update term", "error", err)
			return mterrors.Wrap(err, "failed to update consensus term")
		}

		pm.logger.InfoContext(ctx, "Consensus term updated successfully", "new_term", requestTerm)
	}
	// If requestTerm == currentCachedTerm, just continue (same term is OK)
	return nil
}

// validateTerm validates that the request term is not stale (>= current term).
// Unlike validateAndUpdateTerm, this does NOT update the term.
// This is used when we want to defer the term update until after an operation succeeds.
// If force is true, validation is skipped.
func (pm *MultiPoolerManager) validateTerm(ctx context.Context, requestTerm int64, force bool) error {
	if force {
		return nil // Skip validation if force is set
	}

	currentTerm, err := pm.getCurrentTermNumber(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current term: %w", err)
	}

	// Check if consensus term has been initialized (term 0 means uninitialized)
	if currentTerm == 0 {
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			"consensus term not initialized, must be set via BeginTerm (use force=true to bypass)")
	}

	// Reject stale requests
	if requestTerm < currentTerm {
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("consensus term too old: request term %d is less than current term %d (use force=true to bypass)",
				requestTerm, currentTerm))
	}

	// Accept equal or newer terms
	return nil
}

// updateTermIfNewer updates the consensus term if the provided term is newer than current.
// This is used to decouple term validation from term update, allowing updates to occur
// only after an operation succeeds.
func (pm *MultiPoolerManager) updateTermIfNewer(ctx context.Context, requestTerm int64) error {
	currentTerm, err := pm.getCurrentTermNumber(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current term: %w", err)
	}

	if requestTerm <= currentTerm {
		// Already at or past this term
		return nil
	}

	pm.logger.InfoContext(ctx, "Updating to newer term after successful operation",
		"request_term", requestTerm,
		"old_term", currentTerm,
		"service_id", pm.serviceID.String())

	if err := pm.consensusState.UpdateTermAndSave(ctx, requestTerm); err != nil {
		return mterrors.Wrap(err, "failed to update consensus term")
	}

	return nil
}

// validateTermExactMatch validates that the request term exactly matches the current term.
// Unlike validateAndUpdateTerm, this does NOT update the term automatically.
// This is used for Promote to ensure the node was properly recruited before promotion.
func (pm *MultiPoolerManager) validateTermExactMatch(ctx context.Context, requestTerm int64, force bool) error {
	if force {
		return nil // Skip validation if force is set
	}

	currentTerm, err := pm.getCurrentTermNumber(ctx)
	if err != nil {
		return fmt.Errorf("failed to get current term: %w", err)
	}

	// Check if consensus term has been initialized
	if currentTerm == 0 {
		pm.logger.ErrorContext(ctx, "Consensus term not initialized - node not recruited",
			"service_id", pm.serviceID.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			"consensus term not initialized - node must be recruited via BeginTerm first")
	}

	// Require exact match - do not update term automatically
	if requestTerm != currentTerm {
		pm.logger.ErrorContext(ctx, "Promote term mismatch - node not recruited for this term",
			"request_term", requestTerm,
			"current_term", currentTerm,
			"service_id", pm.serviceID.String())
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION,
			fmt.Sprintf("term mismatch: node not recruited for term %d (current term is %d). "+
				"Coordinator must call BeginTerm first to recruit this node",
				requestTerm, currentTerm))
	}

	return nil
}

// checkDemotionState checks the current state to determine what steps remain
func (pm *MultiPoolerManager) checkDemotionState(ctx context.Context) (*demotionState, error) {
	state := &demotionState{}

	// Check topology state
	pm.mu.Lock()
	poolerType := pm.multipooler.Type
	servingStatus := pm.multipooler.ServingStatus
	pm.mu.Unlock()

	state.isReplicaInTopology = (poolerType == clustermetadatapb.PoolerType_REPLICA)
	state.isNotServing = (servingStatus == clustermetadatapb.PoolerServingStatus_NOT_SERVING)

	// Check if PostgreSQL is in recovery mode (canonical way to check if read-only)
	isPrimary, err := pm.isPrimary(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to check recovery status", "error", err)
		return nil, mterrors.Wrap(err, "failed to check recovery status")
	}
	state.isReadOnly = !isPrimary

	// Capture current LSN
	state.finalLSN, err = pm.getWALPosition(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to get LSN", "error", err)
		return nil, mterrors.Wrap(err, "failed to get LSN")
	}

	pm.logger.InfoContext(ctx, "Checked demotion state",
		"is_not_serving", state.isNotServing,
		"is_replica_in_topology", state.isReplicaInTopology,
		"is_read_only", state.isReadOnly,
		"is_primary", isPrimary,
		"pooler_type", poolerType,
		"serving_status", servingStatus)

	return state, nil
}

// setNotServing transitions the pooler to NOT_SERVING status during demotion.
// This uses the StateManager to coordinate:
//   - Query service rejects all queries
//   - Heartbeat writer is stopped
//   - Multipooler record is updated
//
// After this, topology is synced to persist the state change.
func (pm *MultiPoolerManager) setNotServing(ctx context.Context, state *demotionState) error {
	if state.isNotServing {
		pm.logger.InfoContext(ctx, "Already in NOT_SERVING state, skipping")
		return nil
	}

	pm.logger.InfoContext(ctx, "Transitioning to NOT_SERVING")

	// Use the serving state manager to transition components.
	// This updates query service, heartbeat, and the multipooler record.
	if err := pm.servingState.SetState(ctx, pm.multipooler.Type, clustermetadatapb.PoolerServingStatus_NOT_SERVING); err != nil {
		return mterrors.Wrap(err, "failed to transition to NOT_SERVING")
	}

	// Notify the topology publisher of the new state. The write to etcd happens
	// asynchronously so that a temporarily unreachable etcd does not block demotion.
	if err := pm.topoPublisher.Notify(ctx, pm.multipooler); err != nil {
		pm.logger.ErrorContext(ctx, "topoPublisher.Notify called without action lock", "error", err)
	}

	pm.logger.InfoContext(ctx, "Transitioned to NOT_SERVING successfully")
	return nil
}

// restartPostgresAsStandby restarts PostgreSQL as a standby server
// This creates standby.signal and restarts PostgreSQL via pgctld
func (pm *MultiPoolerManager) restartPostgresAsStandby(ctx context.Context, state *demotionState) error {
	if state.isReadOnly {
		pm.logger.InfoContext(ctx, "PostgreSQL already running as standby, skipping")
		return nil
	}

	if pm.pgctldClient == nil {
		return mterrors.New(mtrpcpb.Code_FAILED_PRECONDITION, "pgctld client not initialized")
	}

	pm.logger.InfoContext(ctx, "Restarting PostgreSQL as standby")
	req := &pgctldpb.RestartRequest{
		Mode:      "fast",
		Timeout:   nil, // Use default timeout
		Port:      0,   // Use default port
		ExtraArgs: nil,
		AsStandby: true, // Create standby.signal before restart
	}

	resp, err := pm.pgctldClient.Restart(ctx, req)
	if err != nil {
		return mterrors.Wrap(err, "failed to restart as standby")
	}

	// Reopen connections after restart
	pm.reopenConnections(ctx)

	// Wait for database connection to be ready after restart
	if err := pm.waitForDatabaseConnection(ctx); err != nil {
		return mterrors.Wrap(err, "failed to connect to database after restart")
	}

	// Verify server is in recovery mode (standby)
	inRecovery, err := pm.isInRecovery(ctx)
	if err != nil {
		return mterrors.Wrap(err, "failed to verify standby status")
	}

	if !inRecovery {
		return mterrors.New(mtrpcpb.Code_INTERNAL, "server not in recovery mode after restart as standby")
	}

	pm.logger.InfoContext(ctx, "PostgreSQL is now running as a standby",
		"pid", resp.Pid,
		"message", resp.Message)

	return nil
}

// getActiveWriteConnections returns connections that are performing write operations
func (pm *MultiPoolerManager) getActiveWriteConnections(ctx context.Context) ([]int32, error) {
	// Query for connections doing write operations
	// Note: this is temporary, we can refactor this once we
	// have the query pool. Thinking that we should have a
	// specific user for the write pool and we can kill all connections
	// associated with that user.
	sql := `
		SELECT pid
		FROM pg_stat_activity
		WHERE pid != pg_backend_pid()
		  AND datname IS NOT NULL
		  AND backend_type = 'client backend'
		  AND state = 'active'
		  AND query NOT ILIKE 'SELECT%'
		  AND query NOT ILIKE 'SHOW%'
		  AND query NOT ILIKE 'BEGIN%'
		  AND query NOT ILIKE 'COMMIT%'
		  AND query NOT ILIKE 'ROLLBACK%'
		  AND query != '<IDLE>'`

	result, err := pm.query(ctx, sql)
	if err != nil {
		return nil, err
	}

	var pids []int32
	if result != nil {
		for _, row := range result.Rows {
			pid, err := executor.GetInt32(row, 0)
			if err != nil {
				return nil, fmt.Errorf("failed to parse pid: %w", err)
			}
			pids = append(pids, pid)
		}
	}

	return pids, nil
}

// terminateWriteConnections terminates connections performing write operations
func (pm *MultiPoolerManager) terminateWriteConnections(ctx context.Context) (int32, error) {
	pids, err := pm.getActiveWriteConnections(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to get active write connections", "error", err)
		return 0, mterrors.Wrap(err, "failed to get active write connections")
	}

	if len(pids) == 0 {
		pm.logger.InfoContext(ctx, "No active write connections to terminate")
		return 0, nil
	}

	pm.logger.WarnContext(ctx, "Terminating connections still performing writes after drain",
		"count", len(pids),
		"pids", pids)

	// Terminate each write connection
	for _, pid := range pids {
		if err := pm.execArgs(ctx, "SELECT pg_terminate_backend($1)", pid); err != nil {
			pm.logger.WarnContext(ctx, "Failed to terminate write connection", "pid", pid, "error", err)
		}
	}

	return int32(len(pids)), nil
}

// drainWriteActivity monitors for write activity during emergency demotion.
// During the drain, it monitors for write activity every 100ms.
// If 2 consecutive checks show no writes, exits early.
func (pm *MultiPoolerManager) drainWriteActivity(ctx context.Context, drainTimeout time.Duration) error {
	// Monitor for write activity during drain
	pm.logger.InfoContext(ctx, "Monitoring for write activity during drain", "duration", drainTimeout)
	drainCtx, cancel := context.WithTimeout(ctx, drainTimeout)
	defer cancel()

	monitorTicker := time.NewTicker(100 * time.Millisecond)
	defer monitorTicker.Stop()

	consecutiveNoWrites := 0
	drainComplete := false

	for !drainComplete {
		select {
		case <-drainCtx.Done():
			pm.logger.InfoContext(ctx, "Drain timeout completed")
			drainComplete = true

		case <-monitorTicker.C:
			// Check for write activity
			pids, err := pm.getActiveWriteConnections(ctx)
			if err != nil {
				pm.logger.WarnContext(ctx, "Failed to check for write activity during drain", "error", err)
				consecutiveNoWrites = 0 // Reset on error
			} else if len(pids) > 0 {
				pm.logger.WarnContext(ctx, "Detected write activity during drain",
					"count", len(pids),
					"pids", pids)
				consecutiveNoWrites = 0 // Reset counter
			} else {
				// No writes detected
				consecutiveNoWrites++
				if consecutiveNoWrites >= 2 {
					pm.logger.InfoContext(ctx, "No write activity detected for 2 consecutive checks, exiting drain early")
					drainComplete = true
				}
			}
		}
	}

	return nil
}

// checkPromotionState checks the current state to determine what steps remain
func (pm *MultiPoolerManager) checkPromotionState(ctx context.Context, syncReplicationConfig *multipoolermanagerdatapb.ConfigureSynchronousReplicationRequest) (*promotionState, error) {
	state := &promotionState{}

	// Check PostgreSQL promotion state
	isInRecovery, err := pm.isInRecovery(ctx)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to check recovery status", "error", err)
		return nil, mterrors.Wrap(err, "failed to check recovery status")
	}

	state.isPrimaryInPostgres = !isInRecovery

	if state.isPrimaryInPostgres {
		// Get current primary LSN
		state.currentLSN, err = pm.getPrimaryLSN(ctx)
		if err != nil {
			pm.logger.ErrorContext(ctx, "Failed to get current LSN", "error", err)
			return nil, err
		}
	}

	// Check topology state
	pm.mu.Lock()
	poolerType := pm.multipooler.Type
	pm.mu.Unlock()

	state.isPrimaryInTopology = (poolerType == clustermetadatapb.PoolerType_PRIMARY)

	// Default: if no sync config requested, consider it as matching (no requirements to check)
	state.syncReplicationMatches = true

	// Check sync replication state if config was provided
	if syncReplicationConfig != nil {
		if state.isPrimaryInPostgres {
			state.syncReplicationMatches = false
			currentConfig, err := pm.getSynchronousReplicationConfig(ctx)
			if err != nil {
				pm.logger.WarnContext(ctx, "Failed to get current sync replication config", "error", err)
			}
			if err == nil {
				state.syncReplicationMatches = pm.syncReplicationConfigMatches(currentConfig, syncReplicationConfig)
			}
		} else {
			// Node is a standby being promoted - it doesn't have sync replication configured yet
			state.syncReplicationMatches = false
		}
	}

	pm.logger.InfoContext(ctx, "Checked promotion state",
		"is_primary_in_postgres", state.isPrimaryInPostgres,
		"is_primary_in_topology", state.isPrimaryInTopology,
		"sync_replication_matches", state.syncReplicationMatches)

	return state, nil
}

// promoteStandbyToPrimary calls pg_promote() and waits for promotion to complete
func (pm *MultiPoolerManager) promoteStandbyToPrimary(ctx context.Context, state *promotionState) error {
	// Return early if already promoted
	if state.isPrimaryInPostgres {
		pm.logger.InfoContext(ctx, "PostgreSQL already promoted, skipping")
		return nil
	}

	// Call pg_promote() to promote standby to primary
	pm.logger.InfoContext(ctx, "PostgreSQL promotion needed")
	pm.logger.InfoContext(ctx, "Calling pg_promote() to promote standby to primary")
	pm.promotionInProgress.Store(true)

	// Broadcast immediately so subscribers (multiorch) see PROMOTING server
	// status before the periodic health stream interval fires. Without this,
	// the flag may be set and cleared within a single interval, making it
	// invisible to subscribers. We reset the promotionInProgress flag and
	// broadcast again after promotion completes to ensure the full window is
	// visible.
	pm.broadcastHealth()

	// TODO: this defer fires before configureReplicationAfterPromotion and
	// rules.updateRule in the caller, so multiorch sees PRIMARY status while sync
	// replication is not yet configured and rule history has not been written. If
	// we want the PROMOTING window to cover the full Promote RPC (including the
	// sync standby ack gate), the defer should move to the caller instead.
	defer func() {
		pm.promotionInProgress.Store(false)
		pm.broadcastHealth()
	}()

	if err := pm.exec(ctx, "SELECT pg_promote()"); err != nil {
		pm.logger.ErrorContext(ctx, "Failed to call pg_promote()", "error", err)
		return mterrors.Wrap(err, "failed to promote standby")
	}

	// Wait for promotion to complete: pg_is_in_recovery()=false AND postgres_ready=true.
	// Keeping promotionInProgress set until postgres_ready ensures multiorch suppresses
	// PrimaryIsDead for the full window — including the gap between pg_is_in_recovery()=false
	// and postgres actually accepting connections.
	pm.logger.InfoContext(ctx, "Waiting for promotion to complete")
	if err := pm.waitForPromotionComplete(ctx); err != nil {
		return err
	}

	// Clear primary_conninfo after promotion to prevent accidental replication on restart
	if err := pm.resetPrimaryConnInfo(ctx); err != nil {
		pm.logger.WarnContext(ctx, "Failed to clear primary_conninfo after promotion", "error", err)
		// Log but don't fail - promotion already succeeded
	}

	return nil
}

// waitForPromotionComplete polls until the node has left recovery mode AND postgres
// is accepting connections. Both conditions are required: pg_is_in_recovery()=false
// confirms the WAL-level promotion, and postgres_ready=true confirms clients can
// connect. Clearing promotionInProgress only when both are true ensures multiorch's
// PrimaryIsDeadAnalyzer suppression window matches the full visibility gap.
func (pm *MultiPoolerManager) waitForPromotionComplete(ctx context.Context) error {
	ticker := time.NewTicker(100 * time.Millisecond)
	defer ticker.Stop()

	promotionTimeout := 30 * time.Second
	promotionCtx, cancel := context.WithTimeout(ctx, promotionTimeout)
	defer cancel()

	promotedFromRecovery := false
	for {
		select {
		case <-promotionCtx.Done():
			pm.logger.ErrorContext(ctx, "Timeout waiting for promotion to complete")
			return mterrors.New(mtrpcpb.Code_DEADLINE_EXCEEDED,
				fmt.Sprintf("timeout waiting for promotion to complete after %v", promotionTimeout))

		case <-ticker.C:
			if !promotedFromRecovery {
				isInRecovery, err := pm.isInRecovery(promotionCtx)
				if err != nil {
					pm.logger.ErrorContext(ctx, "Failed to check recovery status during promotion", "error", err)
					return mterrors.Wrap(err, "failed to check recovery status")
				}
				if !isInRecovery {
					pm.logger.InfoContext(ctx, "Postgres left recovery mode, waiting for connections to be accepted")
					promotedFromRecovery = true
				}
			}

			if promotedFromRecovery && pm.isPostgresReady(promotionCtx) {
				pm.logger.InfoContext(ctx, "Promotion completed successfully - node is now primary and accepting connections")
				return nil
			}
		}
	}
}

// updateTopologyAfterPromotion updates the pooler type in topology from REPLICA to PRIMARY
func (pm *MultiPoolerManager) updateTopologyAfterPromotion(ctx context.Context, state *promotionState) error {
	// Return early if already updated
	if state.isPrimaryInTopology {
		pm.logger.InfoContext(ctx, "Topology already updated, skipping")
		return nil
	}

	pm.logger.InfoContext(ctx, "Topology update needed")
	pm.logger.InfoContext(ctx, "Updating pooler type in topology to PRIMARY")

	// Use the serving state manager to transition components (query service, heartbeat, health streamer)
	// and update the multipooler record. The serving status stays SERVING during promotion.
	if err := pm.servingState.SetState(ctx, clustermetadatapb.PoolerType_PRIMARY, clustermetadatapb.PoolerServingStatus_SERVING); err != nil {
		return mterrors.Wrap(err, "failed to set serving state for promotion")
	}

	// Notify the topology publisher of the new state. The write to etcd happens
	// asynchronously so that a temporarily unreachable etcd does not block promotion.
	if err := pm.topoPublisher.Notify(ctx, pm.multipooler); err != nil {
		pm.logger.ErrorContext(ctx, "topoPublisher.Notify called without action lock", "error", err)
	}

	return nil
}

// configureReplicationAfterPromotion applies synchronous replication configuration
func (pm *MultiPoolerManager) configureReplicationAfterPromotion(ctx context.Context, state *promotionState, syncReplicationConfig *multipoolermanagerdatapb.ConfigureSynchronousReplicationRequest) error {
	if syncReplicationConfig == nil {
		return nil // No configuration requested
	}

	// Return early if already configured
	if state.syncReplicationMatches {
		pm.logger.InfoContext(ctx, "Sync replication already configured, skipping")
		return nil
	}

	pm.logger.InfoContext(ctx, "Sync replication configuration needed")
	pm.logger.InfoContext(ctx, "Configuring synchronous replication for new cohort")
	// Use the locked version since we're already holding the action lock from Promote
	err := pm.configureSynchronousReplicationLocked(ctx,
		syncReplicationConfig.SynchronousCommit,
		syncReplicationConfig.SynchronousMethod,
		syncReplicationConfig.NumSync,
		syncReplicationConfig.StandbyIds,
		syncReplicationConfig.ReloadConfig,
		syncReplicationConfig.Force)
	if err != nil {
		pm.logger.ErrorContext(ctx, "Failed to configure synchronous replication", "error", err)
		return mterrors.Wrap(err, "promotion succeeded but failed to configure synchronous replication")
	}

	return nil
}

// ReplicationLag returns the current replication lag from the heartbeat reader
func (pm *MultiPoolerManager) ReplicationLag(ctx context.Context) (time.Duration, error) {
	if err := pm.checkReady(); err != nil {
		return 0, err
	}

	if pm.replTracker == nil {
		return 0, mterrors.New(mtrpcpb.Code_UNAVAILABLE, "replication tracker not initialized")
	}

	return pm.replTracker.HeartbeatReader().Status()
}

// Start initializes the MultiPoolerManager
func (pm *MultiPoolerManager) Start(senv *servenv.ServEnv) {
	// Open the database connections, connection pool manager, and start background operations
	// TODO: This should be managed by a proper state manager (like tm_state.go)
	pm.Open()

	// Start loading multipooler record from topology asynchronously
	go pm.loadMultiPoolerFromTopo()

	senv.OnRunE(func() error {
		// Block until manager is ready or error before registering gRPC services
		// Use load timeout from manager configuration
		waitCtx, cancel := context.WithTimeout(pm.ctx, pm.loadTimeout)
		defer cancel()

		pm.logger.Info("Waiting for manager to reach ready state before registering gRPC services")
		if err := pm.WaitUntilReady(waitCtx); err != nil {
			pm.logger.Error("Manager failed to reach ready state during startup", "error", err)
			return fmt.Errorf("manager failed to reach ready state: %w", err)
		}
		pm.logger.Info("Manager reached ready state, will register gRPC services")

		pm.logger.Info("MultiPoolerManager started")
		pm.qsc.RegisterGRPCServices()
		pm.logger.Info("Query service controller registered")

		// Register manager gRPC services
		pm.registerGRPCServices()
		pm.logger.Info("MultiPoolerManager gRPC services registered")
		return nil
	})
}

// WaitUntilReady blocks until the manager reaches Ready or Error state, or
// the context is cancelled. Returns nil if Ready, or an error if Error state
// or context cancelled. This should be called after Start() to ensure
// initialization is complete before accepting RPC requests.
//
// Thread-safety: This method waits on a channel that is closed when the state
// changes to Ready or Error, allowing efficient notification without polling.
func (pm *MultiPoolerManager) WaitUntilReady(ctx context.Context) error {
	select {
	case <-ctx.Done():
		return fmt.Errorf("waiting for manager ready cancelled: %w", ctx.Err())
	case <-pm.readyChan:
		// State has changed to Ready or Error, check which one
		pm.mu.Lock()
		state := pm.state
		stateError := pm.stateError
		pm.mu.Unlock()

		switch state {
		case ManagerStateReady:
			pm.logger.InfoContext(ctx, "Manager is ready")
			return nil
		case ManagerStateError:
			pm.logger.ErrorContext(ctx, "Manager failed to initialize", "error", stateError)
			return fmt.Errorf("manager is in error state: %w", stateError)
		default:
			// This shouldn't happen - channel was closed but state isn't terminal
			return fmt.Errorf("unexpected state after ready signal: %s", state)
		}
	}
}

// postgresState represents the state of PostgreSQL for monitoring
type postgresState struct {
	pgctldAvailable          bool
	dirInitialized           bool
	postgresRunning          bool
	backupsAvailable         bool
	isPrimary                bool
	bootstrapSentinelPresent bool
	// primaryTerm is the coordinator term at which this pooler is the primary
	// per the highest known rule. 0 if we are not the primary for that rule.
	primaryTerm int64
}

// postgresStateEqual reports whether two postgresState values are identical.
func postgresStateEqual(a, b postgresState) bool {
	return a.pgctldAvailable == b.pgctldAvailable &&
		a.dirInitialized == b.dirInitialized &&
		a.postgresRunning == b.postgresRunning &&
		a.backupsAvailable == b.backupsAvailable &&
		a.isPrimary == b.isPrimary &&
		a.bootstrapSentinelPresent == b.bootstrapSentinelPresent &&
		a.primaryTerm == b.primaryTerm
}

// remedialAction represents actions the postgres monitor can take
type remedialAction int

const (
	remedialActionNone remedialAction = iota
	remedialActionStartPostgres
	remedialActionRestoreFromBackup
	remedialActionAdjustTypeToPrimary
	remedialActionAdjustTypeToReplica
	remedialActionCreateFirstBackup
)

// monitorPostgresIteration performs one iteration of PostgreSQL monitoring.
// Returns the discovered postgres state on success, or an error if the state
// could not be determined. The caller is responsible for transition detection
// and broadcasting health updates.
func (pm *MultiPoolerManager) monitorPostgresIteration(ctx context.Context) (postgresState, error) {
	const (
		reasonPgctldUnavailable = "pgctld_unavailable"
		reasonPostgresRunning   = "postgres_running"
	)

	// Wait for manager to be ready
	if err := pm.checkReady(); err != nil {
		pm.logger.InfoContext(pm.ctx, "MonitorPostgres: manager not ready yet")
		return postgresState{}, err
	}

	// Skip all action while awaiting a rewind after emergency demotion.
	if pm.rewindPending.Load() {
		pm.logger.InfoContext(ctx, "MonitorPostgres: skipping, awaiting rewind after demotion")
		return postgresState{}, nil
	}

	// Discover current state
	currentState, err := pm.discoverPostgresState(ctx)
	if err != nil {
		// Log and skip this tick; the next iteration will retry. A persistent
		// failure keeps the error loud rather than silently triggering the wrong
		// remediation. pgctld unavailability gets its dedicated reason code so
		// the monitor's log-dedup path behaves as before.
		if !currentState.pgctldAvailable {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: pgctld unavailable", "error", err)
			pm.pgMonitorLastLoggedReason = reasonPgctldUnavailable
		} else {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to discover state; skipping tick", "error", err)
		}
		return postgresState{}, err
	}

	// Determine what remediation is needed
	action := pm.determineRemedialAction(currentState)
	if action == remedialActionNone {
		// No action needed - just log status
		if currentState.postgresRunning {
			pm.setMonitorReason(ctx, reasonPostgresRunning, "MonitorPostgres: PostgreSQL is running")
		}
		return currentState, nil
	}

	// Acquire action lock before taking remedial action
	lockCtx, err := pm.actionLock.Acquire(ctx, "MonitorPostgres")
	if err != nil {
		pm.logger.InfoContext(ctx, "MonitorPostgres: failed to acquire action lock", "error", err)
		return postgresState{}, err
	}
	defer pm.actionLock.Release(lockCtx)

	// Re-check rewindPending after acquiring the lock: EmergencyDemote sets this flag
	// while holding the lock, so we may have been waiting while it demoted the node.
	if pm.rewindPending.Load() {
		pm.logger.InfoContext(ctx, "MonitorPostgres: skipping after lock acquire, rewind now pending")
		return postgresState{}, nil
	}

	// Re-verify state after acquiring lock (conditions may have changed)
	currentState, err = pm.discoverPostgresState(lockCtx)
	if err != nil {
		if !currentState.pgctldAvailable {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: pgctld unavailable after lock acquire", "error", err)
			pm.pgMonitorLastLoggedReason = reasonPgctldUnavailable
		} else {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to re-discover state after lock acquire; skipping tick", "error", err)
		}
		return postgresState{}, err
	}

	// Re-determine action based on current state
	action = pm.determineRemedialAction(currentState)

	// Take remedial action with lock held
	pm.takeRemedialAction(lockCtx, action, currentState)

	return currentState, nil
}

// discoverPostgresState discovers the current state of PostgreSQL. Returns an
// error only when a probe fails in a way that leaves the state genuinely
// ambiguous (e.g. a sentinel stat failing for reasons other than NotExist);
// callers must refuse to take remedial action in that case. pgctld being
// unavailable is not such a case — it is represented as pgctldAvailable=false.
func (pm *MultiPoolerManager) discoverPostgresState(ctx context.Context) (postgresState, error) {
	state := postgresState{}

	// Check if pgctld client is available
	if pm.pgctldClient == nil {
		return state, nil // All fields remain false
	}
	state.pgctldAvailable = true

	// Get status from pgctld. On failure return both the state (with
	// pgctldAvailable=false) and the error so the caller can log the
	// underlying cause while still reading the unavailability flag.
	statusResp, err := pm.pgctldClient.Status(ctx, &pgctldpb.StatusRequest{})
	if err != nil {
		state.pgctldAvailable = false
		return state, fmt.Errorf("pgctld status: %w", err)
	}

	// Check if directory is initialized
	state.dirInitialized = (statusResp.Status != pgctldpb.ServerStatus_NOT_INITIALIZED)

	// Check if Postgres is running
	state.postgresRunning = (statusResp.Status == pgctldpb.ServerStatus_RUNNING)
	if state.postgresRunning {
		var err error
		state.isPrimary, err = pm.isPrimary(ctx)
		if err != nil {
			pm.logger.ErrorContext(ctx, "Failed to determine primary status", "error", err)
		}
		// Lock-free first pass from the monitor: use the inconsistent read,
		// which falls back to the cached rule when postgres is unreachable.
		if cs, err := pm.getInconsistentConsensusStatus(ctx); err == nil {
			state.primaryTerm = commonconsensus.LeaderTerm(cs)
		}
	}

	// Check if backups are available (only if directory not initialized)
	if !state.dirInitialized {
		state.backupsAvailable = pm.hasCompleteBackups(ctx)
	}

	sentinelPresent, err := pm.hasBootstrapSentinel()
	if err != nil {
		// We can't tell whether a stale sentinel needs handling. Surface as an
		// error so the monitor skips this tick; the operator should investigate.
		return state, fmt.Errorf("check bootstrap sentinel: %w", err)
	}
	state.bootstrapSentinelPresent = sentinelPresent

	return state, nil
}

// primaryTermLocked returns the coordinator term of the pooler's current
// committed rule if this pooler is the primary per that rule. Uses a
// consistent consensus status read and therefore requires the action lock.
// Returns (0, nil) when the rule does not name this pooler as primary.
// Returns (0, err) only when the consensus status cannot be read at all —
// callers that need to distinguish "confirmed not primary" from "unknown"
// must inspect the error.
//
// Callers that cannot hold the action lock should read
// getInconsistentConsensusStatus themselves and pass the result to
// consensus.LeaderTerm.
func (pm *MultiPoolerManager) primaryTermLocked(ctx context.Context) (int64, error) {
	cs, err := pm.getConsensusStatus(ctx)
	if err != nil {
		return 0, fmt.Errorf("failed to read consensus status: %w", err)
	}
	return commonconsensus.LeaderTerm(cs), nil
}

// setMonitorReason sets the current monitor state reason and logs on state changes.
// This avoids log spam during repeated monitor iterations with the same state.
func (pm *MultiPoolerManager) setMonitorReason(ctx context.Context, reason, message string) {
	if pm.pgMonitorLastLoggedReason != reason {
		pm.logger.InfoContext(ctx, message)
		pm.pgMonitorLastLoggedReason = reason
	}
}

// determineRemedialAction decides what action to take based on discovered state.
// This is pure decision logic with no side effects.
func (pm *MultiPoolerManager) determineRemedialAction(currentState postgresState) remedialAction {
	// Pgctld unavailable: No action possible
	if !currentState.pgctldAvailable {
		return remedialActionNone
	}

	// Postgres is running: Check if pooler type needs adjustment
	if currentState.postgresRunning {
		if currentState.isPrimary && pm.getPoolerType() != clustermetadatapb.PoolerType_PRIMARY {
			return remedialActionAdjustTypeToPrimary
		}
		if !currentState.isPrimary && pm.getPoolerType() == clustermetadatapb.PoolerType_PRIMARY {
			return remedialActionAdjustTypeToReplica
		}
		// Postgres is standby and type is already REPLICA, but check if the resignation
		// signal needs to be (re-)published. This handles the case where the signal was
		// lost after a process restart following EmergencyDemote.
		if !currentState.isPrimary {
			pm.mu.Lock()
			resigned := pm.resignedLeaderAtTerm
			pm.mu.Unlock()
			if currentState.primaryTerm != 0 && resigned == 0 {
				return remedialActionAdjustTypeToReplica
			}
		}
		return remedialActionNone // Pooler type already matches
	}

	// A sentinel from a prior first-backup attempt means bootstrap crashed
	// mid-flight. Any on-disk pg_data is stale — force the create-first-backup
	// path so createFirstBackupAndInitializeLocked can clean up and retry.
	if currentState.bootstrapSentinelPresent {
		return remedialActionCreateFirstBackup
	}

	// Postgres not running: Try to start or restore
	if currentState.dirInitialized {
		return remedialActionStartPostgres
	}

	if currentState.backupsAvailable {
		return remedialActionRestoreFromBackup
	}

	// Directory not initialized and no backups: try to create the first backup
	return remedialActionCreateFirstBackup
}

// takeRemedialAction executes the specified remedial action.
// Caller must hold the action lock.
func (pm *MultiPoolerManager) takeRemedialAction(ctx context.Context, action remedialAction, state postgresState) {
	// Assert that the action lock is held
	if err := AssertActionLockHeld(ctx); err != nil {
		pm.logger.ErrorContext(ctx, "takeRemedialAction called without action lock", "error", err)
		return
	}

	const (
		reasonPostgresRunning            = "postgres_running"
		reasonStartingPostgres           = "starting_postgres"
		reasonRestoringFromBackup        = "restoring_from_backup"
		reasonCreatingFirstBackup        = "creating_first_backup"
		reasonWaitingForFirstBackupLease = "waiting_for_first_backup_lease"
	)

	switch action {
	case remedialActionNone:
		// No action to take
		return

	case remedialActionAdjustTypeToPrimary:
		pm.setMonitorReason(ctx, reasonPostgresRunning, "MonitorPostgres: PostgreSQL is running")
		pm.logger.InfoContext(ctx, "MonitorPostgres: PostgreSQL is running and primary")
		pm.logger.InfoContext(ctx, "MonitorPostgres: Changing pooler type to primary")
		if err := pm.changeTypeLocked(ctx, clustermetadatapb.PoolerType_PRIMARY); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to change pooler type to primary", "error", err)
		}

	case remedialActionAdjustTypeToReplica:
		pm.setMonitorReason(ctx, reasonPostgresRunning, "MonitorPostgres: PostgreSQL is running")
		pm.logger.InfoContext(ctx, "MonitorPostgres: PostgreSQL is running but not primary")
		pm.logger.InfoContext(ctx, "MonitorPostgres: Changing pooler type to replica")
		// Signal voluntary resignation so the coordinator can trigger an immediate
		// election. Use the primary_term (the term at which we were elected) since
		// the coordinator uses this to decide whether the signal is still active.
		if state.primaryTerm != 0 {
			if err := pm.setResignedLeaderAtTerm(ctx, state.primaryTerm); err != nil {
				pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to set resigned primary term", "error", err)
				return
			}
		}
		if err := pm.changeTypeLocked(ctx, clustermetadatapb.PoolerType_REPLICA); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to change pooler type to replica", "error", err)
		}

	case remedialActionStartPostgres:
		// Honour the in-memory flag set by tests and demos to suppress auto-restart
		// during controlled failovers.
		if pm.postgresRestartsDisabled.Load() {
			pm.logger.InfoContext(ctx, "MonitorPostgres: skipping start, postgres restarts disabled")
			return
		}
		pm.setMonitorReason(ctx, reasonStartingPostgres, "MonitorPostgres: PostgreSQL initialized but not running, starting PostgreSQL")
		if err := pm.actionLock.SetAction(ctx, multipoolermanagerdatapb.PostgresAction_POSTGRES_ACTION_STARTING); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to set action", "error", err)
		}
		if err := pm.startPostgres(ctx); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to start PostgreSQL, will retry", "error", err)
		}

	case remedialActionRestoreFromBackup:
		pm.setMonitorReason(ctx, reasonRestoringFromBackup, "MonitorPostgres: directory not initialized but backups available, restoring from backup")
		if err := pm.actionLock.SetAction(ctx, multipoolermanagerdatapb.PostgresAction_POSTGRES_ACTION_RESTORING_FROM_BACKUP); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to set action", "error", err)
		}
		if err := pm.restoreAndStartPostgres(ctx); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to restore from backup, will retry", "error", err)
		}

	case remedialActionCreateFirstBackup:
		pm.setMonitorReason(ctx, reasonCreatingFirstBackup, "MonitorPostgres: no backup found, attempting to create one")
		if err := pm.actionLock.SetAction(ctx, multipoolermanagerdatapb.PostgresAction_POSTGRES_ACTION_CREATING_FIRST_BACKUP); err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to set action", "error", err)
		}
		busy, backupFound, err := pm.createFirstBackupAndInitializeLocked(ctx)
		if busy {
			pm.setMonitorReason(ctx, reasonWaitingForFirstBackupLease, "MonitorPostgres: backup lease held by another pooler, waiting")
		} else if err != nil {
			pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to create first backup, will retry", "error", err)
		} else if backupFound {
			// Another pooler created the backup just before we acquired the lease.
			// Restore immediately rather than waiting for the next monitor iteration.
			pm.setMonitorReason(ctx, reasonRestoringFromBackup, "MonitorPostgres: first backup found; restoring")
			if err := pm.actionLock.SetAction(ctx, multipoolermanagerdatapb.PostgresAction_POSTGRES_ACTION_RESTORING_FROM_BACKUP); err != nil {
				pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to set action", "error", err)
			}
			if err := pm.restoreAndStartPostgres(ctx); err != nil {
				pm.logger.ErrorContext(ctx, "MonitorPostgres: failed to restore from backup, will retry", "error", err)
			}
		}
	}
}

// hasCompleteBackups checks if there are any complete backups available
func (pm *MultiPoolerManager) hasCompleteBackups(ctx context.Context) bool {
	// Get list of backups
	backups, err := pm.listBackups(ctx)
	if err != nil {
		return false
	}

	// Filter to only complete backups
	for _, b := range backups {
		if b.Status == multipoolermanagerdatapb.BackupMetadata_COMPLETE {
			return true
		}
	}

	return false
}

// startPostgres starts PostgreSQL via pgctld
func (pm *MultiPoolerManager) startPostgres(ctx context.Context) error {
	pm.logger.InfoContext(ctx, "MonitorPostgres: Attempting to restart PostgreSQL")
	if pm.pgctldClient == nil {
		return errors.New("pgctld client not available")
	}

	_, err := pm.pgctldClient.Start(ctx, &pgctldpb.StartRequest{})
	if err != nil {
		return fmt.Errorf("MonitorPostgres: failed to start PostgreSQL: %w", err)
	}

	pm.logger.InfoContext(ctx, "MonitorPostgres: PostgreSQL started successfully")

	// Reopen connections after postgres restart to replace stale socket FDs.
	// Only when connection pool is initialized (the manager may not have
	// connection infrastructure in unit tests with minimal setup).
	if pm.connPoolMgr != nil {
		pm.reopenConnections(ctx)

		// Wait for database connection to be ready
		if err := pm.waitForDatabaseConnection(ctx); err != nil {
			return fmt.Errorf("MonitorPostgres: database not ready after restart: %w", err)
		}
	}

	return nil
}

// restoreAndStartPostgres restores from backup and starts PostgreSQL.
// This is used by MonitorPostgres for auto-restore functionality.
// Caller must hold the action lock.
func (pm *MultiPoolerManager) restoreAndStartPostgres(ctx context.Context) error {
	// Re-check status to ensure conditions haven't changed
	// (e.g., another process may have initialized or started postgres while we waited for lock)
	if pm.pgctldClient != nil {
		statusResp, err := pm.pgctldClient.Status(ctx, &pgctldpb.StatusRequest{})
		if err == nil {
			// If directory is now initialized, skip restore
			if statusResp.Status != pgctldpb.ServerStatus_NOT_INITIALIZED {
				pm.logger.InfoContext(ctx, "MonitorPostgres: directory became initialized after acquiring lock, skipping restore")
				return nil
			}
		}
		// If status check fails, continue with restore attempt
	}

	// Get the latest complete backup
	backups, err := pm.listBackups(ctx)
	if err != nil {
		return fmt.Errorf("failed to list backups: %w", err)
	}

	// Filter to only complete backups
	var completeBackups []*multipoolermanagerdatapb.BackupMetadata
	for _, b := range backups {
		if b.Status == multipoolermanagerdatapb.BackupMetadata_COMPLETE {
			completeBackups = append(completeBackups, b)
		}
	}

	if len(completeBackups) == 0 {
		return errors.New("no complete backups available")
	}

	// Use the latest complete backup (last in the list)
	latestBackup := completeBackups[len(completeBackups)-1]

	pm.logger.InfoContext(ctx, "MonitorPostgres: restoring from backup",
		"backup_id", latestBackup.BackupId)

	// Perform the restore
	if err := telemetry.WithSpan(ctx, "monitor-postgres-restore", func(ctx context.Context) error {
		return pm.restoreFromBackupLocked(ctx, latestBackup.BackupId)
	}); err != nil {
		return fmt.Errorf("failed to restore from backup: %w", err)
	}

	pm.logger.InfoContext(ctx, "MonitorPostgres: successfully restored from backup",
		"backup_id", latestBackup.BackupId,
		"shard", pm.getShardID(),
		"term", pm.consensusState.revocation.GetRevokedBelowTerm())

	return nil
}
